#!/usr/bin/env python3
"""Regenerate every generated manuscript asset from the stored results and compare it with revision/source.

    python verify_manuscript_assets.py

Each asset generator runs in a scratch copy of extension/ (so no results file or RESULTS.md in the package is
rewritten) and writes into a temporary folder; every .tex file it writes must equal the file of the same name in
revision/source byte for byte, and every file in revision/source that declares a generator must have been
regenerated. Covers the main-text figures, tables and macros, the supplementary tables and the main text's numbers of
supplementary notes, tables, figures and propositions (si_refs.tex).
A generator whose input files are absent from this package (the lite package leaves out large arrays) is reported
as not checked here, and the result is then "passed, partial" rather than a failure.
"""

from __future__ import annotations

import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
SOURCE = HERE.parent / "revision" / "source"
GENERATORS = [("cross_study", "make_assets.py", True), ("identified_set", "make_manuscript_assets.py", True),
              ("spectral_transfer", "make_scale_assets.py", True), ("recoverability", "make_assets.py", False),
              ("perturbation", "make_assets.py", False), ("perturbation_replication", "make_assets.py", False),
              ("semipaired", "make_assets.py", False), ("generality", "make_assets.py", True),
              ("predictability", "make_assets.py", True), ("synthesis", "make_assets.py", False),
              ("synthesis", "registry.py", False), ("synthesis", "si_refs.py", False)]


def main():
    declared = {}
    for f in sorted(SOURCE.glob("*.tex")):
        m = re.match(r"% Generated by extension/([^/]+)/(\S+)\.", f.read_text().splitlines()[0])
        if m:
            declared[f.name] = m.group(1)
    ok, regenerated, skipped = True, set(), {}
    with tempfile.TemporaryDirectory() as tmp:
        copy = Path(tmp) / "extension"

        def copy_small(src, dst):
            # large arrays (predictions, estimates) are only read by the generators: link them instead of copying
            if Path(src).stat().st_size > 20_000_000 and Path(src).suffix == ".npz":
                Path(dst).symlink_to(Path(src).resolve())
                return dst
            return shutil.copy2(src, dst)

        shutil.copytree(HERE, copy, ignore=shutil.ignore_patterns("__pycache__"), copy_function=copy_small)
        for name in ("revision", "release"):
            (Path(tmp) / name).symlink_to(HERE.parent / name)
        for folder, script, has_md in GENERATORS:
            if not (copy / folder / script).exists():
                skipped[folder] = f"{folder}/{script}"
                print(f"[skip] {folder}/{script}: not in this package")
                continue
            out = Path(tmp) / f"out_{folder}_{Path(script).stem}"
            out.mkdir()
            cmd = [sys.executable, script, "--out", str(out)]
            if has_md:
                cmd += ["--results-md", str(out / "RESULTS.md")]
            r = subprocess.run(cmd, cwd=copy / folder, capture_output=True, text=True)
            if r.returncode:
                m = re.search(r"FileNotFoundError: .*?'([^']+)'", r.stderr)
                if m and not Path(m.group(1).replace(str(copy), str(HERE))).exists():
                    skipped[folder] = Path(m.group(1)).name
                    print(f"[skip] {folder}/{script}: input not in this package ({skipped[folder]})")
                    continue
                print(f"[FAIL] {folder}/{script}: {r.stderr[-400:]}")
                ok = False
                continue
            for f in sorted(out.glob("*.tex")):
                same = (SOURCE / f.name).exists() and f.read_bytes() == (SOURCE / f.name).read_bytes()
                regenerated.add(f.name)
                ok &= same
                print(f"[{'ok' if same else 'FAIL'}] {folder}: {f.name}")
    not_here = sorted(f for f, folder in declared.items() if folder in skipped)
    missing = sorted(set(declared) - regenerated - set(not_here))
    print(f"[{'ok' if not missing else 'FAIL'}] every generated file in revision/source was regenerated"
          + (f"; missing: {missing}" if missing else f" ({len(declared) - len(not_here)} files)"))
    ok &= not missing
    if ok and not_here:
        print(f"passed, partial: not regenerated here ({len(not_here)} files whose inputs this package leaves out): "
              + ", ".join(not_here))
    else:
        print("passed" if ok else "FAILED")
    sys.exit(0 if ok else 1)


if __name__ == "__main__":
    main()
