#!/usr/bin/env python3
"""Write LaTeX macros, figure and table for the revised manuscript.

Every number in the new manuscript text is generated here from
results/summary.json, results/s3_sensitivity.json,
results/sensitivity_free_search.json and results/identified_summary_arrays.npz.

    python make_manuscript_assets.py --out ../../revision/source
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np

from analyze_identified import COHORTS, empirical_log_odds
from run_identified import RESULTS, load_recipients

KEYS = {"Cambridge": "Cam", "Newcastle": "New", "T-ALL": "Tall", "Colon": "Colon"}
EXAMPLE = 95        # first colon donor in the fixed recipient order
CLIP = 8.0          # log-odds display limit for panel A


def pct(x, digits=1):
    return f"{100 * x:.{digits}f}"


def count(n):
    return f"{n:,}".replace(",", "{,}")


def macros(summary, s3s, free):
    s3 = summary["S3_reversal_direction"]
    ident = summary["S1_S2_S4_identified_set"]
    lines = ["% Generated by extension/identified_set/make_manuscript_assets.py. Do not edit."]

    def add(name, value):
        lines.append(f"\\newcommand{{\\{name}}}{{{value}}}")

    total_q = sum(ident[c]["recipients"] * 81 for c in COHORTS)
    total_unid = sum(ident[c]["S1_direction_unidentified_count"] for c in COHORTS)
    add("IdRecipientQueries", count(total_q))
    add("IdUnidentifiedCount", count(total_unid))
    add("IdUnidentifiedPct", pct(total_unid / total_q))
    cognate_n = sum(ident[c]["recipients"] * 9 for c in COHORTS)
    cognate_unid = sum(ident[c]["S1_cognate_fraction"] * ident[c]["recipients"] * 9 for c in COHORTS)
    add("IdUnidCognatePct", pct(cognate_unid / cognate_n))
    add("IdCertifiedEndpoints", count(summary["certification"]["star_endpoints_certified"]))
    add("IdCertMaxDiff", f"{summary['certification']['max_search_vs_certified_difference']:.1e}"
        .replace("e-", r"\times10^{-").replace("e+", r"\times10^{") + "}")
    add("IdScalingFailures", count(summary["certification"]["scaling_failures_during_search"]))
    for cohort in COHORTS:
        k, a, b, s = KEYS[cohort], ident[cohort], s3[cohort], s3s[cohort]
        add(f"IdUnid{k}", pct(a["S1_direction_unidentified_fraction"]))
        add(f"IdUnidCognate{k}", pct(a["S1_cognate_fraction"]))
        add(f"IdWidth{k}", f"{a['S2_log_odds_width_median']:.1f}")
        add(f"IdWidthLo{k}", f"{a['S2_log_odds_width_quartiles'][0]:.1f}")
        add(f"IdWidthHi{k}", f"{a['S2_log_odds_width_quartiles'][1]:.1f}")
        add(f"IdWidthMin{k}", f"{a['S2_log_odds_width_min']:.1f}")
        add(f"IdRisk{k}", f"{a['S2_minimax_deviance_lower_bound_mean']:.3f}")
        add(f"IdHeldFreq{k}", f"{a['heldout_mean_deviance_frequency_only']:.4f}")
        add(f"IdHeldFull{k}", f"{a['heldout_mean_deviance_full_patterns']:.4f}")
        add(f"IdSpearRisk{k}", f"{a['S4_mean_within_spearman_bound_vs_gain']:.2f}")
        add(f"IdSpearProd{k}", f"{a['S4_mean_within_spearman_frequency_product_vs_gain']:.2f}")
        add(f"IdRev{k}", count(b["reversals"]))
        add(f"IdRevPct{k}", pct(b["reversals"] / b["recipient_queries"]))
        add(f"IdRevTies{k}", count(b["reversals_with_tied_heldout_direction"]))
        add(f"IdAgree{k}", pct(b["agreement_with_full_patterns"]))
        add(f"IdAgreeN{k}", f"{count(b['agreeing'])}/{count(b['usable_reversals'])}")
        add(f"IdAgreeLo{k}", pct(b["bootstrap_95"][0]))
        add(f"IdAgreeHi{k}", pct(b["bootstrap_95"][1]))
        add(f"IdAgreeAdjLo{k}", pct(b["bootstrap_familywise"][0]))
        add(f"IdAgreeAdjHi{k}", pct(b["bootstrap_familywise"][1]))
        add(f"IdNonempty{k}", pct(s["nonempty_agreement"]))
        add(f"IdNonemptyAdjLo{k}", pct(s["nonempty_bootstrap_familywise"][0]))
        add(f"IdRevGainShare{k}", pct(s["share_of_total_gain_from_reversals"]))
    retro = COHORTS[:3]
    agree = [s3[c]["agreement_with_full_patterns"] for c in retro]
    reversal_pct = [s3[c]["reversals"] / s3[c]["recipient_queries"] for c in COHORTS]
    add("IdAgreeRetroMin", f"{100 * min(agree):.0f}")
    add("IdAgreeRetroMax", f"{100 * max(agree):.0f}")
    add("IdRevPctMin", f"{100 * min(reversal_pct):.0f}")
    add("IdRevPctMax", f"{100 * max(reversal_pct):.0f}")
    add("IdAgreeColonRound", f"{100 * s3['Colon']['agreement_with_full_patterns']:.0f}")
    add("IdFreeExtLowMedian", f"{free['lower_endpoint_extension_log_odds']['median']:.2f}")
    add("IdFreeExtHighMedian", f"{free['upper_endpoint_extension_log_odds']['median']:.2f}")
    add("IdFreeExtMax", f"{max(free['lower_endpoint_extension_log_odds']['max'], free['upper_endpoint_extension_log_odds']['max']):.2f}")
    add("IdFreeStarWidth", f"{free['star_width_median']:.1f}")
    add("IdFreeWidth", f"{free['free_width_median']:.1f}")
    return "\n".join(lines) + "\n"


def figure(summary, arrays, data):
    p = EXAMPLE
    order = np.argsort(arrays["theta_freq"][p], kind="stable")
    empirical = empirical_log_odds(data["truth"])[p]
    bars, rows_freq, rows_full, rows_emp = [], [], [], []
    for rank, q in enumerate(order, start=1):
        low, high = arrays["theta_low"][p, q], arrays["theta_high"][p, q]
        lo, hi = max(low, -CLIP), min(high, CLIP)
        tip_lo = "{Stealth[length=2.4pt,width=2.4pt]}" if low < -CLIP else ""
        tip_hi = "{Stealth[length=2.4pt,width=2.4pt]}" if high > CLIP else ""
        arrow = f"{tip_lo}-{tip_hi}" if (tip_lo or tip_hi) else "-"
        bars.append(f"\\draw[{arrow},interval] (axis cs:{rank},{lo:.4f}) -- (axis cs:{rank},{hi:.4f});")
        rows_freq.append(f"({rank},{arrays['theta_freq'][p, q]:.4f})")
        rows_full.append(f"({rank},{arrays['theta_full'][p, q]:.4f})")
        rows_emp.append(f"({rank},{np.clip(empirical[q], -CLIP, CLIP):.4f})")
    s3 = summary["S3_reversal_direction"]
    agree_rows = []
    for y, cohort in zip((4, 3, 2, 1), COHORTS):
        b = s3[cohort]
        x = 100 * b["agreement_with_full_patterns"]
        lo, hi = 100 * b["bootstrap_95"][0], 100 * b["bootstrap_95"][1]
        agree_rows.append(f"({x:.3f},{y}) += ({hi - x:.3f},0) -= ({x - lo:.3f},0)")
    labels = ",".join(COHORTS[::-1])
    chunk = lambda items: "\n ".join(" ".join(items[i:i + 4]) for i in range(0, len(items), 4))
    return rf"""% Generated by extension/identified_set/make_manuscript_assets.py. Do not edit.
\definecolor{{freqonly}}{{HTML}}{{5D6670}}
\definecolor{{fullpat}}{{HTML}}{{A64442}}
\definecolor{{agreecol}}{{HTML}}{{217D91}}
\tikzset{{interval/.style={{line width=1.2pt,black!20}}}}
\begin{{tikzpicture}}[font=\sffamily]
\begin{{axis}}[name=left,
 width=.62\textwidth,height=5.4cm,
 xmin=-1,xmax=83,ymin=-{CLIP + 0.5:.1f},ymax={CLIP + 0.5:.1f},
 xtick={{1,27,54,81}},ytick={{-8,-4,0,4,8}},
 xlabel={{Query, ordered by frequency-only log odds}},
 ylabel={{Log odds ratio}},
 title={{\textbf{{a}}\enspace Identified intervals, first colon donor}},
 title style={{font=\sffamily\small,at={{(0,1)}},anchor=south west,yshift=13pt}},
 axis x line*=bottom,axis y line*=left,tick align=outside,
 axis line style={{gray!55}},tick label style={{font=\sffamily\small}},label style={{font=\sffamily\small}},set layers,
 legend style={{draw=none,at={{(0,1.0)}},anchor=south west,font=\sffamily\scriptsize,
   legend columns=4,column sep=5pt}},legend cell align=left]
\addlegendimage{{interval}}
\addlegendentry{{Certified interval}}
\addplot[only marks,mark=o,mark size=1.45pt,color=freqonly,line width=.5pt] coordinates {{
 {chunk(rows_freq)}}};
\addlegendentry{{Individual frequencies}}
\addplot[only marks,mark=*,mark size=1.2pt,color=fullpat] coordinates {{
 {chunk(rows_full)}}};
\addlegendentry{{Both assay patterns}}
\addplot[only marks,mark=x,mark size=1.5pt,color=black!60,line width=.45pt] coordinates {{
 {chunk(rows_emp)}}};
\addlegendentry{{Held-out cells}}
\begin{{pgfonlayer}}{{axis background}}
\draw[black!40] (axis cs:-1,0) -- (axis cs:83,0);
{chr(10).join(bars)}
\end{{pgfonlayer}}
\end{{axis}}
\begin{{axis}}[at={{(left.east)}},anchor=west,xshift=1.75cm,
 width=.30\textwidth,height=5.4cm,
 xmin=40,xmax=100,ymin=.5,ymax=4.5,
 xtick={{50,75,100}},ytick={{1,2,3,4}},yticklabels={{{labels}}},
 xlabel={{Held-out agreement (\%)}},
 title={{\textbf{{b}}\enspace Reversed directions}},
 title style={{font=\sffamily\small,at={{(0,1)}},anchor=south west,xshift=-1.55cm,yshift=13pt}},
 axis x line*=bottom,axis y line*=left,tick align=outside,y tick style={{draw=none}},
 xmajorgrids=true,grid style={{gray!18}},axis line style={{gray!55}},
 tick label style={{font=\sffamily\small}},label style={{font=\sffamily\small}},
 every axis plot/.append style={{only marks,mark size=2.2pt,line width=.8pt}},
 error bars/x dir=both,error bars/x explicit,
 error bars/error mark options={{rotate=90,mark size=2.6pt,line width=.8pt}}]
\draw[dashed,black!45] (axis cs:50,.5) -- (axis cs:50,4.5);
\draw[dashed,black!30] (axis cs:40,1.5) -- (axis cs:100,1.5);
\addplot[color=agreecol,mark=*] coordinates {{
 {" ".join(agree_rows)}}};
\end{{axis}}
\end{{tikzpicture}}
"""


def table(summary, s3s):
    ident, s3 = summary["S1_S2_S4_identified_set"], summary["S3_reversal_direction"]

    def row(label, fn):
        return label + " & " + " & ".join(fn(c) for c in COHORTS) + r"\\"

    rows = [
        row("People", lambda c: str(ident[c]["recipients"])),
        row("Direction unidentified, all queries (\\%)", lambda c: pct(ident[c]["S1_direction_unidentified_fraction"])),
        row("Direction unidentified, same marker (\\%)", lambda c: pct(ident[c]["S1_cognate_fraction"])),
        row("Median log-odds width (IQR)", lambda c: f"{ident[c]['S2_log_odds_width_median']:.1f} ({ident[c]['S2_log_odds_width_quartiles'][0]:.1f}--{ident[c]['S2_log_odds_width_quartiles'][1]:.1f})"),
        row("Minimax deviance bound, mean", lambda c: f"{ident[c]['S2_minimax_deviance_lower_bound_mean']:.3f}"),
        row("Reversals, n (\\% of queries)", lambda c: f"{count(s3[c]['reversals'])} ({pct(s3[c]['reversals'] / s3[c]['recipient_queries'])})"),
        row("Held-out agreement (\\%)", lambda c: pct(s3[c]["agreement_with_full_patterns"])),
        row("\\quad nominal 95\\% interval", lambda c: f"{pct(s3[c]['bootstrap_95'][0])}--{pct(s3[c]['bootstrap_95'][1])}"),
        row("\\quad Bonferroni interval", lambda c: f"{pct(s3[c]['bootstrap_familywise'][0])}--{pct(s3[c]['bootstrap_familywise'][1])}"),
        row("\\quad no empty held-out cell$^\\dagger$", lambda c: pct(s3s[c]["nonempty_agreement"])),
        row("Share of net gain in reversals (\\%)$^\\dagger$", lambda c: pct(s3s[c]["share_of_total_gain_from_reversals"])),
        row("Spearman, bound vs.\\ pair gain$^\\ddagger$", lambda c: f"{ident[c]['S4_mean_within_spearman_bound_vs_gain']:.2f}"),
        row("Spearman, $m(1-m)n(1-n)$ vs.\\ pair gain$^\\ddagger$", lambda c: f"{ident[c]['S4_mean_within_spearman_frequency_product_vs_gain']:.2f}"),
    ]
    return ("% Generated by extension/identified_set/make_manuscript_assets.py. Do not edit.\n"
            "\\begin{tabularx}{\\textwidth}{@{}Yrrrr@{}}\n\\toprule\n"
            "Summary & Cambridge & Newcastle & T-ALL & Colon\\\\\n\\midrule\n"
            + "\n".join(rows) + "\n\\bottomrule\n\\end{tabularx}\n")


def markdown(summary, s3s, free):
    """Plain-text results table for results/RESULTS.md (same numbers as the LaTeX table)."""
    ident, s3 = summary["S1_S2_S4_identified_set"], summary["S3_reversal_direction"]
    head = "| Summary | " + " | ".join(COHORTS) + " |\n|---|" + "---:|" * len(COHORTS) + "\n"

    def row(label, fn):
        return f"| {label} | " + " | ".join(fn(c) for c in COHORTS) + " |\n"

    body = "".join([
        row("People", lambda c: str(ident[c]["recipients"])),
        row("S1 direction unidentified, all queries (%)", lambda c: pct(ident[c]["S1_direction_unidentified_fraction"])),
        row("S1 direction unidentified, same marker (%)", lambda c: pct(ident[c]["S1_cognate_fraction"])),
        row("S2 median certified log-odds width (IQR)", lambda c: f"{ident[c]['S2_log_odds_width_median']:.1f} ({ident[c]['S2_log_odds_width_quartiles'][0]:.1f}-{ident[c]['S2_log_odds_width_quartiles'][1]:.1f})"),
        row("S2 per-query minimax deviance bound, mean", lambda c: f"{ident[c]['S2_minimax_deviance_lower_bound_mean']:.3f}"),
        row("S3 reversals, n (% of queries)", lambda c: f"{s3[c]['reversals']:,} ({pct(s3[c]['reversals'] / s3[c]['recipient_queries'])})"),
        row("S3 held-out agreement with full patterns (%)", lambda c: pct(s3[c]["agreement_with_full_patterns"])),
        row("S3 nominal 95% interval", lambda c: f"{pct(s3[c]['bootstrap_95'][0])}-{pct(s3[c]['bootstrap_95'][1])}"),
        row("S3 Bonferroni interval (4 cohorts)", lambda c: f"{pct(s3[c]['bootstrap_familywise'][0])}-{pct(s3[c]['bootstrap_familywise'][1])}"),
        row("S3 agreement, no empty held-out cell (%) [added]", lambda c: pct(s3s[c]["nonempty_agreement"])),
        row("Share of net held-out gain in reversals (%) [added]", lambda c: pct(s3s[c]["share_of_total_gain_from_reversals"])),
        row("S4 Spearman, bound vs pair gain (descriptive)", lambda c: f"{ident[c]['S4_mean_within_spearman_bound_vs_gain']:.2f}"),
        row("S4 Spearman, m(1-m)n(1-n) vs pair gain", lambda c: f"{ident[c]['S4_mean_within_spearman_frequency_product_vs_gain']:.2f}"),
    ])
    cert = summary["certification"]
    return (
        "# Results (generated by make_manuscript_assets.py; do not edit)\n\n" + head + body +
        f"\nCertified star endpoints: {cert['star_endpoints_certified']:,}; maximum search-versus-certified "
        f"difference {cert['max_search_vs_certified_difference']:.1e}; scaling failures during search: "
        f"{cert['scaling_failures_during_search']}.\n\n"
        "Unrestricted local search, first colon donor, 81 queries: endpoints moved outward by median "
        f"{free['lower_endpoint_extension_log_odds']['median']:.2f} (lower) and "
        f"{free['upper_endpoint_extension_log_odds']['median']:.2f} (upper) log-odds units; median width "
        f"{free['star_width_median']:.1f} -> {free['free_width_median']:.1f}.\n\n"
        "[added] = not prespecified in PLAN.md; added after the primary S3 result.\n")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", type=Path, required=True)
    parser.add_argument("--results-md", type=Path, default=RESULTS / "RESULTS.md")
    args = parser.parse_args()
    summary = json.loads((RESULTS / "summary.json").read_text())
    s3s = json.loads((RESULTS / "s3_sensitivity.json").read_text())
    free = json.loads((RESULTS / "sensitivity_free_search.json").read_text())
    arrays = np.load(RESULTS / "identified_summary_arrays.npz")
    data = load_recipients()
    args.out.mkdir(parents=True, exist_ok=True)
    (args.out / "identified_macros.tex").write_text(macros(summary, s3s, free))
    (args.out / "identified_figure.tex").write_text(figure(summary, arrays, data))
    (args.out / "identified_table.tex").write_text(table(summary, s3s))
    args.results_md.write_text(markdown(summary, s3s, free))
    print("wrote", *(str(args.out / n) for n in ("identified_macros.tex", "identified_figure.tex",
                                                  "identified_table.tex")), args.results_md)


if __name__ == "__main__":
    main()
