#!/usr/bin/env python3
"""LaTeX macros, figure and table for the second-order transfer results.

Reads results/binary_released.json, results/scale_summary.json,
results/d1_lodo.json, results/d2_hc_to_uc.json, results/d3_pairing_free.json,
results/d3_permutation_control.json and results/d3_learning_curve.json.

    python make_scale_assets.py --out ../../revision/source
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
R = HERE / "results"
COHORTS = ("Cambridge", "Newcastle", "T-ALL", "Colon")
KEY = {"Cambridge": "Cam", "Newcastle": "New", "T-ALL": "Tall", "Colon": "Colon"}
ARM_LABELS = [
    ("independence", "Independence"),
    ("variances_only", "Closed form, variances only"),
    ("reference_corr", "Reference correlation"),
    ("reference_cov", "Reference covariance"),
    ("regression", "Reference regression"),
    ("cell_coupling", "Exact coupling of cells"),
    ("closed_form", "Closed form"),
    ("pf_means_closed_form", "Pairing-free, means"),
    ("pf_lowrank_closed_form", "Pairing-free, rank 8"),
    ("oracle", "Own paired half (not permitted)"),
]


FIGURE_LABELS = {
    "independence": "Independence", "variances_only": "Variances only",
    "reference_corr": "Reference correlation", "reference_cov": "Reference covariance",
    "regression": "Reference regression", "cell_coupling": "Cell coupling",
    "closed_form": "Closed form", "pf_means_closed_form": "No pairs: means",
    "pf_lowrank_closed_form": "No pairs: rank 8", "oracle": "Own paired half",
}


def load(name):
    return json.loads((R / name).read_text())


def num(x, d):
    text = f"{abs(x):.{d}f}"
    return f"\\ensuremath{{-}}{text}" if x < 0 and float(text) != 0 else text


def pct(x, d=1):
    return num(100 * x, d)


def big(x):
    text = f"{abs(x):,.0f}".replace(",", "{,}")
    return f"\\ensuremath{{-}}{text}" if x < 0 else text


def macros(binary, scale, perm, curve, d1, d3):
    lines = ["% Generated by extension/spectral_transfer/make_scale_assets.py. Do not edit."]

    def add(name, value):
        lines.append(f"\\newcommand{{\\{name}}}{{{value}}}")

    for c in COHORTS:
        e = binary["cohorts"][c]
        k = KEY[c]
        add(f"SoPair{k}", pct(e["pairwise_exact_gain_retained"]))
        add(f"SoPairLo{k}", pct(e["pairwise_exact_gain_retained_95"][0]))
        add(f"SoPairHi{k}", pct(e["pairwise_exact_gain_retained_95"][1]))
        add(f"SoClosed{k}", pct(e["closed_form_gain_retained"]))
        add(f"SoClosedLo{k}", pct(e["closed_form_gain_retained_95"][0]))
        add(f"SoClosedHi{k}", pct(e["closed_form_gain_retained_95"][1]))
        add(f"SoFirst{k}", pct(e["first_order_gain_retained"], 0))
    add("SoClipped", str(binary["clipped_cells"]["closed_form"]))
    pair = [binary["cohorts"][c]["pairwise_exact_gain_retained"] for c in COHORTS]
    add("SoPairMin", f"{100 * min(pair):.0f}")
    add("SoPairMax", f"{100 * max(pair):.0f}")
    closed = [binary["cohorts"][c]["closed_form_gain_retained"] for c in COHORTS]
    add("SoClosedMin", f"{100 * min(closed):.0f}")
    add("SoClosedMax", f"{100 * max(closed):.0f}")

    s1 = scale["D1_leave_one_donor_out"]
    add("ScDonors", str(len(s1["donors"])))
    add("ScGenes", str(s1["genes"]))
    add("ScProteins", str(s1["proteins"]))
    add("ScPairs", f"{s1['genes'] * s1['proteins']:,}".replace(",", "{,}"))
    mean = s1["mean"]
    names = {"independence": "Indep", "variances_only": "Var", "reference_corr": "RefCorr",
             "reference_cov": "RefCov", "regression": "Reg", "cell_coupling": "Cells",
             "closed_form": "Closed", "first_order": "First", "oracle": "Oracle",
             "pf_means_closed_form": "PfMeans", "pf_lowrank_closed_form": "PfLow",
             "pf_means_regression": "PfMeansReg", "pf_lowrank_regression": "PfLowReg"}
    for arm, short in names.items():
        if arm in mean["cov_rel_error"]:
            err = mean["cov_rel_error"][arm]
            add(f"ScErr{short}", num(err, 3) if abs(err) < 100 else big(err))
            add(f"ScCorr{short}", num(mean["cov_corr"][arm], 3))
            r2 = mean["r2"][arm]
            add(f"ScRsq{short}", num(r2, 3) if abs(r2) < 100 else big(r2))
    for comp, short in (("variances_only", "Var"), ("regression", "Reg"), ("reference_corr", "RefCorr"),
                        ("reference_cov", "RefCov")):
        c = s1["primary_contrasts"][comp]
        add(f"ScDiff{short}", num(c["mean_difference"], 3))
        add(f"ScDiffLo{short}", num(c["bootstrap_familywise"][0], 3))
        add(f"ScDiffHi{short}", num(c["bootstrap_familywise"][1], 3))
        add(f"ScWins{short}", f"{c['donors_favouring_target']}/{len(s1['donors'])}")
    cells = s1["cells_vs_closed_form"]["closed_form"]
    add("ScDiffCells", num(cells["mean_difference"], 3))
    add("ScDiffLoCells", num(cells["bootstrap_95"][0], 3))
    add("ScDiffHiCells", num(cells["bootstrap_95"][1], 3))
    pf = s1["pairing_free_vs_paired"]["pf_lowrank_closed_form"]
    for comp, short in (("closed_form", "Closed"), ("regression", "Reg"), ("variances_only", "Var"),
                        ("independence", "Indep")):
        add(f"PfDiff{short}", num(pf[comp]["mean_difference"], 3))
        add(f"PfDiffLo{short}", num(pf[comp]["bootstrap_familywise"][0], 3))
        add(f"PfDiffHi{short}", num(pf[comp]["bootstrap_familywise"][1], 3))
    gap_closed = mean["cov_rel_error"]["independence"] - mean["cov_rel_error"]["closed_form"]
    gap_pf = mean["cov_rel_error"]["independence"] - mean["cov_rel_error"]["pf_lowrank_closed_form"]
    add("PfShareOfPaired", pct(gap_pf / gap_closed, 0))
    gap_means = mean["cov_rel_error"]["independence"] - mean["cov_rel_error"]["pf_means_closed_form"]
    add("PfShareOfPairedMeans", pct(gap_means / gap_closed, 0))
    s2 = scale["D2_healthy_to_colitis"]
    for arm, short in names.items():
        if arm in s2["mean"]["cov_rel_error"]:
            e2, r2b = s2["mean"]["cov_rel_error"][arm], s2["mean"]["r2"][arm]
            add(f"HcErr{short}", num(e2, 3) if abs(e2) < 100 else big(e2))
            add(f"HcRsq{short}", num(r2b, 3) if abs(r2b) < 100 else big(r2b))
    for comp, short in (("variances_only", "Var"), ("regression", "Reg")):
        c = s2["primary_contrasts"][comp]
        add(f"HcDiff{short}", num(c["mean_difference"], 3))
        add(f"HcDiffLo{short}", num(c["bootstrap_familywise"][0], 3))
        add(f"HcDiffHi{short}", num(c["bootstrap_familywise"][1], 3))
    add("HcRecipients", str(len(s2["donors"])))
    obs = np.array([v["closed_form"]["observed"] for v in perm.values()])
    null = np.array([v["closed_form"]["null_mean"] for v in perm.values()])
    add("PcObs", num(obs.mean(), 3))
    add("PcNull", num(null.mean(), 3))
    add("PcPerms", "200")
    add("PcP", "1/201")
    add("PcDonors", str(len(perm)))
    sizes = ("5", "10", "15")
    for size in sizes:
        add(f"LcErr{['Five', 'Ten', 'Fifteen'][sizes.index(size)]}", num(np.mean([np.mean(v[size]) for v in curve.values()]), 3))
    add("LcErrAll", num(np.mean([np.mean([x for k, x in v.items() if k not in sizes][0]) for v in curve.values()]), 3))
    edge = sum(d["ridge_scale"] == 1e-3 for d in d3["donors"].values())
    add("PfRidgeEdge", f"{edge} of {len(d3['donors'])}")
    add("PfSamples", f"{min(d['training_samples'] for d in d3['donors'].values())}--{max(d['training_samples'] for d in d3['donors'].values())}")
    return "\n".join(lines) + "\n"


RIGOR = HERE.parent / "cross_study" / "results" / "colon_rigor.json"
RIGOR_KEY = {"pf_means_closed_form": "pf_means", "pf_lowrank_closed_form": "pf_moment"}


def figure(binary, d1, d3, perm):
    """Pairing-free rows show the corrected re-analysis (cross_study/colon_pf_rigor.py)."""
    donors = list(d1["donors"])
    rigor = json.loads(RIGOR.read_text())
    rows = []
    for y, (arm, label) in enumerate(reversed(ARM_LABELS), start=1):
        if arm in RIGOR_KEY:
            values = [rigor[d][RIGOR_KEY[arm]]["E"] for d in donors]
        else:
            values = [d1["donors"][d]["arms"][arm]["cov_rel_error"] for d in donors]
        rows.append((y, arm, FIGURE_LABELS[arm], values))
    ticks = ",".join(str(y) for y, *_ in rows)
    labels = ",".join("{" + label + "}" for _, _, label, _ in rows)
    points = "\n ".join(" ".join(f"({min(v, 1.95):.4f},{y + 0.18 * (k / (len(vals) - 1) - 0.5):.3f})" for k, v in enumerate(vals))
                        for y, _, _, vals in rows)
    means = " ".join(f"({min(np.mean(vals), 1.95):.4f},{y})" for y, _, _, vals in rows)
    clipped = [f"\\node[font=\\tiny,anchor=west,black!55] at (axis cs:1.96,{y}) {{{np.mean(vals):.1f}}};"
               for y, _, _, vals in rows if np.mean(vals) > 1.95]
    retained = []
    for c_index, c in enumerate(COHORTS):
        e = binary["cohorts"][c]
        yb = 4 - c_index
        for arm, dy in (("pairwise_exact", 0.16), ("closed_form", -0.16)):
            v = 100 * e[f"{arm}_gain_retained"]
            lo, hi = (100 * t for t in e[f"{arm}_gain_retained_95"])
            retained.append((arm, f"({v:.3f},{yb + dy:.2f}) += ({hi - v:.3f},0) -= ({v - lo:.3f},0)"))
    pair_rows = " ".join(r for a, r in retained if a == "pairwise_exact")
    closed_rows = " ".join(r for a, r in retained if a == "closed_form")
    return rf"""% Generated by extension/spectral_transfer/make_scale_assets.py. Do not edit.
\definecolor{{pairexact}}{{HTML}}{{217D91}}
\definecolor{{closedcol}}{{HTML}}{{A64442}}
\definecolor{{donorcol}}{{HTML}}{{5D6670}}
\begin{{tikzpicture}}[font=\sffamily]
\begin{{axis}}[name=left,
 width=.40\textwidth,height=6.2cm,
 xmin=0,xmax=100,ymin=.5,ymax=4.5,
 xtick={{0,25,50,75,100}},ytick={{1,2,3,4}},yticklabels={{Colon,T-ALL,Newcastle,Cambridge}},
 xlabel={{Full-pattern gain retained (\%)}},
 title={{\textbf{{c}}\enspace Nine-marker binary panel}},
 title style={{font=\sffamily\small,at={{(0,1)}},anchor=south west,xshift=-1.6cm,yshift=11pt}},
 axis x line*=bottom,axis y line*=left,tick align=outside,y tick style={{draw=none}},
 xmajorgrids=true,grid style={{gray!18}},axis line style={{gray!55}},
 tick label style={{font=\sffamily\small}},label style={{font=\sffamily\small}},
 legend style={{draw=none,at={{(0,1.0)}},anchor=south west,font=\sffamily\scriptsize,legend columns=2,column sep=4pt}},
 every axis plot/.append style={{only marks,mark size=2pt,line width=.75pt}},
 error bars/x dir=both,error bars/x explicit,
 error bars/error mark options={{rotate=90,mark size=2.2pt,line width=.75pt}}]
\draw[dashed,black!30] (axis cs:0,1.5) -- (axis cs:100,1.5);
\addplot[color=pairexact,mark=*] coordinates {{ {pair_rows} }};
\addlegendentry{{Pairwise, exact}}
\addplot[color=closedcol,mark=square*] coordinates {{ {closed_rows} }};
\addlegendentry{{Closed form}}
\end{{axis}}
\begin{{axis}}[at={{(left.east)}},anchor=west,xshift=3.6cm,
 width=.40\textwidth,height=6.2cm,
 xmin=0,xmax=2.1,ymin=.4,ymax={len(rows) + .6},
 xtick={{0,.5,1,1.5,2}},ytick={{{ticks}}},yticklabels={{{labels}}},
 xlabel={{Cross-covariance error (relative)}},
 title={{\textbf{{d}}\enspace {d1['genes']} genes $\times$ {d1['proteins']} proteins, {len(donors)} colon donors}},
 title style={{font=\sffamily\small,at={{(0,1)}},anchor=south west,xshift=-3.3cm,yshift=11pt}},
 axis x line*=bottom,axis y line*=left,tick align=outside,y tick style={{draw=none}},
 xmajorgrids=true,grid style={{gray!18}},axis line style={{gray!55}},
 tick label style={{font=\sffamily\scriptsize}},label style={{font=\sffamily\small}},clip=false]
\draw[dashed,black!45] (axis cs:1,.4) -- (axis cs:1,{len(rows) + .6});
\draw[black!25] (axis cs:0,1.5) -- (axis cs:2.1,1.5);
\draw[black!25] (axis cs:0,3.5) -- (axis cs:2.1,3.5);
\addplot[only marks,mark=*,mark size=.9pt,color=donorcol!60] coordinates {{
 {points}}};
\addplot[only marks,mark=|,mark size=4pt,line width=1.2pt,color=black] coordinates {{ {means} }};
{chr(10).join(clipped)}
\end{{axis}}
\end{{tikzpicture}}
"""


def table(scale, d1, d2, d3):
    s1, s2 = scale["D1_leave_one_donor_out"], scale["D2_healthy_to_colitis"]

    def cell(summary, arm, metric, digits=3):
        value = summary["mean"][metric].get(arm)
        if value is None:
            return "--"
        text = f"{abs(value):.{digits}f}" if abs(value) < 100 else f"{abs(value):,.0f}".replace(",", "{,}")
        return f"$-{text}$" if value < 0 else text

    lines = []
    first = {"pf_means_closed_form": "Pairing-free, means (first version)",
             "pf_lowrank_closed_form": "Pairing-free, rank 8 (first version)"}
    for arm, label in ARM_LABELS + [("first_order", "First-order formula"),
                                    ("pf_means_regression", "Pairing-free means, regression (first version)"),
                                    ("pf_lowrank_regression", "Pairing-free rank 8, regression (first version)")]:
        lines.append(f"{first.get(arm, label)} & {cell(s1, arm, 'cov_rel_error')} & {cell(s1, arm, 'cov_corr')} & "
                     f"{cell(s1, arm, 'r2')} & {cell(s2, arm, 'cov_rel_error')} & {cell(s2, arm, 'r2')}\\\\")
    rigor = json.loads(RIGOR.read_text())
    for key, label in (("pf_means", "Pairing-free, means (corrected)"),
                       ("pf_moment", "Pairing-free, rank 8 (corrected)")):
        value = np.mean([rigor[d][key]["E"] for d in d1["donors"]])
        lines.append(f"{label} & {value:.3f} & -- & -- & -- & --\\\\")
    return ("% Generated by extension/spectral_transfer/make_scale_assets.py. Do not edit.\n"
            "\\begin{tabularx}{\\textwidth}{@{}Yrrrrr@{}}\n\\toprule\n"
            "& \\multicolumn{3}{c}{Leave one donor out ($n=12$)} & \\multicolumn{2}{c}{Healthy to colitis ($n=8$)}\\\\\n"
            "\\cmidrule(lr){2-4}\\cmidrule(l){5-6}\n"
            "Prediction & Error & Correlation & $R^2$ & Error & $R^2$\\\\\n\\midrule\n"
            + "\n".join(lines) + "\n\\bottomrule\n\\end{tabularx}\n")


def markdown(binary, scale, perm, curve):
    s1, s2 = scale["D1_leave_one_donor_out"], scale["D2_healthy_to_colitis"]
    lines = ["# Results (generated by make_scale_assets.py; do not edit)", "",
             "## Nine-marker binary panel: share of the full-pattern gain retained", "",
             "| Cohort | Pairwise, exact | 95% interval | Closed form | 95% interval | First-order |",
             "|---|---:|---:|---:|---:|---:|"]
    for c in COHORTS:
        e = binary["cohorts"][c]
        lines.append(f"| {c} | {pct(e['pairwise_exact_gain_retained'])}% | "
                     f"{pct(e['pairwise_exact_gain_retained_95'][0])}-{pct(e['pairwise_exact_gain_retained_95'][1])}% | "
                     f"{pct(e['closed_form_gain_retained'])}% | "
                     f"{pct(e['closed_form_gain_retained_95'][0])}-{pct(e['closed_form_gain_retained_95'][1])}% | "
                     f"{pct(e['first_order_gain_retained'], 0)}% |")
    lines += ["", f"## Colon panel ({s1['genes']} genes x {s1['proteins']} proteins)", "",
              "Mean over recipients; error = relative Frobenius error of the predicted cross-covariance "
              "against the held-out paired cross-covariance (lower is better).", "",
              "| Prediction | D1 error | D1 correlation | D1 R^2 | D2 error | D2 R^2 |", "|---|---:|---:|---:|---:|---:|"]
    for arm, label in ARM_LABELS:
        def get(summary, metric):
            value = summary["mean"][metric].get(arm)
            return "-" if value is None else (f"{value:.3f}" if abs(value) < 100 else f"{value:.3g}")
        lines.append(f"| {label} | {get(s1, 'cov_rel_error')} | {get(s1, 'cov_corr')} | {get(s1, 'r2')} | "
                     f"{get(s2, 'cov_rel_error')} | {get(s2, 'r2')} |")
    lines += ["", "Primary contrasts, closed form minus comparator (Bonferroni over four):", ""]
    for design, summary in (("D1", s1), ("D2", s2)):
        for comp, c in summary["primary_contrasts"].items():
            lines.append(f"- {design} vs {comp}: {c['mean_difference']:.4f} "
                         f"({c['bootstrap_familywise'][0]:.4f} to {c['bootstrap_familywise'][1]:.4f}); "
                         f"closed form better in {c['donors_favouring_target']}/{len(summary['donors'])}")
    obs = np.mean([v["closed_form"]["observed"] for v in perm.values()])
    null = np.mean([v["closed_form"]["null_mean"] for v in perm.values()])
    lines += ["", f"Pairing-free negative control (primary estimator): observed mean error {obs:.3f}, "
              f"derangement mean {null:.3f}; p = 1/201 for each of {len(perm)} donors.", "",
              "Learning curve (mean error): " + ", ".join(
                  f"{size} biopsies {np.mean([np.mean(v[size]) for v in curve.values()]):.3f}" for size in ("5", "10", "15")),
              "", "D2 was not run for the pairing-free arms. All analyses are retrospective; see PLAN.md.",
              "", "The pairing-free rows above are the first version. A corrected re-analysis "
              "(../cross_study/colon_pf_rigor.py: disjoint cell halves, donor-grouped folds, extended grids, "
              "converged fits, donor-aware permutations) gives mean error "
              + ", ".join(f"{k} {np.mean([v[k]['E'] for v in json.loads(RIGOR.read_text()).values()]):.3f}"
                          for k in ("pf_means", "pf_moment"))
              + "; Figure 3b of the revision shows the corrected values."]
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", type=Path, required=True)
    parser.add_argument("--results-md", type=Path, default=R / "RESULTS.md")
    args = parser.parse_args()
    binary, scale = load("binary_released.json"), load("scale_summary.json")
    d1, d2, d3 = load("d1_lodo.json"), load("d2_hc_to_uc.json"), load("d3_pairing_free.json")
    perm, curve = load("d3_permutation_control.json"), load("d3_learning_curve.json")
    args.out.mkdir(parents=True, exist_ok=True)
    (args.out / "scale_macros.tex").write_text(macros(binary, scale, perm, curve, d1, d3))
    (args.out / "scale_figure.tex").write_text(figure(binary, d1, d3, perm))
    (args.out / "scale_table.tex").write_text(table(scale, d1, d2, d3))
    args.results_md.write_text(markdown(binary, scale, perm, curve))
    print("wrote scale_macros.tex, scale_figure.tex, scale_table.tex to", args.out)


if __name__ == "__main__":
    main()
