#!/usr/bin/env python3
"""Manuscript assets that draw on several studies: synth_macros.tex, five figures of the main text and the tables of
the Supplementary Notes on the bone-marrow and validation tests and on the analyses added in revision.

    python make_assets.py --out ../../revision/source

* atlas_figure.tex (Fig. 2): the validation test (../validation), the other methods given the same atlas, the
  biological readout with reference regression, its differences per donor and the named relationships
  (../second_review).
* transfer_figure.tex (Fig. 3): the bone-marrow test (../deployment), its reanalysis with the paired cells centred by
  contrasts, the fly connectome with unpaired neurons of other animals, and the calibration of the noise estimate
  after contrasts (../second_review).
* reference_figure.tex (Fig. 4): the reference's axes and condition maps, reweighting, the atlas's size, and RNA
  from nuclei in the bone-marrow test.
* savings_figure.tex (Fig. 5): development curves, the external test, the saving in every test data set
  (results/savings_summary.json) and where the saving comes from.
* law_figure.tex (Fig. 6): the law against observation (../predictability), every prospective problem and the budget
  chosen from a pilot (../second_review).
* pairfree_figure.tex (Fig. 7): learning without pairs in blood (../cross_study) and in the melanoma screen
  (../perturbation), with its replication in the monocyte screen (../perturbation_replication).

Every number is read from the result records of the analyses; nothing here recomputes a result.
"""

from __future__ import annotations

import argparse
import importlib.util
import json
import re
from datetime import datetime
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
EXT = HERE.parent
DEP = EXT / "deployment"


def _load_module(name, path):
    spec = importlib.util.spec_from_file_location(name, path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


sa = _load_module("semipaired_assets", EXT / "semipaired" / "make_assets.py")
ra = _load_module("review_assets", HERE / "review_assets.py")
COMMON = sa.COMMON
COMMON_X = COMMON.replace("ymajorgrids=true", "xmajorgrids=true") + ",y tick style={draw=none}"
NUM = {1: "one", 2: "two", 3: "three", 4: "four", 5: "five", 6: "six", 7: "seven", 8: "eight", 9: "nine",
       10: "ten", 11: "eleven", 12: "twelve"}
COLORS = ["\\definecolor{propcol}{HTML}{217D91}", "\\definecolor{pairedcol}{HTML}{5D6670}",
          "\\definecolor{semicol}{HTML}{C9803A}", "\\definecolor{champcol}{HTML}{8E4B8C}",
          "\\definecolor{ridgecol}{HTML}{9AA3AB}", "\\definecolor{meancol}{HTML}{A64442}",
          "\\definecolor{sitecol}{HTML}{6A8FB3}"]


HEADER = "% Generated by extension/synthesis/make_assets.py. Do not edit."
PICTURE = [HEADER] + COLORS + ["\\begin{tikzpicture}[font=\\sffamily]"]


def load(path):
    return json.loads(Path(path).read_text())


LOG_X = "xmode=log,log basis x=2,"


def axis_start(at, name, width, height, options=""):
    """The opening of a pgfplots axis: position, name, size and the first options."""
    return f"\\begin{{axis}}[{at}name={name},scale only axis,width={width}\\textwidth,height={height},{options}"


def row(label, cells):
    """A table row: the label, then the cells, separated by ampersands."""
    return f"{label} & " + " & ".join(cells) + " \\\\"


def signed(text):
    return "\\ensuremath{-}" + text[1:] if text.startswith("-") else text


def pct(v, digits=None):
    p = 100 * v
    if digits is None:
        digits = 1 if abs(p) < 10 else 0
    return signed(f"{p:.{digits}f}")


def fac(v):
    return f"{v:.2f}" if v < 1.15 else f"{v:.1f}"


def thousands(n):
    return f"{int(round(n)):,}"


def edt(stamp, date=True):
    """A freeze time 'YYYY-MM-DD HH:MM:SS EDT' as '19:35 EDT on 28 September 2026', or as '19:35 EDT'."""
    day, clock = stamp.split()[:2]
    if not date:
        return f"{clock[:5]} EDT"
    d = datetime.strptime(day, "%Y-%m-%d")
    return f"{clock[:5]} EDT on {d.day} {d:%B %Y}"


# ------------------------------------------------------------------ macros

def macros(summ, dep, dinfo, fly, struct, dep_frozen, con, mp, law, fly_own, sizes):
    """Macros of the savings summary, the bone-marrow test and its analyses after scoring, and the fly connectome
    with unpaired neurons of other animals."""
    m = {}
    m["SyNTest"] = NUM[summ["n_test"]]
    m["SyNInf"] = NUM[summ["n_informative"]]
    m["SyGeo"] = fac(summ["geometric_mean"])
    m["SyGeoLo"], m["SyGeoHi"] = fac(summ["ci"][0]), fac(summ["ci"][1])
    m["SyMin"], m["SyMax"] = fac(summ["min"]), fac(summ["max"])
    m["SyNLb"] = NUM[summ["n_lower_bound_above_one"]]
    rows = {r["dataset"]: r for r in summ["rows"]}
    m["SyExt"] = fac(rows["overcite"]["factor"])
    # bone-marrow test
    p = dep["targets"]["0.5"]
    m["DpLevel"] = pct(p["level"])
    m["DpTarget"] = pct(p["target"])
    for arm, key in (("proposed_other", "Other"), ("proposed_same", "Same"), ("proposed_same_poolstd", "SamePool")):
        m[f"DpCells{key}"] = f"{p['cells'][arm]['cells']:.0f}"
    m["DpSaveOther"] = fac(p["D1_other_vs_paired_only"]["ratio"])
    m["DpSaveOtherLo"], m["DpSaveOtherHi"] = (fac(x) for x in p["D1_other_vs_paired_only"]["ci"])
    m["DpNonInf"] = fac(p["D3_other_over_same"]["ratio"])
    m["DpNonInfLo"], m["DpNonInfHi"] = (fac(x) for x in p["D3_other_over_same"]["ci"])
    for frac, tag in (("0.25", "Quarter"), ("0.75", "ThreeQ")):
        q = dep["targets"][frac]
        m[f"DpSaveOther{tag}"] = fac(q["D1_other_vs_paired_only"]["ratio"])
        m[f"DpSaveOther{tag}Lo"], m[f"DpSaveOther{tag}Hi"] = (fac(x) for x in q["D1_other_vs_paired_only"]["ci"])
        m[f"DpNonInf{tag}"] = fac(q["D3_other_over_same"]["ratio"])
        m[f"DpNonInf{tag}Lo"], m[f"DpNonInf{tag}Hi"] = (fac(x) for x in q["D3_other_over_same"]["ci"])
    m["DpSaveSame"] = fac(p["same_vs_paired_only"]["ratio"])
    m["DpSaveSamePool"] = fac(p["same_poolstd_vs_paired_only"]["ratio"])
    m["DpDOne"] = "met" if dep["hypotheses"]["D1"] else "not met"
    m["DpDTwo"] = "met" if dep["hypotheses"]["D2"] else "not met"
    m["DpDThree"] = "met" if dep["hypotheses"]["D3"] else "not met"
    b = dep["budgets"]
    rf = dep["rf"]
    top = b.index(max(b))
    m["DpMaxBudget"] = str(max(b))
    m["DpRfOtherMax"] = pct(rf["proposed_other"][top])
    m["DpRfSameMax"] = pct(rf["proposed_same"][top])
    m["DpRfAssayMax"] = pct(rf["proposed_assay"][top])
    m["DpRfPairedMax"] = pct(max(rf["paired_only"]))
    m["DpRfMeansBest"] = pct(max(rf["proposed_other_poolstd"]))
    m["DpRfSamePoolFirst"] = pct(rf["proposed_same_poolstd"][0])
    m["DpFirstBudget"] = str(min(b))
    below = [B for B, v in zip(b, rf["proposed_other"]) if v < 0]
    m["DpOwnNegativeBelow"] = str(min(B for B, v in zip(b, rf["proposed_other"]) if v >= 0))
    m["DpOwnNegativeMax"] = str(max(below)) if below else "0"
    sites = dep["sites"]
    sv = [s["other_vs_paired_only"] for s in sites.values()]
    m["DpSiteMin"], m["DpSiteMax"] = fac(min(sv)), fac(max(sv))
    m["DpNSites"] = NUM[len(sites)]
    m["DpNFolds"] = NUM[len(dinfo)]
    same = [f["pool_cells"]["same"] for f in dinfo.values()]
    other = [f["pool_cells"]["other"] for f in dinfo.values()]
    m["DpPoolSameMin"], m["DpPoolSameMax"] = thousands(min(same)), thousands(max(same))
    m["DpPoolOtherMin"], m["DpPoolOtherMax"] = thousands(min(other)), thousands(max(other))
    m["DpReservoir"] = thousands(np.mean([f["reservoir"] for f in dinfo.values()]))
    s = struct["mean"]
    m["DpOverlapOther"], m["DpOverlapAssay"] = f"{s['other']['top5']:.2f}", f"{s['assay']['top5']:.2f}"
    m["DpOverlapOtherTwenty"], m["DpOverlapAssayTwenty"] = f"{s['other']['top20']:.2f}", f"{s['assay']['top20']:.2f}"
    m["DpROther"], m["DpRAssay"] = f"{s['other']['offdiag_r']:.2f}", f"{s['assay']['offdiag_r']:.2f}"
    m["DpFrozenAt"] = dep_frozen
    # after scoring: paired cells centred by contrasts
    cb, cr = con["budgets"], con["rf"]
    ct = con["targets"]["0.5"]
    m["CtOtherFirst"] = pct(cr["c_proposed_other"][0])
    m["CtOtherFifty"] = pct(cr["c_proposed_other"][cb.index(50)])
    m["CtOtherHundred"] = pct(cr["c_proposed_other"][cb.index(100)])
    m["CtOtherMax"] = pct(cr["c_proposed_other"][-1])
    m["CtPairedFirst"] = pct(cr["c_paired_only"][0])
    m["CtPairedMax"] = pct(cr["c_paired_only"][-1])
    m["CtAssayMax"] = pct(cr["c_proposed_assay"][-1])
    m["CtFrozenOtherFirst"] = pct(cr["proposed_other"][0])
    m["CtFrozenOtherHundred"] = pct(cr["proposed_other"][cb.index(100)])
    m["CtCellsOther"] = f"{ct['cells']['c_proposed_other']['cells']:.0f}"
    m["CtCellsSame"] = f"{ct['cells']['c_proposed_same']['cells']:.0f}"
    m["CtSaveOther"] = fac(ct["other_vs_paired_only"]["ratio"])
    m["CtSaveOtherLo"], m["CtSaveOtherHi"] = (fac(x) for x in ct["other_vs_paired_only"]["ci"])
    m["CtOverSame"] = fac(ct["other_over_same"]["ratio"])
    m["CtOverSameLo"], m["CtOverSameHi"] = (fac(x) for x in ct["other_over_same"]["ci"])
    m["CtVsFrozen"] = fac(ct["contrasts_vs_frozen_other"]["ratio"])
    m["CtVsFrozenLo"], m["CtVsFrozenHi"] = (fac(x) for x in ct["contrasts_vs_frozen_other"]["ci"])
    # after scoring: axes and condition maps of each source of unpaired cells
    mr = mp["rf"]
    m["MpOtherMapped"] = pct(mr["other_mapped"][-1])
    m["MpOtherUnmapped"] = pct(mr["other_unmapped"][-1])
    m["MpSameUnmapped"] = pct(mr["same_unmapped"][-1])
    m["MpAssayMapped"] = pct(mr["assay_mapped"][-1])
    m["MpAssayUnmapped"] = pct(mr["assay_unmapped"][-1])
    m["MpAssayOtherMap"] = pct(mr["assay_bases_other_map"][-1])
    # drawn populations of at most three cells (frozen draws)
    m["PsSmallTwentyFive"] = pct(sizes["budgets"]["25"]["at_most_three"], 0)
    m["PsSmallFifty"] = pct(sizes["budgets"]["50"]["at_most_three"], 0)
    # fly: contrasts against own centring with the factor sqrt(n/(n-1)) (largest difference over budgets, points)
    d_prop = max(abs(a - b) for a, b in zip(fly["rf"]["proposed_own_standardization"],
                                           fly_own["rf"]["proposed_own_standardization"]))
    d_pair = max(abs(a - b) for a, b in zip(fly["rf"]["paired_only_own_standardization"],
                                           fly_own["rf"]["paired_only_own_standardization"]))
    m["FxDiffProposed"] = f"{100 * d_prop:.1f}"
    m["FxDiffPaired"] = f"{100 * d_pair:.1f}"
    # after scoring: the law of the saving along each source's axes
    ls = law["summary"]
    for key, tag in (("same", "Same"), ("other", "Other"), ("assay", "Assay")):
        m[f"Lw{tag}"] = fac(ls[key]["saving_closed_geomean"])
        m[f"Lw{tag}Lo"], m[f"Lw{tag}Hi"] = (fac(x) for x in ls[key]["saving_closed_range"])
        m[f"LwW{tag}"] = pct(ls[key]["w_leading_rna5_mean"], 0)
        m[f"LwPi{tag}"] = pct(ls[key]["pi_leading_rna5_mean"], 0)
    # fly, unpaired neurons of other animals, paired neurons centred by contrasts (after scoring)
    fb = fly["budgets"]
    i = fb.index(100)
    r = fly["rf"]
    m["FxOwnHundred"] = pct(r["proposed_own_standardization"][i])
    m["FxSameHundred"] = pct(r["proposed_same_animal_pool"][i])
    m["FxPoolHundred"] = pct(r["proposed_pool_standardization_prespecified"][i])
    m["FxPairedOwnHundred"] = pct(r["paired_only_own_standardization"][i])
    m["FxPairedPoolHundred"] = pct(r["paired_only_pool_standardization_prespecified"][i])
    m["FxOwnMax"] = pct(max(r["proposed_own_standardization"]))
    return m


def write_macros(path, m):
    path.write_text(HEADER + "\n"
                    + "".join(f"\\newcommand{{\\{k}}}{{{v}}}\n" for k, v in sorted(m.items())))


# ------------------------------------------------------------------ tables of the bone-marrow note

ARM_LABELS = [("paired_only", "Paired cells only"), ("proposed_same_poolstd", "Same samples, their averages"),
              ("proposed_same", "Own site"), ("proposed_other", "Other sites"),
              ("proposed_assay", "Other sites, RNA from nuclei"),
              ("proposed_other_poolstd", "Other sites, their averages")]


def cell_pct(v):
    return pct(v, 0) if abs(100 * v) >= 10 else pct(v, 1)


def deploy_table(dep):
    b = dep["budgets"]
    p = dep["targets"]["0.5"]["cells"]
    lines = [HEADER,
             "\\begin{tabular}{@{}l" + "r" * len(b) + "r@{}}", "\\toprule",
             " & \\multicolumn{%d}{c}{Recovered (\\%%) with paired cells} & Paired cells \\\\" % len(b),
             "\\cmidrule(lr){2-%d}" % (len(b) + 1),
             "Unpaired cells & " + " & ".join(str(x) for x in b) + " & to the target \\\\", "\\midrule"]
    for arm, lab in ARM_LABELS:
        c = p[arm]
        cells = f"$>${c['cells']:.0f}" if c["relation"] == ">" else f"{c['cells']:.0f}"
        lines.append(f"{lab} & " + " & ".join(cell_pct(v) for v in dep["rf"][arm]) + f" & {cells} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(lines) + "\n"


def site_table(dep):
    lines = [HEADER,
             "\\begin{tabular}{@{}lrrr@{}}", "\\toprule",
             "Site & Best recovery (\\%) & Other sites & Other sites, RNA from nuclei \\\\", "\\midrule"]
    for s, r in sorted(dep["sites"].items()):
        rel = r["relations"]
        def show(num_arm, den_arm, v):
            lower = rel[num_arm] == ">" and rel[den_arm] != ">"
            both = rel[num_arm] == ">" and rel[den_arm] == ">"
            return "n.r." if both else (("$\\geq$" if lower else "") + fac(v))
        lines.append(f"{s} & {pct(r['level'], 0)} & "
                     f"{show('paired_only', 'proposed_other', r['other_vs_paired_only'])} & "
                     f"{show('paired_only', 'proposed_assay', r['assay_vs_paired_only'])} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(lines) + "\n"


def fly_table(fly):
    b = fly["budgets"]
    rows = [("proposed_same_animal_pool", "Same animal, centred on its averages (benchmark)"),
            ("proposed_pool_standardization_prespecified", "Other animals, centred on their averages (prespecified)"),
            ("proposed_own_standardization", "Other animals, centred by contrasts (after scoring)"),
            ("paired_only_same_animal_pool", "Paired neurons only, same animal's averages"),
            ("paired_only_pool_standardization_prespecified", "Paired neurons only, other animals' averages"),
            ("paired_only_own_standardization", "Paired neurons only, centred by contrasts")]
    lines = [HEADER,
             "\\begin{tabular}{@{}l" + "r" * len(b) + "@{}}", "\\toprule",
             " & \\multicolumn{%d}{c}{Recovered (\\%%) with paired neurons} \\\\" % len(b),
             "\\cmidrule(lr){2-%d}" % (len(b) + 1),
             "Estimator & " + " & ".join(str(x) for x in b) + " \\\\", "\\midrule"]
    for k, lab in rows:
        lines.append(f"{lab} & " + " & ".join(cell_pct(v) for v in fly["rf"][k]) + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(lines) + "\n"


# ------------------------------------------------------------------ validation test (a study not analysed before)

VAL = EXT / "validation"
VAL_ARMS = [("paired_only", "Paired cells only"), ("atlas", "Atlas (other study)"),
            ("other", "Other pools, other donors"), ("own", "Own samples"),
            ("own_poolstd", "Own samples, their averages"), ("atlas_dfcentre", "Atlas, centred as in bone marrow")]
WORD_BUDGET = {25: "TwentyFive", 50: "Fifty", 100: "Hundred", 200: "TwoHundred", 400: "FourHundred",
               800: "EightHundred"}


def val_macros(val, vfreeze, vman, cal_bm, prows, m):
    b = val["budgets"]
    p = val["targets"]["0.5"]
    m["VlLevel"], m["VlTarget"] = pct(p["level"]), pct(p["target"])
    for arm, key in (("paired_only", "Paired"), ("atlas", "Atlas"), ("other", "Other"), ("own", "Own"),
                     ("own_poolstd", "OwnPool"), ("atlas_dfcentre", "Df")):
        c = p["cells"][arm]
        m[f"VlCells{key}"] = f"{c['cells']:.0f}"
        for B in (25, 50, 100, 800):
            m[f"VlRf{key}{WORD_BUDGET[B]}"] = pct(val["rf"][arm][b.index(B)])
            lo, hi = val["rf_ci"][arm][b.index(B)]
            m[f"VlRf{key}{WORD_BUDGET[B]}Lo"], m[f"VlRf{key}{WORD_BUDGET[B]}Hi"] = pct(lo), pct(hi)
    for name, key in (("V1_atlas_vs_paired_only", "SaveAtlas"), ("V3_other_vs_paired_only", "SaveOther"),
                      ("V4_atlas_over_own", "AtlasOverOwn"), ("own_vs_paired_only", "SaveOwn"),
                      ("atlas_over_other", "AtlasOverOther"), ("own_poolstd_vs_paired_only", "SaveOwnPool"),
                      ("atlas_dfcentre_vs_paired_only", "SaveDf")):
        r = p[name]
        fmt = (lambda v: f"{v:.2f}") if key in ("AtlasOverOwn", "AtlasOverOther") else fac
        m[f"Vl{key}"] = fmt(r["ratio"])
        m[f"Vl{key}Lo"], m[f"Vl{key}Hi"] = fmt(r["ci"][0]), fmt(r["ci"][1])
    for frac, tag in (("0.25", "Quarter"), ("0.75", "ThreeQ")):
        r = val["targets"][frac]["V1_atlas_vs_paired_only"]
        m[f"VlSaveAtlas{tag}"] = fac(r["ratio"])
        m[f"VlSaveAtlas{tag}Lo"], m[f"VlSaveAtlas{tag}Hi"] = fac(r["ci"][0]), fac(r["ci"][1])
    for k, v in val["hypotheses"].items():
        word = {"V1": "VOne", "V2": "VTwo", "V3": "VThree", "V4": "VFour"}[k]
        m[f"Vl{word}"] = "met" if v else "not met"
    pools = val["pools"]
    sv = [r["atlas_vs_paired_only"] for r in pools.values()]
    m["VlPoolMin"], m["VlPoolMax"] = fac(min(sv)), fac(max(sv))
    m["VlNPools"] = NUM[len(pools)]
    m["VlNFolds"] = str(len(val["folds"]))
    m["VlNDonors"] = str(len({f["donor"] for f in val["folds"].values()}))
    acct = val["audit"]["accounting"]
    for B in (25, 50, 100):
        a = acct[str(B)]
        m[f"VlRows{WORD_BUDGET[B]}"] = f"{a['rows_contrasts']:.0f}"
        m[f"VlPops{WORD_BUDGET[B]}"] = f"{a['populations']:.0f}"
        m[f"VlSingles{WORD_BUDGET[B]}"] = f"{a['singletons']:.1f}"
    cal = val["audit"]["calibration"]
    rc = [v["ratio_estimated_to_actual"] for v in cal["contrasts"].values()]
    rd = [v["ratio_estimated_to_actual"] for v in cal["dfcentre"].values()]
    m["VlCalConMin"], m["VlCalConMax"] = f"{min(rc):.2f}", f"{max(rc):.2f}"
    m["VlCalDfMin"], m["VlCalDfMax"] = f"{min(rd):.2f}", f"{max(rd):.2f}"
    bc = [v["ratio_estimated_to_actual"] for v in cal_bm["calibration"]["contrasts"].values()]
    bd = [v["ratio_estimated_to_actual"] for v in cal_bm["calibration"]["dfcentre"].values()]
    m["DpCalConMin"], m["DpCalConMax"] = f"{min(bc):.2f}", f"{max(bc):.2f}"
    m["DpCalDfMin"], m["DpCalDfMax"] = f"{min(bd):.2f}", f"{max(bd):.2f}"
    m["DpCalDraws"] = str(cal_bm["draws"])
    # both data sets together: the noise term under contrasts and under the bone-marrow test's own centring
    allc, alld = [f"{v:.2f}" for v in rc + bc], rd + bd
    m["CalCon"] = allc[0] if len(set(allc)) == 1 else f"{min(rc + bc):.2f}--{max(rc + bc):.2f}"
    m["CalDfMin"], m["CalDfMax"] = f"{min(alld):.2f}", f"{max(alld):.2f}"
    m["VlFrozenAt"] = edt(vfreeze["frozen"])
    m["VlHashedAt"] = edt(vman["written"], date=False)
    panels = load(VAL / "results" / "predictions_info.json")["panels"]
    m["VlNAntibodies"] = str(len(panels["proteins_new"]))
    # the 29 prospective problems of the law
    rows = [r for r in prows if r["target"] == 0.5]
    below = [r for r in rows if not r["estimable"] and r["rel_blocks"] == "<="]
    above = [r for r in rows if not r["estimable"] and r["rel_blocks"] != "<="]
    m["PrNBelow"], m["PrNAbove"] = str(len(below)), str(len(above))
    m["PrNNeither"] = str(sum(1 for r in above if r["rel_blocks"] == ">"))


def sensitivity_macros(val, con, m):
    """After scoring: the validation's saving with the budget axis counted in contrast rows (mean rows at each budget,
    the same interpolation as the test), and the bone-marrow paired-only control under both centrings."""
    grun = _load_module("grun", EXT / "generality" / "grun.py")
    p = val["targets"]["0.5"]
    rows = [val["audit"]["accounting"][str(B)]["rows_contrasts"] for B in val["budgets"]]
    na, ra = grun.needed(val["rf"]["atlas"], p["target"], rows)
    npo, rpo = grun.needed(val["rf"]["paired_only"], p["target"], rows)
    assert (ra, rpo) == ("=", ">")
    m["VlRowsAtlas"], m["VlRowsMax"], m["VlSaveAtlasRows"] = f"{na:.0f}", f"{rows[-1]:.0f}", fac(npo / na)
    b = con["budgets"]
    for arm, key in (("paired_only", "DpPoDf"), ("c_paired_only", "DpPoCon")):
        for B in (25, 50, 100):
            m[f"{key}{WORD_BUDGET[B]}"] = pct(con["rf"][arm][b.index(B)])
    # the two centrings at the larger budgets
    big = [abs(con["rf"]["c_paired_only"][b.index(B)] - con["rf"]["paired_only"][b.index(B)]) for B in (400, 800)]
    assert max(big) < 0.001, big
    lead = [con["rf"]["c_paired_only"][b.index(B)] >= con["rf"]["paired_only"][b.index(B)] for B in (25, 50, 100, 200)]
    assert all(lead), lead


def val_table(val):
    b = val["budgets"]
    p = val["targets"]["0.5"]["cells"]
    lines = [HEADER,
             "\\begin{tabular}{@{}l" + "r" * len(b) + "r@{}}", "\\toprule",
             " & \\multicolumn{%d}{c}{Recovered (\\%%) with paired cells} & Paired cells \\\\" % len(b),
             "\\cmidrule(lr){2-%d}" % (len(b) + 1),
             "Arm & " + " & ".join(str(x) for x in b) + " & to the target \\\\", "\\midrule"]
    for arm, lab in VAL_ARMS:
        c = p[arm]
        cells = f"$>${c['cells']:.0f}" if c["relation"] == ">" else f"{c['cells']:.0f}"
        lines.append(f"{lab} & " + " & ".join(cell_pct(v) for v in val["rf"][arm]) + f" & {cells} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(lines) + "\n"


def audit_table(val, cal_bm, sizes):
    """Degrees of freedom of the paired draws and calibration of the noise term, validation and bone-marrow tests."""
    acct = val["audit"]["accounting"]
    cal = val["audit"]["calibration"]
    bm = sizes["budgets"]
    budgets = [25, 50, 100, 200]
    own_df = "Noise term / variance across draws, own averages, $\\sqrt{n/(n-1)}$"

    def ratio(c, centring, B):
        return c[centring][str(B)]["ratio_estimated_to_actual"]

    lines = [HEADER,
             "\\begin{tabular}{@{}l" + "r" * len(budgets) + "@{}}", "\\toprule",
             "Paired cells drawn & " + " & ".join(str(B) for B in budgets) + " \\\\", "\\midrule",
             "\\multicolumn{%d}{@{}l}{\\textit{Validation (prespecified)}} \\\\" % (len(budgets) + 1),
             row("Populations with a drawn cell", (f"{acct[str(B)]['populations']:.1f}" for B in budgets)),
             row("Single cells (no contrast)", (f"{acct[str(B)]['singletons']:.1f}" for B in budgets)),
             row("Contrast rows", (f"{acct[str(B)]['rows_contrasts']:.1f}" for B in budgets)),
             row("Noise term / variance across draws, contrasts",
                 (f"{ratio(cal, 'contrasts', B):.2f}" for B in budgets)),
             row(own_df, (f"{ratio(cal, 'dfcentre', B):.2f}" for B in budgets)),
             "\\multicolumn{%d}{@{}l}{\\textit{Bone marrow (after scoring)}} \\\\" % (len(budgets) + 1),
             row("Populations with a drawn cell", (f"{bm[str(B)]['populations']:.1f}" for B in budgets)),
             row("Single cells (no contrast)", (f"{B * bm[str(B)]['single']:.1f}" for B in budgets)),
             row("Contrast rows", (f"{bm[str(B)]['contrasts']:.1f}" for B in budgets)),
             row("Noise term / variance across draws, contrasts",
                 (f"{ratio(cal_bm['calibration'], 'contrasts', B):.2f}" for B in budgets)),
             row(own_df, (f"{ratio(cal_bm['calibration'], 'dfcentre', B):.2f}" for B in budgets)),
             "\\bottomrule", "\\end{tabular}"]
    return "\n".join(lines) + "\n"


# ------------------------------------------------------------------ savings in every test data set (SI)

UNITS = {"overcite": "ORFs", "hao": "donors", "stephenson": "patients", "bmmc_cite": "donors", "colon": "patients",
         "bmmc_multiome": "donors", "scala_m1": "mice", "gouwens_visp": "recording days", "banc": "neuron types",
         "malecns": "neuron types"}


def f1(v):
    return f"{v:.1f}"


def saving_text(factor, ci, comp_rel, prop_rel):
    lower = comp_rel == ">" or prop_rel == "<="
    return ("$\\geq$" if lower else "") + f"{f1(factor)} ({f1(ci[0])}--{f1(ci[1])})"


def savings_table(summ):
    """Each test data set's saving over paired-only estimation under the rule that enters the 3.1-fold summary and,
    for the benchmark, under its original plan."""
    gen = EXT / "generality" / "results"
    orig = load(gen / "summary.json")["G1_paired_only/0.5"]
    amend = load(gen / "summary_amend1.json")
    lines = [HEADER,
             "\\begin{tabular}{@{}llrlrl@{}}", "\\toprule",
             " & & \\multicolumn{2}{c}{Rule of the summary} & \\multicolumn{2}{c}{Original plan} \\\\",
             "\\cmidrule(lr){3-4}\\cmidrule(lr){5-6}",
             "Data set & Units held out & Target (\\%) & Saving (95\\% CI) & Target (\\%) & Saving \\\\", "\\midrule"]
    for r in summ["rows"]:
        d = r["dataset"]
        if d == "overcite":
            lines.append(f"{r['label']} & {UNITS[d]} & 30 & "
                         f"{saving_text(r['factor'], r['ci'], r['comparator_relation'], r['proposed_relation'])}"
                         f" & 30 & {f1(r['factor'])} \\\\")
            continue
        a = load(gen / f"{d}_amend1.json")["savings"]["paired_only"]["0.5"]
        o = load(gen / f"{d}.json")["savings"]["paired_only"]["0.5"]
        if r["informative"]:
            left = saving_text(r["factor"], r["ci"], r["comparator_relation"], r["proposed_relation"])
        else:
            left = "no dependence recovered"
        if o["target_rf"] < 0:
            right = "1 (negative target)"
        elif o["comparator_relation"] == ">" and o["proposed_relation"] == ">":
            right = "1 (neither reached)"
        else:
            right = ("$\\geq$" if o["comparator_relation"] == ">" else "") + f1(o["factor"])
        lines.append(f"{r['label']} & {UNITS[d]} & {pct(a['target_rf'], 1)} & {left} & {pct(o['target_rf'], 1)} & "
                     f"{right} \\\\")
    inf = amend["informative/G1_paired_only/0.5"]
    lines += ["\\midrule",
              f"\\multicolumn{{3}}{{@{{}}l}}{{Geometric mean, {NUM[summ['n_informative']]} test data sets with "
              f"dependence recovered}} & {f1(summ['geometric_mean'])} "
              f"({f1(summ['ci'][0])}--{f1(summ['ci'][1])}) & & \\\\",
              f"\\multicolumn{{3}}{{@{{}}l}}{{Geometric mean, {NUM[len(inf['per_dataset'])]} benchmark data sets with "
              f"dependence recovered}} & {f1(inf['geometric_mean'])} ({f1(inf['ci'][0])}--{f1(inf['ci'][1])}) & & \\\\",
              f"\\multicolumn{{3}}{{@{{}}l}}{{Geometric mean, nine benchmark data sets, original plan (G1)}} & & & "
              f"{f1(orig['geometric_mean'])} ({f1(orig['ci'][0])}--{f1(orig['ci'][1])}) \\\\",
              "\\bottomrule", "\\end{tabular}"]
    return "\n".join(lines) + "\n"


# ------------------------------------------------------------------ Fig. 4

def ext_panel(o, at, name, title):
    b, rf, ci = o["budgets"], o["rf"], o["rf_ci"]
    xt = ",".join(str(x) for x in b)
    lines = [axis_start(at, name, ".3", "3.9cm", LOG_X),
             f" xmin=20,xmax=480,ymin=-20,ymax=80,xtick={{{xt}}},xticklabels={{{xt}}},ytick={{-20,0,20,40,60,80}},",
             " xlabel={Paired cells},ylabel={Dependence recovered (\\%)},",
             f" title={{{title}}},", COMMON + "]",
             "\\draw[dashed,black!45] (axis cs:20,30) -- (axis cs:480,30);"]
    lo = " ".join(f"({x},{max(100 * c[0], -20):.2f})" for x, c in zip(b, ci[sa.PROPOSED]))
    hi = " ".join(f"({x},{min(100 * c[1], 80):.2f})" for x, c in zip(reversed(b), reversed(ci[sa.PROPOSED])))
    lines.append(f"\\fill[propcol,opacity=.15] plot coordinates {{ {lo} {hi} }} -- cycle;")
    lines += sa.curve_lines(b, rf[sa.PROPOSED], sa.STYLES["prop"])
    lines += sa.curve_lines(b, sa.envelope(rf, sa.PAIRED_ONLY, len(b)), sa.STYLES["paired"])
    lines += sa.curve_lines(b, sa.envelope(rf, ["semicca/pooled", "semicca/percond"], len(b)), sa.STYLES["semi"])
    lines += sa.curve_lines(b, rf["champollion/transport"], sa.STYLES["champ"])
    lines += sa.curve_lines(b, sa.envelope(rf, ["ridge_u/pooled", "ridge_u/percond", "ridge_p/pooled",
                                                "ridge_p/percond"], len(b)), sa.STYLES["ridge"])
    lines.append("\\end{axis}")
    return lines


def forest_panel(summ, at, name, title):
    rows = summ["rows"]
    order = list(reversed(rows))                          # external test at the top
    n = len(order)
    labels = []
    for r in order:
        lab = r["label"].replace("T cells, ORF screen (external test)", "T cells (external test)")
        labels.append("{" + lab + "}")
    labels = ["{\\textbf{Geometric mean}, descriptive}"] + labels
    lines = [axis_start(at, name, ".23", "4.6cm", LOG_X),
             f" xmin=0.5,xmax=12,ymin=-.6,ymax={n + .6},xtick={{0.5,1,2,4,8}},xticklabels={{0.5,1,2,4,8}},",
             f" ytick={{{','.join(str(i) for i in range(n + 1))}}},yticklabels={{{','.join(labels)}}},",
             " xlabel={Saving over paired cells only},",
             f" title={{{title}}},", COMMON_X + ",yticklabel style={font=\\sffamily\\scriptsize}]",
             f"\\draw[black!50] (axis cs:1,-.6) -- (axis cs:1,{n + .6});"]
    for y, r in enumerate(order, start=1):
        if not r["informative"]:
            lines.append(f"\\node[font=\\sffamily\\scriptsize,color=black!70,anchor=west] at (axis cs:1.05,{y}) "
                         "{no dependence recovered};")
            continue
        lo, hi = r["ci"]
        # a lower bound: paired-only estimation did not reach the target, or the estimator reached it at the
        # smallest budget
        censored = r["comparator_relation"] == ">" or r["proposed_relation"] == "<="
        mark = "o" if censored else "*"
        col = "propcol"
        x0, x1 = max(lo, .5), min(hi, 12)
        lines.append(f"\\draw[color={col},line width=.7pt] (axis cs:{x0:.3f},{y}) -- (axis cs:{x1:.3f},{y});")
        lines.append(f"\\addplot[only marks,color={col},mark={mark},mark size=1.7pt] "
                     f"coordinates {{ ({r['factor']:.3f},{y}) }};")
    gm, (glo, ghi) = summ["geometric_mean"], summ["ci"]
    lines.append(f"\\draw[color=black,line width=.9pt] (axis cs:{glo:.3f},0) -- (axis cs:{ghi:.3f},0);")
    lines.append(f"\\addplot[only marks,color=black,mark=diamond*,mark size=2.6pt] coordinates {{ ({gm:.3f},0) }};")
    lines.append("\\end{axis}")
    return lines


def mech_panel(sf, sp, at, name, title):
    rows = [("bjs2/mapped", "Estimator"), ("bjs2/pooled", "Without cell-type map"),
            ("bjs/mapped", "RNA axes only"), ("abl/bjs_pairbasis", "Axes from paired cells"),
            ("abl/bjs_marker", "Original coordinates"),
            ("dose/500", "500 unpaired cells"), ("js/pooled", "Paired cells only")]
    n = len(rows)
    lines = [axis_start(at, name, ".14", "4.6cm", "xmin=-5,xmax=60,"),
             f" ymin=.4,ymax={n + .6},ytick={{{','.join(str(i) for i in range(1, n + 1))}}},",
             " yticklabels={" + ",".join("{" + r[1] + "}" for r in reversed(rows)) + "},",
             " xtick={0,20,40,60},xlabel={At 100 paired cells (\\%)},",
             f" title={{{title}}},", COMMON_X + "]"]
    for s, style, dy in ((sf, "only marks,mark=*,mark size=1.7pt,color=propcol", .15),
                         (sp, "only marks,mark=o,mark size=1.7pt,color=pairedcol", -.15)):
        b = s["budgets"]
        i = b.index(100)
        pts = []
        for y, (a, _) in enumerate(reversed(rows), start=1):
            if a in s["rf"]:
                pts.append(f"({max(100 * s['rf'][a][i], -5):.2f},{y + dy:.2f})")
        lines.append(f"\\addplot[{style}] coordinates {{ {' '.join(pts)} }};")
    lines.append("\\end{axis}")
    return lines


def savings_figure(sf, o, summ, sp):
    lines = list(PICTURE)
    lines += sa.dev_panel(sf, "a", "", "\\textbf{a}\\enspace Melanoma screen (development)", 3600)
    lines += ext_panel(o, "at={(a.outer north east)},anchor=outer north west,xshift=.3cm,", "b",
                       "\\textbf{b}\\enspace External test (prespecified)")
    lines += ["\\path (a.outer south west) -- (b.outer south east) coordinate[pos=.5] (legab);",
              "\\begin{axis}[hide axis,scale only axis,width=1pt,height=1pt,xmin=0,xmax=1,ymin=0,ymax=1,at={(legab)},"
              "anchor=north,yshift=-2pt,legend style={draw=none,font=\\sffamily\\scriptsize,"
              "at={(0.5,0.5)},anchor=north,"
              "legend columns=3,column sep=6pt,cells={anchor=west}}]",
              f"\\addlegendimage{{{sa.STYLES['prop']}}}", "\\addlegendentry{Estimator}",
              f"\\addlegendimage{{{sa.STYLES['paired']}}}", "\\addlegendentry{Paired cells only}",
              f"\\addlegendimage{{{sa.STYLES['semi']}}}", "\\addlegendentry{SemiCCA}",
              f"\\addlegendimage{{{sa.STYLES['champ']}}}", "\\addlegendentry{Champollion}",
              f"\\addlegendimage{{{sa.STYLES['ridge']}}}", "\\addlegendentry{Reference regression}",
              "\\end{axis}"]
    lines += forest_panel(summ, "at={(a.outer south west)},anchor=outer north west,yshift=-1.25cm,", "c",
                          "\\textbf{c}\\enspace Saving in the test data sets")
    lines += mech_panel(sf, sp, "at={(c.outer north east)},anchor=outer north west,xshift=.2cm,", "d",
                        "\\textbf{d}\\enspace Source of the saving")
    lines.append("\\end{tikzpicture}")
    return "\n".join(lines) + "\n"


# ------------------------------------------------------------------ Fig. 3

DEP_ARMS = [("proposed_same_poolstd", "Same samples, their averages",
             "color=black,line width=.9pt,dashed,mark=*,mark size=1.3pt"),
            ("proposed_same", "Own site", "color=sitecol,line width=.9pt,mark=diamond*,mark size=1.7pt"),
            ("proposed_other", "Other sites", "color=propcol,line width=1.2pt,mark=*,mark size=1.6pt"),
            ("proposed_assay", "Other sites, RNA from nuclei",
             "color=semicol,line width=.9pt,mark=triangle*,mark size=1.6pt"),
            ("proposed_other_poolstd", "Other sites, their averages",
             "color=meancol,line width=.9pt,mark=x,mark size=1.8pt"),
            ("paired_only", "Paired cells only", "color=pairedcol,line width=.8pt,mark=square*,mark size=1.3pt")]


def fly_panel(fly, at, name, title):
    b, r = fly["budgets"], fly["rf"]
    xt = ",".join(str(x) for x in b)
    lines = [axis_start(at, name, ".3", "3.5cm", LOG_X),
             f" xmin=20,xmax=480,ymin=-20,ymax=80,xtick={{{xt}}},xticklabels={{{xt}}},ytick={{-20,0,20,40,60,80}},",
             " xlabel={Paired neurons},ylabel={Dependence recovered (\\%)},",
             f" title={{{title}}},", COMMON + "]"]
    for arm, _, style in FLY_ARMS:
        lines += sa.curve_lines(b, r[arm], style)
    lines.append("\\end{axis}")
    return lines


FLY_ARMS = [("proposed_same_animal_pool", "Same animal, its averages",
             "color=black,line width=.9pt,dashed,mark=*,mark size=1.3pt"),
            ("proposed_own_standardization", "Other animals, contrasts",
             "color=propcol,line width=1.2pt,mark=*,mark size=1.6pt"),
            ("proposed_pool_standardization_prespecified", "Other animals, their averages",
             "color=meancol,line width=.9pt,mark=x,mark size=1.8pt"),
            ("paired_only_own_standardization", "Paired neurons only, contrasts",
             "color=pairedcol,line width=.8pt,mark=square*,mark size=1.3pt")]

def offscale(arms, budgets, rf, lo=-.2):
    """Arm labels extended by the lowest value of any point drawn at the bottom of the axis."""
    out = []
    for arm, label, style in arms:
        v = np.asarray(rf[arm], float)
        if np.nanmin(v) < lo:
            i = int(np.nanargmin(v))
            label = f"{label} (to {signed(f'{100 * v[i]:.0f}')}\\% at {budgets[i]})"
        out.append((arm, label, style))
    return out


def legend_below(anchor, arms, columns, sep=6):
    out = ["\\begin{axis}[hide axis,scale only axis,width=1pt,height=1pt,xmin=0,xmax=1,ymin=0,ymax=1,"
           f"at={{({anchor})}},anchor=north,yshift=-2pt,legend style={{draw=none,font=\\sffamily\\scriptsize,"
           f"at={{(0.5,0.5)}},anchor=north,legend columns={columns},column sep={sep}pt,cells={{anchor=west}}}}]"]
    for arm in arms:
        out += [f"\\addlegendimage{{{arm[-1]}}}", f"\\addlegendentry{{{arm[1]}}}"]
    out.append("\\end{axis}")
    return out


VAL_FIG_ARMS = [("own_poolstd", "Own samples, their averages",
                 "color=black,line width=.9pt,dashed,mark=*,mark size=1.3pt"),
                ("own", "Own samples", "color=sitecol,line width=.9pt,mark=diamond*,mark size=1.7pt"),
                ("other", "Other pools and donors", "color=champcol,line width=.9pt,mark=triangle*,mark size=1.7pt"),
                ("atlas", "Atlas of another study", "color=propcol,line width=1.2pt,mark=*,mark size=1.6pt"),
                ("atlas_dfcentre", "Atlas, centred as in bone marrow",
                 "color=propcol,line width=.9pt,densely dotted,mark=o,mark size=1.5pt,mark options={solid}"),
                ("paired_only", "Paired cells only", "color=pairedcol,line width=.8pt,mark=square*,mark size=1.3pt")]


def curves_panel(res, arms, at, name, title, ymax, height="3.5cm"):
    b, rf = res["budgets"], res["rf"]
    xt = ",".join(str(x) for x in b)
    tgt = 100 * res["targets"]["0.5"]["target"]
    ticks = ",".join(str(t) for t in range(-20, ymax + 1, 20))
    lines = [axis_start(at, name, ".3", height, LOG_X),
             f" xmin=20,xmax=1000,ymin=-20,ymax={ymax},xtick={{{xt}}},xticklabels={{{xt}}},ytick={{{ticks}}},",
             " xlabel={Paired cells},ylabel={Dependence recovered (\\%)},",
             f" title={{{title}}},", COMMON + "]",
             f"\\draw[dashed,black!45] (axis cs:20,{tgt:.2f}) -- (axis cs:1000,{tgt:.2f});"]
    for arm, _, style in arms:
        lines += sa.curve_lines(b, rf[arm], style)
    lines.append("\\end{axis}")
    return lines


def cells_panel(res, arms, at, name, title, height="3.5cm"):
    p = res["targets"]["0.5"]["cells"]
    n = len(arms)
    lines = [axis_start(at, name, ".2", height, LOG_X),
             f" xmin=20,xmax=1600,ymin=.4,ymax={n + .6},xtick={{25,100,400,1600}},xticklabels={{25,100,400,$>$800}},",
             f" ytick={{{','.join(str(i) for i in range(1, n + 1))}}},",
             " yticklabels={" + ",".join("{" + lab + "}" for _, lab, _ in reversed(arms)) + "},",
             " xlabel={Paired cells to the target},",
             f" title={{{title}}},", COMMON_X + "]",
             "\\draw[black!25] (axis cs:800,.4) -- (axis cs:800,%s);" % (n + .6)]
    for y, (arm, _, style) in enumerate(reversed(arms), start=1):
        c = p[arm]
        color = style.split(",")[0].replace("color=", "")
        if c["relation"] == ">":
            lines.append(f"\\draw[->,color={color},line width=.8pt] (axis cs:800,{y}) -- (axis cs:1400,{y});")
            lines.append(f"\\addplot[only marks,mark=o,mark size=1.8pt,color={color}] coordinates {{ (800,{y}) }};")
        else:
            bar = ("line width=1.4pt,densely dotted" if "dotted" in style
                   else "line width=1.6pt,densely dashed" if "dashed" in style else "line width=2.4pt")
            lines.append(f"\\draw[color={color},{bar}] (axis cs:20,{y}) -- (axis cs:{c['cells']:.1f},{y});")
            lines.append(f"\\node[font=\\sffamily\\scriptsize,anchor=west] at (axis cs:{c['cells'] * 1.08:.1f},{y}) "
                         f"{{{c['cells']:.0f}}};")
    lines.append("\\end{axis}")
    return lines


READOUT_ARMS = [a for a in VAL_FIG_ARMS if a[0] in ("own", "other", "atlas", "paired_only")]
RD_BUDGET = {25: "TwentyFive", 50: "Fifty", 100: "Hundred", 150: "OneFifty", 200: "TwoHundred", 400: "FourHundred",
             800: "EightHundred"}
RD_ARM = {"atlas": "Atlas", "paired_only": "Po", "own": "Own", "other": "Other"}
RD_END = {"E1": "One", "E2": "Two", "E3": "Three", "E1_cognate": "Cog"}
TYPE_WORD = {"B": "B", "CD4 T": "CDFour", "CD8 T": "CDEight", "NK": "NK", "CD14 Mono": "Mono"}


def sci(v):
    e = int(np.floor(np.log10(abs(v))))
    return f"{v / 10 ** e:.1f}\\times10^{{{e}}}"


def readout_macros(rd, rfreeze, m):
    """Macros of the biological readout of the validation (validation/readout/results/readout.json)."""
    b = rd["budgets"]
    for e, ew in RD_END.items():
        for arm, aw in RD_ARM.items():
            for B, bw in RD_BUDGET.items():
                i = b.index(B)
                m[f"Bo{ew}{aw}{bw}"] = pct(rd["values"][e][arm][i])
                lo, hi = rd["ci"][e][arm][i]
                m[f"Bo{ew}{aw}{bw}Lo"], m[f"Bo{ew}{aw}{bw}Hi"] = pct(lo), pct(hi)
    for h, hw in (("B1", "One"), ("B2", "Two"), ("B3", "Three")):
        m[f"BoB{hw}"] = "met" if rd["hypotheses"][h] else "not met"
        for B, r in rd["differences"][h].items():
            bw = RD_BUDGET[int(B)]
            m[f"BoDiff{hw}{bw}"] = signed(f"{100 * r['difference']:.1f}")
            m[f"BoDiff{hw}{bw}Lo"] = signed(f"{100 * r['ci'][0]:.1f}")
            m[f"BoDiff{hw}{bw}Hi"] = signed(f"{100 * r['ci'][1]:.1f}")
    m["BoRandomTwo"], m["BoPerfectTwo"] = pct(rd["random_E2"]), pct(rd["perfect_E2"])
    m["BoNRep"] = thousands(sum(rd["reproducible_by_type"].values()))
    m["BoNUnits"] = str(sum(rd["units_by_type"].values()))
    m["BoNPairs"] = thousands(rd["pairs_per_unit"])
    m["BoNCognate"] = str(len(rd["cognate"]))
    n_units = sum(rd["units_by_type"].values())
    m["BoRepShare"] = pct(sum(rd["reproducible_by_type"].values()) / (rd["pairs_per_unit"] * n_units), 1)
    for c, cw in TYPE_WORD.items():
        m[f"BoRep{cw}"] = thousands(rd["reproducible_by_type"][c])
        m[f"BoUnits{cw}"] = str(rd["units_by_type"][c])
        for arm in ("atlas", "paired_only"):
            for B in (50, 100, 150):
                m[f"BoType{cw}{RD_ARM[arm]}{RD_BUDGET[B]}"] = pct(rd["by_type"][c]["E1"][arm][b.index(B)])
    for e, ew in (("E1", "One"), ("E2", "Two")):
        n = rd["needed"][e]
        m[f"BoTarget{ew}"] = pct(n["target"])
        for arm, aw in RD_ARM.items():
            c = n["cells"][arm]
            m[f"BoCells{ew}{aw}"] = {">": "$>$", "<=": "$\\leq$"}.get(c["relation"], "") + f"{c['cells']:.0f}"
        s = n["saving_atlas"]
        pre = "at least " if s["numerator_relation"] == ">" else ""
        m[f"BoSave{ew}"] = pre + fac(s["ratio"])
        m[f"BoSave{ew}Lo"], m[f"BoSave{ew}Hi"] = fac(s["ci"][0]), fac(s["ci"][1])
    m["BoIntegrity"] = f"${sci(rd['integrity']['max_abs_P'])}$" if rd["integrity"]["max_abs_P"] > 0 else "0"
    m["BoCompared"] = thousands(rd["integrity"]["compared"])
    m["BoFrozenAt"] = edt(rfreeze["frozen"])


def robust_macros(rb, val, m):
    """Macros of the robustness analyses of the validation (validation/results_posthoc/robustness.json)."""
    sv = [r["saving"] for r in rb["per_donor"].values()]
    m["RbDonorMin"], m["RbDonorMax"] = fac(min(sv)), fac(max(sv))
    m["RbNDonors"] = NUM.get(len(sv), str(len(sv)))
    nc = sum(1 for r in rb["per_donor"].values() if r["paired_only_cells"][1] == ">")
    m["RbDonorsCensored"] = NUM.get(nc, str(nc))
    reached = sum(1 for r in rb["per_donor"].values() if r["paired_only_cells"][1] != ">")
    m["RbDonorsPoReached"] = NUM.get(reached, "none")
    m["RbDonorAtlasMax"] = f"{max(r['atlas_cells'][0] for r in rb['per_donor'].values()):.0f}"
    pv = [r["saving"] for r in rb["per_pool"].values()]
    m["RbPoolMin"], m["RbPoolMax"] = fac(min(pv)), fac(max(pv))
    lo = [r["saving"] for r in rb["leave_one_pool_out"].values()]
    ow = [r["atlas_over_own"] for r in rb["leave_one_pool_out"].values()]
    m["RbLopoMin"], m["RbLopoMax"] = fac(min(lo)), fac(max(lo))
    m["RbLopoOwnMin"], m["RbLopoOwnMax"] = f"{min(ow):.2f}", f"{max(ow):.2f}"
    m["RbReproduces"] = f"${sci(rb['reproduces_hashed_atlas_arm'])}$" if rb["reproduces_hashed_atlas_arm"] > 0 else "0"
    words = {"full": "Full", "patients_4": "PatientsFour", "patients_7": "PatientsSeven",
             "patients_15": "PatientsFifteen", "patients_30": "PatientsThirty", "patients_59": "PatientsFiftyNine",
             "few_B_mono": "FewBMono",
             "few_T": "FewT", "without_B": "WithoutB", "without_CD4_T": "WithoutCDFourT",
             "without_CD8_T": "WithoutCDEightT", "without_NK": "WithoutNK", "without_CD14_Mono": "WithoutMono"}
    for k, v in rb["variants"].items():
        w = words[k]
        c = v["atlas_cells"]
        m[f"RbCells{w}"] = ("$>$" if c["relation"] == ">" else "") + f"{c['cells']:.0f}"
        m[f"RbCells{w}Lo"], m[f"RbCells{w}Hi"] = f"{c['ci'][0]:.0f}", f"{c['ci'][1]:.0f}"
        s = v["saving"]
        pre = "at least " if s["numerator_relation"] == ">" and s["denominator_relation"] == "=" else ""
        m[f"RbSave{w}"] = "none" if c["relation"] == ">" else pre + fac(s["ratio"])
        m[f"RbSave{w}Lo"], m[f"RbSave{w}Hi"] = fac(s["ci"][0]), fac(s["ci"][1])
        m[f"RbRfHundred{w}"] = pct(v["rf"][rb["budgets"].index(100)])
        m[f"RbRfMax{w}"] = pct(max(v["rf"]))
        m[f"RbPops{w}"] = str(v["populations"])
        m[f"RbCellCount{w}"] = thousands(v["cells"])


def composition_macros(cm, m):
    """After scoring: the skewed atlases scored without condition maps
    (validation/results_posthoc/composition_map.json)."""
    for k, w in (("full", "Full"), ("few_B_mono", "FewBMono"), ("few_T", "FewT")):
        v = cm["variants"][k]
        m[f"RbUnmap{w}"] = pct(v["unmapped_rf"][-1])
        m[f"RbMapped{w}"] = pct(v["mapped_rf"][-1])
        m[f"RbMappedMax{w}"] = pct(max(v["mapped_rf"]))


def readout_table(rd):
    b = rd["budgets"]
    lines = [HEADER,
             "\\begin{tabular}{@{}l" + "r" * len(b) + "@{}}", "\\toprule",
             " & \\multicolumn{%d}{c}{Paired cells} \\\\" % len(b), "\\cmidrule(lr){2-%d}" % (len(b) + 1),
             "Arm & " + " & ".join(str(x) for x in b) + " \\\\"]
    for e, title in (("E1", "Direction of reproducible associations (\\%)"),
                     ("E2", "Top 100 pairs reproducible with the estimated sign (\\%)"),
                     ("E3", "Cognate pairs: recovered fraction (\\%)"),
                     ("E1_cognate", "Cognate pairs: direction (\\%)")):
        lines += ["\\midrule", "\\multicolumn{%d}{@{}l}{\\textit{%s}} \\\\" % (len(b) + 1, title)]
        for arm, lab in VAL_ARMS:
            if arm not in rd["values"][e]:
                continue
            lines.append(f"{lab} & " + " & ".join(cell_pct(v) for v in rd["values"][e][arm]) + " \\\\")
    lines += ["\\midrule", "\\multicolumn{%d}{@{}l}{\\textit{Direction by cell type, atlas / paired only (\\%%)}} \\\\"
              % (len(b) + 1)]
    for c, rec in rd["by_type"].items():
        n = rd["reproducible_by_type"][c]
        lines.append(f"{c} ({thousands(n)}) & " + " & ".join(
            f"{100 * x:.0f} / {100 * y:.0f}" for x, y in zip(rec["E1"]["atlas"], rec["E1"]["paired_only"])) + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(lines) + "\n"


SHORT_VARIANT = {"full": "All 118 patients", "patients_59": "59 patients", "patients_30": "30 patients",
                 "patients_15": "15 patients", "patients_7": "7 patients", "patients_4": "4 patients",
                 "few_B_mono": "B, CD14 Mono from 15 patients", "few_T": "CD4, CD8 T from 15 patients",
                 "without_B": "Without B cells", "without_CD4_T": "Without CD4 T", "without_CD8_T": "Without CD8 T",
                 "without_NK": "Without NK", "without_CD14_Mono": "Without CD14 Mono"}


def robust_table(rb, val):
    lines = [HEADER,
             "\\begin{tabular}{@{}lrrrrr@{}}", "\\toprule",
             "Atlas reference & Patients & Cells & With 100 (\\%) & Cells to target (95\\% CI) & "
             "Saving (95\\% CI) \\\\", "\\midrule"]
    order = ["full"] + [f"patients_{n}" for n in (59, 30, 15, 7, 4)] + ["few_B_mono", "few_T"] + \
        [k for k in rb["variants"] if k.startswith("without_")]
    for k in order:
        v = rb["variants"][k]
        c, s = v["atlas_cells"], v["saving"]
        cells = cells_ci(c)
        pre = "$\\geq$" if s["numerator_relation"] == ">" and s["denominator_relation"] == "=" else ""
        save = (f"{pre}{fac(s['ratio'])} ({fac(s['ci'][0])}--{fac(s['ci'][1])})" if c["relation"] != ">"
                else "neither reached")
        desc = SHORT_VARIANT[k]
        lines.append(f"{desc} & {v['patients']} & {thousands(v['cells'])} & "
                     f"{cell_pct(v['rf'][rb['budgets'].index(100)])} & {cells} & {save} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(lines) + "\n"


def donor_table(rb):
    """From the hashed predictions: each donor's held-out samples."""
    lines = [HEADER,
             "\\begin{tabular}{@{}lrrrrr@{}}", "\\toprule",
             " & & \\multicolumn{2}{c}{Recovered with 100 (\\%)} & & \\\\", "\\cmidrule(lr){3-4}",
             "Donor & Samples & Atlas & Paired only & Atlas cells & Saving \\\\", "\\midrule"]
    i100 = rb["budgets"].index(100)
    for d, r in sorted(rb["per_donor"].items(), key=lambda kv: int(re.sub(r"\D", "", kv[0]) or 0)):
        ac = r["atlas_cells"]
        cells = {">": "$>$", "<=": "$\\leq$"}.get(ac[1], "") + f"{ac[0]:.0f}"
        pre = "$\\geq$" if r["paired_only_cells"][1] == ">" else ""
        save = "neither" if ac[1] == ">" else f"{pre}{fac(r['saving'])}"
        lines.append(f"{d} & {r['samples']} & {cell_pct(r['rf']['atlas'][i100])} & "
                     f"{cell_pct(r['rf']['paired_only'][i100])} & {cells} & {save} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(lines) + "\n"


def pool_table(rb):
    """From the hashed predictions: each processing pool, and the test without it."""
    lines = [HEADER,
             "\\begin{tabular}{@{}lrrrrrr@{}}", "\\toprule",
             " & & \\multicolumn{2}{c}{In the pool} & \\multicolumn{3}{c}{Without the pool} \\\\",
             "\\cmidrule(lr){3-4}\\cmidrule(l){5-7}",
             "Pool & Samples & Atlas cells & Saving & Target (\\%) & Saving & Atlas / own \\\\", "\\midrule"]
    for P, r in rb["per_pool"].items():
        lo = rb["leave_one_pool_out"][P]
        ac = r["atlas_cells"]
        pre = "$\\geq$" if r["paired_only_cells"][1] == ">" else ""
        pre2 = "$\\geq$" if lo["cells"]["paired_only"][1] == ">" else ""
        cells = ("$>$" if ac[1] == ">" else "") + f"{ac[0]:.0f}"
        lines.append(f"{P} & {r['samples']} & {cells} & {pre}{fac(r['saving'])} & {pct(lo['target'])} & "
                     f"{pre2}{fac(lo['saving'])} & {lo['atlas_over_own']:.2f} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(lines) + "\n"


ALT_WORD = {"atlas": "Atlas", "semicca": "Semi", "regression": "Ridge", "paired_only": "Po", "own": "Own",
            "other": "Other", "semicca/pooled": "SemiPooled", "semicca/mapped": "SemiMapped",
            "semicca/percond": "SemiPercond", "ridge_p/pooled": "RidgePPooled", "ridge_p/mapped": "RidgePMapped",
            "ridge_p/percond": "RidgePPercond", "ridge_u/pooled": "RidgeUPooled", "ridge_u/mapped": "RidgeUMapped",
            "ridge_u/percond": "RidgeUPercond"}
TRUTH_WORD = {"p01": "Primary", "p05": "Twentieth", "p001": "Thousandth", "fdr05_unit": "FdrUnit",
              "fdr05_all": "FdrAll"}
WEIGHT_WORD = {"pooled": "Pooled", "unit": "Unit", "type": "Type", "sample": "Sample"}


def cells_text(c):
    return {">": "$>$", "<=": "$\\leq$"}.get(c["relation"], "") + f"{c['cells']:.0f}"


def fac2(v):
    """A ratio of paired cells near one keeps two decimals, so that it and its interval read alike; within 0.005
    of one it keeps three, so that a bound just above or below one is not printed as one."""
    if v != 1 and abs(v - 1) < 0.005:
        return f"{v:.3f}"
    return f"{v:.2f}" if v < 2 else f"{v:.1f}"


def cells_ci(c, top=800):
    """Paired cells needed with its interval; a resampled curve that never reached the target counts as more than
    the largest budget."""
    hi = f"$>${top}" if c["ci"][1] >= top - 0.5 else f"{c['ci'][1]:.0f}"
    return cells_text(c) + (f" ({c['ci'][0]:.0f}--{hi})" if c["relation"] == "=" else "")


def ratio_text(r):
    pre = "at least " if r["numerator_relation"] == ">" and r["denominator_relation"] != ">" else ""
    return pre + fac2(r["ratio"])


def pval_text(p, res):
    """A bootstrap P-value; at the resolution of the resamples, its bound rounded up to one digit."""
    if p <= res * 1.0001:
        e = int(np.floor(np.log10(p)))
        return f"$\\leq{int(np.ceil(p / 10 ** e - 1e-9))}\\times10^{{{e}}}$"
    return f"{p:.2g}"


def sd(v):
    """A difference of fractions in percentage points, signed."""
    return signed(f"{100 * v:.1f}")


def ci_pts(lo, hi):
    """An interval of differences in percentage points: an en dash between non-negative bounds, "to" otherwise."""
    return f"{sd(lo)}--{sd(hi)}" if lo >= 0 else f"{sd(lo)} to {sd(hi)}"


def geq(text):
    return text.replace("at least ", "$\\geq$")


def review_macros(rv, rfz, m):
    """Macros of the analyses asked for in review (validation/posthoc_review/results/review.json): other methods
    given the same atlas, Champollion, and the calibration of the readout."""
    alt = rv["alternatives"]
    b = alt["budgets"]
    for arm, w in ALT_WORD.items():
        c = alt["cells"][arm]
        m[f"AltCells{w}"] = cells_text(c)
        m[f"AltCells{w}Lo"], m[f"AltCells{w}Hi"] = f"{c['ci'][0]:.0f}", f"{c['ci'][1]:.0f}"
        for B, bw in RD_BUDGET.items():
            if B in b:
                m[f"AltRf{w}{bw}"] = pct(alt["rf"][arm][b.index(B)])
                for e in ("E1", "E2", "E3"):
                    m[f"Alt{RD_END[e]}{w}{bw}"] = pct(alt["readout"][e]["values"][arm][b.index(B)])
        m[f"AltRfMax{w}"] = pct(np.nanmax(alt["rf"][arm]))
    for key, w in (("K1_semicca_over_atlas", "Semi"), ("K2_regression_over_atlas", "Ridge"),
                   ("paired_only_over_semicca", "PoOverSemi"), ("paired_only_over_regression", "PoOverRidge"),
                   ("semicca_over_own", "SemiOverOwn"), ("regression_over_own", "RidgeOverOwn"),
                   ("paired_only_over_atlas", "PoOverAtlas")):
        r = alt["ratios"][key]
        m[f"AltRatio{w}"] = ratio_text(r)
        lo_hi = fac2 if r["ratio"] < 2 else fac
        m[f"AltRatio{w}Lo"], m[f"AltRatio{w}Hi"] = lo_hi(r["ci"][0]), lo_hi(r["ci"][1])
    m["AltKOne"], m["AltKTwo"] = ("met" if alt["K1"] else "not met"), ("met" if alt["K2"] else "not met")
    for e in ("E1", "E2", "E3"):
        for fam, w in (("semicca", "Semi"), ("regression", "Ridge"), ("paired_only", "Po")):
            for B, r in alt["readout"][e]["atlas_minus"][fam].items():
                bw = RD_BUDGET.get(int(B))
                if bw:
                    m[f"AltDiff{RD_END[e]}{w}{bw}"] = signed(f"{100 * r['difference']:.1f}")
                    m[f"AltDiff{RD_END[e]}{w}{bw}Lo"] = signed(f"{100 * r['ci'][0]:.1f}")
                    m[f"AltDiff{RD_END[e]}{w}{bw}Hi"] = signed(f"{100 * r['ci'][1]:.1f}")
    m["AltFrozenAt"] = edt(rfz["frozen"])
    ig, rp = rv["integrity"], rv["reproduction"]
    m["AltIntegrity"] = f"${sci(ig['max_abs_P'])}$" if ig["max_abs_P"] > 0 else "0"
    m["AltCompared"] = thousands(ig["compared"])
    m["AltReproduces"] = (f"${sci(rp['readout_max_abs_difference'])}$" if rp["readout_max_abs_difference"] > 0
                          else "0")
    m["AltTarget"] = pct(alt["target"])
    ch = rv.get("champollion")
    if ch:
        cb = ch["budgets"]
        m["AltChampFolds"] = str(ch["folds"])
        m["AltChampFit"] = f"{ch['fit_seconds_mean']:.0f}"
        for a, w in (("champollion", "Champ"), ("atlas_same_draws", "ChampAtlas")):
            m[f"AltCells{w}"] = cells_text(ch["cells"][a])
            lo, hi = ch["cells"][a]["ci"]
            m[f"AltCells{w}Lo"], m[f"AltCells{w}Hi"] = f"{lo:.0f}", f"{hi:.0f}"
            m[f"AltRfMax{w}"] = pct(max(ch["rf"][a]))
            for B, bw in RD_BUDGET.items():
                if B in cb:
                    m[f"AltRf{w}{bw}"] = pct(ch["rf"][a][cb.index(B)])
                    for e in ("E1", "E2"):
                        m[f"Alt{RD_END[e]}{w}{bw}"] = pct(ch["readout"][e][a][cb.index(B)])
        r = ch["champollion_over_atlas"]
        m["AltRatioChamp"] = ratio_text(r)
        lo_hi = fac2 if r["ratio"] < 2 else fac
        m["AltRatioChampLo"], m["AltRatioChampHi"] = lo_hi(r["ci"][0]), lo_hi(r["ci"][1])
        for e in ("E1", "E2"):
            for B, r in ch["readout"][e]["atlas_minus_champollion"].items():
                bw = RD_BUDGET[int(B)]
                m[f"AltDiff{RD_END[e]}Champ{bw}"] = signed(f"{100 * r['difference']:.1f}")
                m[f"AltDiff{RD_END[e]}Champ{bw}Lo"] = signed(f"{100 * r['ci'][0]:.1f}")
                m[f"AltDiff{RD_END[e]}Champ{bw}Hi"] = signed(f"{100 * r['ci'][1]:.1f}")
    # calibration of the readout
    cal = rv["calibration"]
    m["CbGlobalThreshold"] = f"${sci(rv['global_bh_threshold'])}$"
    d100 = {"E1": [], "E2": []}
    for t, tw in TRUTH_WORD.items():
        n = cal["counts"][t]
        m[f"CbN{tw}"] = thousands(n["reproducible"])
        m[f"CbPos{tw}"] = pct(n["positive"] / max(n["reproducible"], 1))
        m[f"CbOverall{tw}"] = pct(cal["majority"][t]["overall_sign"])
        m[f"CbRandomTwo{tw}"] = pct(cal["majority"][t]["random_E2"], 1)
        m[f"CbShareCDEight{tw}"] = pct(n["share_by_type"]["CD8 T"])
        for how, hw in WEIGHT_WORD.items():
            m[f"CbMaj{tw}{hw}"] = pct(cal["majority"][t][how]["unit_majority"])
            for e in ("E1", "E2"):
                for B, r in cal["differences"][t][how][e].items():
                    bw = RD_BUDGET[int(B)]
                    k = f"Cb{RD_END[e]}{tw}{hw}"
                    m[f"{k}Atlas{bw}"], m[f"{k}Po{bw}"] = pct(r["atlas"]), pct(r["paired_only"])
                    m[f"{k}Diff{bw}"] = signed(f"{100 * r['difference']:.1f}")
                    m[f"{k}Diff{bw}Lo"] = signed(f"{100 * r['ci'][0]:.1f}")
                    m[f"{k}Diff{bw}Hi"] = signed(f"{100 * r['ci'][1]:.1f}")
                    if int(B) == 100:
                        d100[e].append((r["difference"], r["ci"][0]))
    for e in ("E1", "E2"):
        if d100[e]:
            m[f"CbDiff{RD_END[e]}Min"] = f"{100 * min(x for x, _ in d100[e]):.1f}"
            m[f"CbDiff{RD_END[e]}Max"] = f"{100 * max(x for x, _ in d100[e]):.1f}"
            m[f"CbDiff{RD_END[e]}LoMin"] = signed(f"{100 * min(lo for _, lo in d100[e]):.1f}")
    for c, cw in TYPE_WORD.items():
        for e in ("E1", "E2"):
            for B, r in cal["by_type"][c][e].items():
                bw = RD_BUDGET[int(B)]
                m[f"CbType{RD_END[e]}{cw}Diff{bw}"] = signed(f"{100 * r['difference']:.1f}")
                m[f"CbType{RD_END[e]}{cw}Diff{bw}Lo"] = signed(f"{100 * r['ci'][0]:.1f}")
                m[f"CbType{RD_END[e]}{cw}Diff{bw}Hi"] = signed(f"{100 * r['ci'][1]:.1f}")
    pl = cal["planned"]
    res = pl["p_resolution"]
    for r in pl["comparisons"]:
        k = f"CbPlan{RD_END[r['endpoint']]}{RD_BUDGET[r['budget']]}"
        m[f"{k}SimLo"], m[f"{k}SimHi"] = signed(f"{100 * r['simultaneous_ci'][0]:.1f}"), \
            signed(f"{100 * r['simultaneous_ci'][1]:.1f}")
        m[f"{k}P"] = pval_text(r["p_one_sided"], res)
    m["CbPlanMaxP"] = pval_text(max(r["p_one_sided"] for r in pl["comparisons"]), res)
    for h, hw in (("B1", "One"), ("B2", "Two"), ("B3", "Three")):
        if h in pl["hypotheses"]:
            m[f"CbHolm{hw}"] = pval_text(pl["hypotheses"][h]["p_holm"], 3 * res)
    m["CbHolmMax"] = pval_text(max(v["p_holm"] for v in pl["hypotheses"].values()), 3 * res)
    m["CbPResolution"] = f"${sci(res)}$"
    m["CbBoot"] = thousands(1 / res - 1)             # the resolution of a P-value from n resamples is 1/(n+1)


def alternatives_table(rv):
    """Other methods given the same paired cells, atlas, panels and tuning information."""
    alt = rv["alternatives"]
    b = alt["budgets"]
    cols = [B for B in (50, 100, 200, 800) if B in b]
    rows = [("atlas", "Estimator", None),
            ("semicca/pooled", "SemiCCA, pooled", None), ("semicca/mapped", "SemiCCA, map", None),
            ("semicca/percond", "SemiCCA, per cell type", None),
            ("semicca", "SemiCCA, best form", "K1_semicca_over_atlas"),
            ("ridge_p/pooled", "Ridge, paired Gram, pooled", None),
            ("ridge_p/mapped", "Ridge, paired Gram, map", None),
            ("ridge_p/percond", "Ridge, paired Gram, per type", None),
            ("ridge_u/pooled", "Ridge, atlas Gram, pooled", None),
            ("ridge_u/mapped", "Ridge, atlas Gram, map", None),
            ("ridge_u/percond", "Ridge, atlas Gram, per type", None),
            ("regression", "Reference regression, best form", "K2_regression_over_atlas"),
            ("paired_only", "Paired cells only", "paired_only_over_atlas")]
    lines = [HEADER,
             "\\begin{tabular}{@{}l" + "r" * len(cols) + "rrrr@{}}", "\\toprule",
             (" & \\multicolumn{%d}{c}{Recovered (\\%%), paired cells} & & & "
              "\\multicolumn{2}{c}{Readout, 100 (\\%%)} \\\\") % len(cols),
             "\\cmidrule(lr){2-%d}\\cmidrule(l){%d-%d}" % (len(cols) + 1, len(cols) + 4, len(cols) + 5),
             "Arm & " + " & ".join(str(B) for B in cols) + " & Paired cells (95\\% CI) & Ratio (95\\% CI) & "
             "E1 & E2 \\\\", "\\midrule"]
    i100 = b.index(100) if 100 in b else None
    for arm, lab, rkey in rows:
        c = alt["cells"][arm]
        cells = cells_ci(c)
        if rkey:
            r = alt["ratios"][rkey]
            f_ = fac2 if r["ratio"] < 2 else fac
            rel = f"{geq(ratio_text(r))} ({f_(r['ci'][0])}--{f_(r['ci'][1])})"
        elif arm == "atlas":
            rel = "1"
        else:
            rel = ""
        e1 = cell_pct(alt["readout"]["E1"]["values"][arm][i100]) if i100 is not None else ""
        e2 = cell_pct(alt["readout"]["E2"]["values"][arm][i100]) if i100 is not None else ""
        lines.append(f"{lab} & " + " & ".join(cell_pct(alt["rf"][arm][b.index(B)]) for B in cols)
                     + f" & {cells} & {rel} & {e1} & {e2} \\\\")
    ch = rv.get("champollion")
    if ch:
        cb = ch["budgets"]
        lines += ["\\midrule",
                  "\\multicolumn{%d}{@{}l}{\\textit{First draw of every fold only}} \\\\" % (len(cols) + 5)]
        for a, lab in (("champollion", "Champollion"), ("atlas_same_draws", "Estimator, same draws")):
            c = ch["cells"][a]
            cells = cells_ci(c)
            if a == "champollion":
                r = ch["champollion_over_atlas"]
                f_ = fac2 if r["ratio"] < 2 else fac
                rel = f"{geq(ratio_text(r))} ({f_(r['ci'][0])}--{f_(r['ci'][1])})"
            else:
                rel = "1"
            j = cb.index(100) if 100 in cb else None
            e1 = cell_pct(ch["readout"]["E1"][a][j]) if j is not None else ""
            e2 = cell_pct(ch["readout"]["E2"][a][j]) if j is not None else ""
            lines.append(f"{lab} & " + " & ".join(cell_pct(ch["rf"][a][cb.index(B)]) if B in cb else "" for B in cols)
                         + f" & {cells} & {rel} & {e1} & {e2} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(lines) + "\n"


TRUTH_LABEL = {"p01": "$P<0.01$ (readout)", "p05": "$P<0.05$", "p001": "$P<0.001$",
               "fdr05_unit": "FDR 5\\%, per unit", "fdr05_all": "FDR 5\\%, all units"}
WEIGHT_LABEL = {"pooled": "Pooled (readout)", "unit": "Units alike", "type": "Cell types alike",
                "sample": "Samples alike"}


def calibration_table(rv):
    """The readout at 100 paired cells under other truth sets, weightings, and per cell type."""
    cal = rv["calibration"]

    def cells(r):
        return (f"{cell_pct(r['atlas'])} & {cell_pct(r['paired_only'])} & "
                f"{sd(r['difference'])} ({ci_pts(*r['ci'])})")

    lines = [HEADER,
             "\\begin{tabular}{@{}lrrrrrrrr@{}}", "\\toprule",
             " & & & \\multicolumn{3}{c}{Direction (E1, \\%)} & "
             "\\multicolumn{3}{c}{Top 100 reproducible (E2, \\%)} \\\\",
             "\\cmidrule(lr){4-6}\\cmidrule(l){7-9}",
             " & Associations & Majority & Atlas & Paired & Difference (95\\% CI) & Atlas & Paired & "
             "Difference (95\\% CI) \\\\",
             "\\midrule", "\\multicolumn{9}{@{}l}{\\textit{Truth set (pooled)}} \\\\"]
    for t, lab in TRUTH_LABEL.items():
        d = cal["differences"][t]["pooled"]
        if "100" not in d["E1"]:
            continue
        lines.append(f"{lab} & {thousands(cal['counts'][t]['reproducible'])} & "
                     f"{cell_pct(cal['majority'][t]['pooled']['unit_majority'])} & {cells(d['E1']['100'])} & "
                     f"{cells(d['E2']['100'])} \\\\")
    lines += ["\\midrule", "\\multicolumn{9}{@{}l}{\\textit{Weighting (readout's truth set)}} \\\\"]
    for how, lab in WEIGHT_LABEL.items():
        d = cal["differences"]["p01"][how]
        if "100" not in d["E1"]:
            continue
        lines.append(f"{lab} & & {cell_pct(cal['majority']['p01'][how]['unit_majority'])} & "
                     f"{cells(d['E1']['100'])} & {cells(d['E2']['100'])} \\\\")
    lines += ["\\midrule", "\\multicolumn{9}{@{}l}{\\textit{Cell type (readout's truth set)}} \\\\"]
    for c, rec in cal["by_type"].items():
        if "100" not in rec["E1"]:
            continue
        n = cal["counts"]["p01"]["by_type"][c]
        lines.append(f"{c} & {thousands(n)} & & {cells(rec['E1']['100'])} & {cells(rec['E2']['100'])} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(lines) + "\n"


def multiplicity_table(rv):
    """The eight planned comparisons of the readout: intervals, simultaneous intervals, P-values, Holm."""
    pl = rv["calibration"]["planned"]
    res = pl["p_resolution"]
    name = {"E1": "Direction", "E2": "Top 100 reproducible", "E3": "Cognate pairs, recovered"}
    lines = [HEADER,
             "\\begin{tabular}{@{}llrrrrr@{}}", "\\toprule",
             "Hypothesis & Endpoint & Paired cells & Difference & 95\\% CI & Simultaneous CI & One-sided $P$ \\\\",
             "\\midrule"]
    for r in pl["comparisons"]:
        lines.append(f"{r['hypothesis']} & {name[r['endpoint']]} & {r['budget']} & {sd(r['difference'])} & "
                     f"{sd(r['ci95'][0])} to {sd(r['ci95'][1])} & "
                     f"{sd(r['simultaneous_ci'][0])} to {sd(r['simultaneous_ci'][1])} & "
                     f"{pval_text(r['p_one_sided'], res)} \\\\")
    lines += ["\\midrule"]
    for h, v in pl["hypotheses"].items():
        lines.append(f"{h} & \\multicolumn{{5}}{{l}}{{Intersection--union $P$ (largest over its budgets); "
                     "Holm-adjusted over B1--B3} & "
                     f"{pval_text(v['p_holm'], 3 * res)} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(lines) + "\n"


TP = {"baseline": "b", "followup": "f"}


def allocation_macros(al, m):
    """Donor separation of the validation's folds (validation/results_posthoc/allocation.json)."""
    assert al["donor_disjoint"] and all(v for k, v in al["checks"].items() if k != "atlas")
    m["AlNSamples"] = str(len(al["samples"]))
    m["AlNDonors"] = str(len(al["donors"]))
    m["AlNPools"] = NUM.get(len(al["pools"]), str(len(al["pools"])))
    two = sum(1 for d in al["donors"] if sum(1 for s in al["samples"].values() if s["donor"] == d) == 2)
    m["AlNTwoTimepoints"] = str(two)


def allocation_table(al):
    """Every fold of the validation: held-out sample, paired samples and references, by donor."""
    lines = [HEADER,
             "\\begin{tabular}{@{}lllrrr@{}}", "\\toprule",
             " & & & \\multicolumn{2}{c}{Other-pool reference} & Own-sample \\\\", "\\cmidrule(lr){4-5}",
             "Pool & Held-out sample & Paired samples & Samples (donors) & Cells & reference cells \\\\"]
    last = None
    for f in al["folds"]:
        first = f["pool"] != last
        if first:
            lines.append("\\midrule")
        last = f["pool"]
        paired = ", ".join(f"{p['donor']} ({TP[p['timepoint']]})" for p in f["paired"])
        ref = (f"{f['other']['samples']} ({f['other']['donors']}) & {thousands(f['other']['cells'])}" if first
               else " & ")
        lines.append(f"{f['pool'] if first else ''} & {f['donor']} ({TP[f['timepoint']]}) & {paired} & {ref} & "
                     f"{thousands(f['own_reference_cells'])} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(lines) + "\n"


REGRESSION_STYLE = "color=ridgecol!70!black,line width=1pt,mark=pentagon*,mark size=1.5pt"


def readout_panel(rd, endpoint, at, name, title, ylabel, ymin, ymax, ticks, baseline=None, rv=None):
    """Readout of the validation (validation/readout): an endpoint against paired cells, per arm; with rv, also
    reference regression given the atlas (validation/posthoc_review), the best of its forms at each budget."""
    b = rd["budgets"]
    xt = ",".join(str(x) for x in b if x != 150)
    lines = [axis_start(at, name, ".3", "3.2cm", LOG_X),
             f" xmin=20,xmax=1000,ymin={ymin},ymax={ymax},xtick={{{xt}}},xticklabels={{{xt}}},ytick={{{ticks}}},",
             f" xlabel={{Paired cells}},ylabel={{{ylabel}}},",
             f" title={{{title}}},", COMMON + "]"]
    if baseline is not None:
        lines.append(f"\\draw[dashed,black!45] (axis cs:20,{baseline:.3f}) -- (axis cs:1000,{baseline:.3f});")
    for arm, _, style in READOUT_ARMS:
        lines += sa.curve_lines(b, rd["values"][endpoint][arm], style)
    if rv is not None:
        alt = rv["alternatives"]["readout"][endpoint]["values"]["regression"]
        assert rv["budgets"] == b
        lines += sa.curve_lines(b, alt, REGRESSION_STYLE)
    lines.append("\\end{axis}")
    return lines


def refsize_panel(rb, val, at, name, title):
    """Paired cells the atlas arm needs to reach the test's primary target, against the number of atlas patients."""
    pts = [(v["patients"], v["atlas_cells"]) for k, v in rb["variants"].items()
           if k.startswith("patients_") or k == "full"]
    pts.sort()
    own = val["targets"]["0.5"]["cells"]["own"]["cells"]
    xt = ",".join(str(p) for p, _ in pts)
    lines = [axis_start(at, name, ".3", "3.2cm", LOG_X),
             f" ymode=log,log basis y=2,xmin=3,xmax=160,ymin=50,ymax=1600,xtick={{{xt}}},xticklabels={{{xt}}},",
             " ytick={50,100,200,400,800,1600},yticklabels={50,100,200,400,800,$>$800},",
             " xlabel={Atlas patients in the reference},ylabel={Paired cells to the target},",
             f" title={{{title}}},", COMMON + "]",
             "\\draw[color=pairedcol,line width=.8pt,->] (axis cs:3,800) -- (axis cs:3,1400);",
             "\\draw[color=pairedcol,dashed,line width=.7pt] (axis cs:3,800) -- (axis cs:160,800);",
             f"\\draw[color=sitecol,dashed,line width=.7pt] (axis cs:3,{own:.1f}) -- (axis cs:160,{own:.1f});",
             "\\node[font=\\sffamily\\scriptsize,color=pairedcol,anchor=south east] at (axis cs:155,800) "
             "{paired cells only};",
             f"\\node[font=\\sffamily\\scriptsize,color=sitecol,anchor=north west] at (axis cs:3.2,{own:.1f}) "
             "{own samples};"]
    for p, c in pts:
        lo, hi = c["ci"]
        if c["relation"] == ">":
            lines.append(f"\\draw[->,color=propcol,line width=.8pt] (axis cs:{p},800) -- (axis cs:{p},1400);")
        else:
            lines.append(f"\\draw[color=propcol,line width=.8pt] (axis cs:{p},{lo:.1f}) -- "
                         f"(axis cs:{p},{min(hi, 1400):.1f});")
    lines.append("\\addplot[color=propcol,line width=1.2pt,mark=*,mark size=1.6pt] coordinates {"
                 + " ".join(f"({p},{c['cells']:.1f})" for p, c in pts) + "};")
    for p, c in pts:
        if c["relation"] == ">":
            lines.append(f"\\addplot[only marks,mark=o,mark size=1.8pt,color=propcol,fill=white] "
                         f"coordinates {{ ({p},800) }};")
    lines.append("\\end{axis}")
    return lines


PO_METHODS = ("js", "scose", "fcose", "lowrank")      # the paired-only methods, each pooled and per condition
ALT_FIG_ARMS = [("semicca", "SemiCCA, atlas", "color=semicol,line width=.9pt"),
                ("regression", "Reference regression, atlas", "color=ridgecol,line width=.9pt"),
                ("champollion", "Champollion, atlas (1 draw)", "color=meancol,line width=.9pt")]


def atlas_figure(val, rd, rv, vr, R):
    """Fig. 2: the validation test, the other methods given the same paired cells and atlas, the biological readout
    with reference regression, its differences per donor and the named relationships."""
    lines = list(PICTURE)
    lines += curves_panel(val, VAL_FIG_ARMS, "", "a", "\\textbf{a}\\enspace Blood study, atlas of another study", 60,
                          "3.2cm")
    cells = dict(val["targets"]["0.5"]["cells"])
    alt = rv["alternatives"]
    cells["semicca"], cells["regression"] = alt["cells"]["semicca"], alt["cells"]["regression"]
    cells["champollion"] = rv["champollion"]["cells"]["champollion"]
    b_arms = VAL_FIG_ARMS[:-1] + ALT_FIG_ARMS + VAL_FIG_ARMS[-1:]
    lines += cells_panel({"targets": {"0.5": {"cells": cells}}}, b_arms,
                         "at={(a.outer north east)},anchor=outer north west,xshift=.4cm,", "b",
                         "\\textbf{b}\\enspace Paired cells needed", "3.2cm")
    lines += ["\\path (a.outer south west) -- (b.outer south east) coordinate[pos=.5] (legab);"]
    legend = {a[0]: a for a in offscale(VAL_FIG_ARMS, val["budgets"], val["rf"])}
    # two rows whose columns pair entries of similar length: the atlas arms and paired cells only, then the rest
    lines += legend_below("legab", [legend[k] for k in ("atlas", "atlas_dfcentre", "paired_only", "other",
                                                        "own_poolstd", "own")], 3, sep=4)
    lines += readout_panel(rd, "E1", "at={(a.outer south west)},anchor=outer north west,yshift=-1.3cm,", "c",
                           "\\textbf{c}\\enspace Direction of reproducible associations",
                           "Correct direction (\\%)", 45, 100, "50,60,70,80,90,100", baseline=50, rv=rv)
    lines += readout_panel(rd, "E2", "at={(c.outer north east)},anchor=outer north west,xshift=.4cm,", "d",
                           "\\textbf{d}\\enspace Top 100 pairs per cell type", "Reproducible (\\%)", 0, 80,
                           "0,20,40,60,80", baseline=100 * rd["random_E2"], rv=rv)
    lines += ["\\path (c.outer south west) -- (d.outer south east) coordinate[pos=.5] (legcd);"]
    lines += legend_below("legcd", [a for a in READOUT_ARMS if a[0] != "paired_only"]
                          + [("regression", "Reference regression, atlas", REGRESSION_STYLE)]
                          + [a for a in READOUT_ARMS if a[0] == "paired_only"], 3)
    arms_all = [a for a in vr["arms"] if a not in ("paired_only", "regression")]   # the records' stored order
    assert len(arms_all) == R[0]["score"].shape[2]
    po = [a for a in arms_all if a.split("/")[0] in PO_METHODS]
    reg = [a for a in arms_all if a.startswith("ridge_")]
    dr, _, _ = ra.donor_readout(R, arms_all, po, reg, 100, 1)
    lines += ra.donor_panel(dr, "at={(c.outer south west)},anchor=outer north west,yshift=-1.05cm,", "e",
                            "\\textbf{e}\\enspace Direction, per donor", axis_start, COMMON_X)
    lines += ra.relationship_panel(ra.relationship_values(R, vr, 100),
                                   "at={(e.outer north east)},anchor=outer north west,xshift=.4cm,", "f",
                                   "\\textbf{f}\\enspace Named relationships", axis_start, COMMON_X)
    lines += ra.legend_rows("f.outer south east", [("only marks,mark=diamond*,mark size=2.2pt,color=black", "Held out")]
                            + [(f"only marks,{st}", lab) for _, lab, st in ra.REL_ARMS], 4, side="north east")
    lines.append("\\end{tikzpicture}")
    return "\n".join(lines) + "\n"


def reference_figure(vr, rb, val, mp):
    """Fig. 4: what the reference contributes: its axes and its condition maps at every budget in the validation
    test, reweighting of atlases with a skewed mix of cell types, the atlas's size, and RNA from nuclei in the
    bone-marrow test."""
    lines = list(PICTURE)
    lines += ra.axes_panel(vr, "", "a", "\\textbf{a}\\enspace Axes and maps, validation test", axis_start, COMMON,
                           LOG_X, sa.curve_lines)
    lines += ra.composition_cells_panel(vr, "at={(a.outer north east)},anchor=outer north west,xshift=.4cm,", "b",
                                        "\\textbf{b}\\enspace Mix of cell types in the atlas", axis_start, COMMON_X,
                                        LOG_X)
    lines += ra.legend_rows("a.outer south west", [(st, lab) for _, lab, st in ra.AXES_ARMS], 2,
                            side="north west")
    lines += ra.legend_rows("b.outer south east", [(f"only marks,{st}", lab) for _, lab, st, _ in ra.COMP_KINDS], 2,
                            side="north east")
    lines += refsize_panel(rb, val, "at={(a.outer south west)},anchor=outer north west,yshift=-1.1cm,", "c",
                           "\\textbf{c}\\enspace Size of the atlas")
    lines += ra.bm_map_panel(mp, "at={(c.outer north east)},anchor=outer north west,xshift=.4cm,", "d",
                             "\\textbf{d}\\enspace Bone marrow, RNA from nuclei", axis_start, COMMON, LOG_X,
                             sa.curve_lines)
    lines += ra.legend_rows("d.outer south east", [(st, lab) for _, lab, st in ra.BM_MAP_ARMS], 2,
                            side="north east")
    lines.append("\\end{tikzpicture}")
    return "\n".join(lines) + "\n"


TRANSFER_ARMS = DEP_ARMS[:3] + [
    ("c_proposed_other", "Other sites, contrasts (after scoring)",
     "color=propcol,line width=1.1pt,densely dashed,mark=*,mark size=1.4pt,mark options={solid,fill=white}"),
] + DEP_ARMS[3:]


def transfer_figure(dep, con, fly, cal):
    """Fig. 4: the bone-marrow test (prespecified arms and the contrast reanalysis of the other-site arm), the
    cross-animal fly analysis and the calibration of the noise estimate after contrasts."""
    assert dep["budgets"] == con["budgets"]
    assert abs(dep["targets"]["0.5"]["target"] - con["targets"]["0.5"]["target"]) < 1e-12
    res = {"budgets": dep["budgets"], "rf": dict(dep["rf"], c_proposed_other=con["rf"]["c_proposed_other"]),
           "targets": {"0.5": {"target": dep["targets"]["0.5"]["target"],
                               "cells": dict(dep["targets"]["0.5"]["cells"],
                                             c_proposed_other=con["targets"]["0.5"]["cells"]["c_proposed_other"])}}}
    lines = list(PICTURE)
    lines += curves_panel(res, TRANSFER_ARMS, "", "a", "\\textbf{a}\\enspace Bone marrow, four sites", 40)
    lines += cells_panel(res, TRANSFER_ARMS, "at={(a.outer north east)},anchor=outer north west,xshift=.4cm,", "b",
                         "\\textbf{b}\\enspace Paired cells needed")
    lines += ["\\path (a.outer south west) -- (b.outer south east) coordinate[pos=.5] (legab);"]
    lines += legend_below("legab", offscale(TRANSFER_ARMS, res["budgets"], res["rf"]), 2)
    lines += fly_panel(fly, "at={(a.outer south west)},anchor=outer north west,yshift=-1.95cm,", "c",
                       "\\textbf{c}\\enspace Fly wiring, other animals")
    lines += ra.legend_rows("c.outer south west", [(arm[-1], arm[1]) for arm in offscale(FLY_ARMS, fly["budgets"],
                                                                                        fly["rf"])], 1,
                            side="north west")
    lines += ra.noise_panel(cal, "at={(c.outer north east)},anchor=outer north west,xshift=.4cm,", "d",
                            "\\textbf{d}\\enspace Noise estimate after contrasts", axis_start, COMMON, LOG_X)
    lines += ra.legend_rows("d.outer south east", [
        ("color=propcol,line width=1.1pt,mark=*,mark size=1.4pt", "Implemented (contrasts)"),
        ("color=semicol,line width=.8pt,mark=square*,mark size=1.2pt", "Jackknife"),
        ("color=meancol,line width=.8pt,mark=x,mark size=1.8pt", "Own-mean centring"),
        ("color=black,line width=.8pt", "Validation"), ("color=black,line width=.8pt,densely dashed", "Bone marrow")],
        1, side="north east")
    lines += ["\\end{tikzpicture}"]
    return "\n".join(lines) + "\n"


def contrast_table(con):
    b = con["budgets"]
    p = con["targets"]["0.5"]["cells"]
    rows = [("c_paired_only", "Paired cells only"), ("c_proposed_same", "Own site"),
            ("c_proposed_other", "Other sites"), ("c_proposed_assay", "Other sites, RNA from nuclei")]
    lines = [HEADER,
             "\\begin{tabular}{@{}l" + "r" * len(b) + "r@{}}", "\\toprule",
             " & \\multicolumn{%d}{c}{Recovered (\\%%) with paired cells} & Paired cells \\\\" % len(b),
             "\\cmidrule(lr){2-%d}" % (len(b) + 1),
             "Unpaired cells & " + " & ".join(str(x) for x in b) + " & to the target \\\\", "\\midrule"]
    for arm, lab in rows:
        c = p[arm]
        cells = f"$>${c['cells']:.0f}" if c["relation"] == ">" else f"{c['cells']:.0f}"
        lines.append(f"{lab} & " + " & ".join(cell_pct(v) for v in con["rf"][arm]) + f" & {cells} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(lines) + "\n"


# ------------------------------------------------------------------ Fig. 6

def blood_panel(cs, at, name, title):
    arms = [("pf_means", "No pairs: population averages"),
            ("paired_closed_form", "Paired cells, other donors"), ("recipient_benchmark", "Own paired cells")]
    groups = [("total", "All cells"), ("within_l1", "Within 8 cell types")]
    h = cs["hao"]
    n = len(arms)
    lines = [axis_start(at, name, ".25", "3.6cm", "xmin=0,xmax=1.65,"),
             f" ymin=.4,ymax={n + .6},xtick={{0,.4,.8,1.2,1.6}},ytick={{{','.join(str(i) for i in range(1, n + 1))}}},",
             " yticklabels={" + ",".join("{" + a[1] + "}" for a in reversed(arms)) + "},",
             " xlabel={Relative error},",
             f" title={{{title}}},", COMMON_X + "]",
             f"\\draw[dashed,black!45] (axis cs:1,.4) -- (axis cs:1,{n + .6});"]
    for g, (grp, _), (style, dy) in zip(range(2), groups, (("only marks,mark=*,mark size=1.8pt,color=propcol", .15),
                                                         ("only marks,mark=o,mark size=1.8pt,color=meancol", -.15))):
        pts = []
        for y, (arm, _) in enumerate(reversed(arms), start=1):
            vals = h["per_donor_E"][grp][arm]
            if grp == "total":
                xs = np.linspace(y + dy - .06, y + dy + .06, len(vals))
                lines.append("\\addplot[only marks,mark=*,mark size=.6pt,color=propcol!45] coordinates { "
                             + " ".join(f"({min(v, 1.6):.4f},{yy:.3f})" for v, yy in zip(vals, xs)) + " };")
            pts.append(f"({min(h['mean_E'][grp][arm], 1.6):.4f},{y + dy:.2f})")
        lines.append(f"\\addplot[{style}] coordinates {{ {' '.join(pts)} }};")
    lines.append("\\end{axis}")
    return lines


def ifn_panel(prog, ev, at, name, title):
    h = prog["heldout"]
    iv = h["intervals"]
    whole = ev["heldout"]["estimates"]
    arms = [("pf_within_measured", "No pairs: perturbations"), ("paired_closed_form", "Paired cells, other knockouts"),
            ("benchmark", "Own paired cells")]
    lo_clip = -50
    n = len(arms)
    lines = [axis_start(at, name, ".18", "3.6cm", f"xmin={lo_clip},xmax=105,"),
             f" ymin=.4,ymax={n + .6},xtick={{-50,-25,0,25,50,75,100}},xticklabels={{$-$50,,0,,50,,100}},",
             f" ytick={{{','.join(str(i) for i in range(1, n + 1))}}},",
             " yticklabels={" + ",".join("{" + a[1] + "}" for a in reversed(arms)) + "},",
             " xlabel={Dependence recovered (\\%)},",
             f" title={{{title}}},", COMMON_X + "]",
             f"\\draw[dashed,black!45] (axis cs:0,.4) -- (axis cs:0,{n + .6});"]
    ifn, comp, allp = [], [], []
    for y, (k, _) in enumerate(reversed(arms), start=1):
        v = h["ifn"]["rf"][k]
        key = f"ifn/rf/{k}"
        if key in iv:
            lo, hi = iv[key]["ci"]
            lines.append(f"\\draw[propcol,line width=.8pt] (axis cs:{max(100 * lo, lo_clip):.2f},{y + .22}) -- "
                         f"(axis cs:{100 * hi:.2f},{y + .22});")
        ifn.append(f"({max(100 * v, lo_clip):.2f},{y + .22})")
        comp.append(f"({max(100 * h['complement']['rf'][k], lo_clip):.2f},{y})")
        lo, hi = whole[k]["ci"]
        lines.append(f"\\draw[black,line width=.8pt] (axis cs:{max(100 * lo, lo_clip):.2f},{y - .22}) -- "
                     f"(axis cs:{100 * hi:.2f},{y - .22});")
        allp.append(f"({max(100 * whole[k]['value'], lo_clip):.2f},{y - .22})")
    lines += ["\\addplot[only marks,mark=*,mark size=1.7pt,color=propcol] coordinates { " + " ".join(ifn) + " };",
              "\\addplot[only marks,mark=o,mark size=1.7pt,color=pairedcol] coordinates { " + " ".join(comp) + " };",
              "\\addplot[only marks,mark=diamond*,mark size=2pt,color=black] coordinates { " + " ".join(allp) + " };",
              "\\end{axis}"]
    return lines


def removal_panel(des, at, name, title):
    all_kept = 100 * des["none"]["ifn"]
    lines = [axis_start(at, name, ".2", "3.6cm"),
             " xmin=.5,xmax=3.5,ymin=-5,ymax=65,xtick={1,2,3},xticklabels={5,10,20},ytick={0,20,40,60},",
             " xlabel={Perturbations removed},ylabel={Interferon response (\\%)},",
             f" title={{{title}}},", COMMON + "]",
             f"\\draw[dashed,black!45] (axis cs:.5,{all_kept:.2f}) -- (axis cs:3.5,{all_kept:.2f});"]
    rnd, strg, expo = [], [], []
    for i, k in enumerate((5, 10, 20), start=1):
        a = des["ablation"][str(k)]["ifn"]
        xs = np.linspace(i - .22, i + .22, len(a["random_values"]))
        rnd += [f"({x:.3f},{100 * v:.2f})" for x, v in zip(xs, a["random_values"])]
        strg.append(f"({i + .12},{100 * a['remove_strength']:.2f})")
        expo.append(f"({i - .12},{100 * a['remove_exposure']:.2f})")
    lines += ["\\addplot[only marks,mark=*,mark size=.8pt,color=pairedcol!55] coordinates { " + " ".join(rnd) + " };",
              "\\addplot[only marks,mark=triangle*,mark size=2.1pt,color=propcol] coordinates { "
              + " ".join(expo) + " };",
              "\\addplot[only marks,mark=square*,mark size=1.9pt,color=meancol] coordinates { "
              + " ".join(strg) + " };",
              "\\end{axis}"]
    return lines


def replication_panel(rep, at, name, title):
    """The prespecified replication in the monocyte screen: all genes and proteins, and the interferon block."""
    t = rep["test"]
    s, iv = t["summary"], t["intervals"]
    rows = [("pf_within_measured", "No pairs: perturbations", "primary", "ifn_primary"),
            ("pseudo", "Control: pseudo-populations", None, None),
            ("derange", "Control: shuffled pairs", None, None),
            ("paired_closed_form", "Paired cells, other knockouts", "paired", "ifn_paired")]
    lo_clip = -300
    n = len(rows)
    lines = [axis_start(at, name, ".2", "3.6cm", f"xmin={lo_clip},xmax=105,"),
             f" ymin=.4,ymax={n + .6},xtick={{-300,-200,-100,0,100}},xticklabels={{$-$300,$-$200,$-$100,0,100}},",
             f" ytick={{{','.join(str(i) for i in range(1, n + 1))}}},",
             " yticklabels={" + ",".join("{" + r[1] + "}" for r in reversed(rows)) + "},",
             " xlabel={Dependence recovered (\\%)},",
             f" title={{{title}}},", COMMON_X + "]",
             f"\\draw[dashed,black!45] (axis cs:0,.4) -- (axis cs:0,{n + .6});"]
    ifn, allp = [], []
    for y, (k, _, ka, ki) in enumerate(reversed(rows), start=1):
        allp.append(f"({max(100 * s['all'][k], lo_clip):.2f},{y - .15})")
        ifn.append(f"({max(100 * s['ifn'][k], lo_clip):.2f},{y + .15})")
        for key, dy, col in ((ka, -.15, "black"), (ki, .15, "propcol")):
            if key and key in iv:
                lo, hi = iv[key]["ci"]
                lines.append(f"\\draw[{col},line width=.8pt] (axis cs:{max(100 * lo, lo_clip):.2f},{y + dy}) -- "
                             f"(axis cs:{100 * hi:.2f},{y + dy});")
    lines += ["\\addplot[only marks,mark=*,mark size=1.7pt,color=propcol] coordinates { " + " ".join(ifn) + " };",
              "\\addplot[only marks,mark=diamond*,mark size=2pt,color=black] coordinates { " + " ".join(allp) + " };",
              "\\end{axis}"]
    return lines


def pairfree_figure(cs, prog, des, ev, rep):
    lines = list(PICTURE)
    lines += blood_panel(cs, "", "a", "\\textbf{a}\\enspace Blood, second cohort")
    lines += ["\\begin{axis}[hide axis,scale only axis,width=1pt,height=1pt,xmin=0,xmax=1,ymin=0,ymax=1,"
              "at={(a.outer south)},anchor=north,yshift=-2pt,legend style={draw=none,font=\\sffamily\\scriptsize,"
              "at={(0.5,0.5)},anchor=north,legend columns=2,column sep=6pt,cells={anchor=west}}]",
              "\\addlegendimage{only marks,mark=*,mark size=1.8pt,color=propcol}", "\\addlegendentry{All cells}",
              "\\addlegendimage{only marks,mark=o,mark size=1.8pt,color=meancol}",
              "\\addlegendentry{Within cell types}", "\\end{axis}"]
    lines += ifn_panel(prog, ev, "at={(a.outer north east)},anchor=outer north west,xshift=.1cm,", "b",
                       "\\textbf{b}\\enspace Melanoma screen")
    lines += ["\\begin{axis}[hide axis,scale only axis,width=1pt,height=1pt,xmin=0,xmax=1,ymin=0,ymax=1,"
              "at={(b.outer south east)},anchor=north east,yshift=-2pt,legend style={draw=none,"
              "font=\\sffamily\\scriptsize,at={(1,0.5)},anchor=north east,legend columns=3,column sep=4pt,"
              "cells={anchor=west}}]",
              "\\addlegendimage{only marks,mark=*,mark size=1.7pt,color=propcol}",
              "\\addlegendentry{Interferon response}",
              "\\addlegendimage{only marks,mark=o,mark size=1.7pt,color=pairedcol}",
              "\\addlegendentry{Other}",
              "\\addlegendimage{only marks,mark=diamond*,mark size=2pt,color=black}",
              "\\addlegendentry{All genes and proteins}", "\\end{axis}"]
    lines += removal_panel(des, "at={(a.outer south west)},anchor=outer north west,yshift=-1.3cm,", "c",
                           "\\textbf{c}\\enspace Removing training perturbations")
    lines += ["\\begin{axis}[hide axis,scale only axis,width=1pt,height=1pt,xmin=0,xmax=1,ymin=0,ymax=1,"
              "at={(c.outer south west)},anchor=north west,yshift=-2pt,legend style={draw=none,"
              "font=\\sffamily\\scriptsize,at={(0,0.5)},anchor=north west,legend columns=3,column sep=4pt,"
              "cells={anchor=west}}]",
              "\\addlegendimage{only marks,mark=triangle*,mark size=2.1pt,color=propcol}",
              "\\addlegendentry{Exposure (planned)}",
              "\\addlegendimage{only marks,mark=square*,mark size=1.9pt,color=meancol}",
              "\\addlegendentry{Effect strength}",
              "\\addlegendimage{only marks,mark=*,mark size=1pt,color=pairedcol!55}",
              "\\addlegendentry{Random}", "\\end{axis}"]
    lines += replication_panel(rep, "at={(c.outer north east)},anchor=outer north west,xshift=.1cm,", "d",
                               "\\textbf{d}\\enspace Monocyte screen (replication)")
    lines.append("\\end{tikzpicture}")
    return "\n".join(lines) + "\n"


# ------------------------------------------------------------------ main

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=str(HERE.parent.parent / "revision" / "source"))
    out = Path(ap.parse_args().out)

    # result records
    summ = load(HERE / "results" / "savings_summary.json")
    dep = load(DEP / "results" / "summary.json")
    dinfo = load(DEP / "results" / "predictions_info.json")
    post = {k: load(DEP / "results_posthoc" / f"{k}.json")
            for k in ("fly_contrasts", "assay_structure", "contrasts_summary", "map_by_source", "law_by_source",
                      "fly_own_standardization", "population_sizes", "calibration")}
    fly, con, sizes, cal_bm = (post["fly_contrasts"], post["contrasts_summary"], post["population_sizes"],
                               post["calibration"])
    val = load(VAL / "results" / "summary.json")
    rd = load(VAL / "readout" / "results" / "readout.json")
    rb = load(VAL / "results_posthoc" / "robustness.json")
    al = load(VAL / "results_posthoc" / "allocation.json")
    rv = load(VAL / "posthoc_review" / "results" / "review.json")
    sf, sp = sa.load(sa.R / "summary_frangieh.json"), sa.load(sa.R / "summary_papalexi.json")
    ext = sa.load(sa.EXT / "overcite_plan_estimator.json")
    cs = load(EXT / "cross_study" / "results" / "summary.json")
    prog = load(EXT / "perturbation" / "results" / "programs.json")
    des = load(EXT / "perturbation" / "results" / "design.json")
    pev = load(EXT / "perturbation" / "results" / "evaluation.json")
    rep = load(EXT / "perturbation_replication" / "results" / "evaluation.json")

    # the checks and analyses added in revision (../checks, ../second_review)
    REV2 = EXT / "second_review" / "results"
    draws = ra.draw_records()
    cal = load(REV2 / "noise_calibration.json")
    vr = load(REV2 / "validation_review.json")
    R = ra.review_folds()
    rc = load(REV2 / "readout_checks.json")
    ab = load(REV2 / "atlas_bootstrap.json")
    law2 = load(REV2 / "law_review.json")
    ps = ra.pilot_summary(ra.pilot_records())
    br = load(REV2 / "benchmark_review.json")
    pa = _load_module("predictability_assets", EXT / "predictability" / "make_assets.py")

    # macros
    m = macros(summ, dep, dinfo, fly, post["assay_structure"], edt(load(DEP / "results" / "freeze.json")["frozen"]),
               con, post["map_by_source"], post["law_by_source"], post["fly_own_standardization"], sizes)
    val_macros(val, load(VAL / "results" / "freeze.json"), load(VAL / "results" / "manifest.json"), cal_bm,
               load(EXT / "predictability" / "results" / "rows.json"), m)
    sensitivity_macros(val, con, m)
    readout_macros(rd, load(VAL / "readout" / "results" / "freeze.json"), m)
    robust_macros(rb, val, m)
    composition_macros(load(VAL / "results_posthoc" / "composition_map.json"), m)
    allocation_macros(al, m)
    review_macros(rv, load(VAL / "posthoc_review" / "results" / "freeze.json"), m)
    m["RvFrozenAt"] = edt(load(REV2 / "freeze.json")["frozen"])
    ra.draw_macros(draws, m)
    ra.noise_macros(cal, m)
    ra.validation_macros(vr, m)
    ra.relationship_macros(vr, m, vals=ra.relationship_values(R, vr, 100))
    ra.readout_check_macros(rc, vr, m)
    ra.onedraw_macros(vr, ab, m)
    ra.law_macros(law2["inference"], m)
    ra.pilot_macros(ps, m)
    ra.fixed_macros(br, m)
    arms_all = [a for a in vr["arms"] if a not in ("paired_only", "regression")]
    ra.donor_macros(ra.donor_readout(R, arms_all, [a for a in arms_all if a.split("/")[0] in PO_METHODS],
                                     [a for a in arms_all if a.startswith("ridge_")], 100, 1)[0], m)
    write_macros(out / "synth_macros.tex", m)

    # figures of the main text
    (out / "atlas_figure.tex").write_text(atlas_figure(val, rd, rv, vr, R))
    (out / "transfer_figure.tex").write_text(transfer_figure(dep, con, fly, cal))
    (out / "reference_figure.tex").write_text(reference_figure(vr, rb, val, post["map_by_source"]))
    (out / "savings_figure.tex").write_text(savings_figure(sf, ext, summ, sp))
    (out / "law_figure.tex").write_text(ra.law_figure(load(EXT / "predictability" / "results" / "rows.json"),
                                                      pa.dev_rows(), ps, pa))
    (out / "pairfree_figure.tex").write_text(pairfree_figure(cs, prog, des, pev, rep))

    # tables of the Supplementary Information
    tables = {"deploy_table": deploy_table(dep), "deploy_site_table": site_table(dep),
              "deploy_contrast_table": contrast_table(con), "fly_table": fly_table(fly),
              "val_table": val_table(val), "audit_table": audit_table(val, cal_bm, sizes),
              "allocation_table": allocation_table(al), "readout_table": readout_table(rd),
              "calibration_table": calibration_table(rv), "multiplicity_table": multiplicity_table(rv),
              "alternatives_table": alternatives_table(rv), "robust_table": robust_table(rb, val),
              "pool_table": pool_table(rb), "donor_table": donor_table(rb), "savings_table": savings_table(summ),
              "review_draw_table": ra.draw_table(draws), "review_noise_table": ra.noise_table(cal),
              "review_noise_block_table": ra.noise_block_table(cal),
              "review_axes_table": ra.axes_table(vr), "review_relationship_table": ra.relationship_table(vr),
              "review_truths_table": ra.truths_table(vr), "review_fisher_table": ra.fisher_table(rc),
              "review_onedraw_table": ra.onedraw_table(vr, ab),
              "review_lawunits_table": ra.lawunits_table(law2["inference"]),
              "review_pilot_table": ra.pilot_table(ps), "review_fixed_table": ra.fixed_table(br),
              "review_fixed_detail_table": ra.fixed_detail_table(br)}
    for name, text in tables.items():
        (out / f"{name}.tex").write_text(text)
    print(len(m), "macros")


if __name__ == "__main__":
    main()
