"""Assets of the analyses added in the second review (extension/second_review and extension/checks): macros, the
tables of Supplementary Note 11 and the figure panels that show them. Imported by make_assets.py; every number is
read from the result records."""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
EXT = HERE.parent
REV = EXT / "second_review" / "results"
CHK = EXT / "checks" / "results"
HEADER = "% Generated by extension/synthesis/make_assets.py. Do not edit."


def load(path):
    return json.loads(Path(path).read_text())


def signed(text):
    return "\\ensuremath{-}" + text[1:] if text.startswith("-") else text


def pct(v, digits=None):
    p = 100 * v
    if digits is None:
        digits = 1 if abs(p) < 10 else 0
    return signed(f"{p:.{digits}f}")


def ratio(v, digits=2):
    return f"{v:.{digits}f}"


def sci(v):
    """A small positive number as a power of ten in LaTeX math, e.g. 4 x 10^-10."""
    if v == 0:
        return "0"
    e = int(np.floor(np.log10(v)))
    m = v / 10 ** e
    return f"{m:.0f}\\times10^{{{e}}}" if round(m) != 1 else f"10^{{{e}}}"


def cells(c, rel):
    return f"$>${c:.0f}" if rel == ">" else (f"$\\leq${c:.0f}" if rel == "<=" else f"{c:.0f}")


# ------------------------------------------------------------------ draw scoring (extension/checks)

def draw_records():
    recs = {}
    for p in sorted(CHK.glob("*.json")):
        if p.name == "draw_scoring.json":
            continue
        r = load(p)
        recs[r["test"]] = r
    return recs


def draw_table(recs):
    """Supplementary Table: every test's curves against the mean of per-draw scores."""
    rows = []
    order = ["external", "deployment", "validation"] + sorted(k for k in recs if k.startswith("benchmark/")) \
        + sorted(k for k in recs if k.startswith("law/"))
    for k in order:
        if k not in recs:
            continue
        r = recs[k]
        chk = r.get("stored_vs_regenerated", {})
        infl = r["averaged_prediction_minus_published"]
        name = {"external": "External test", "deployment": "Bone-marrow test", "validation": "Validation test"}.get(
            k, k.replace("benchmark/", "Benchmark: ").replace("law/", "Law: ").replace("_", "\\_"))
        units = (f"{r['units_regenerated']}/{r['units']}" if "units" in r else f"{len(r['problems'])} problems")
        draws = r.get("draws")
        draws = draws[0] if isinstance(draws, list) else draws
        d_pub = r.get("max_abs_difference_per_draw_vs_published")
        d_unit = r.get("max_abs_difference_per_draw_vs_stored_unit_terms", d_pub)
        d = max(x for x in (d_pub, d_unit) if x is not None)
        msq = chk.get("max_rel_msq_difference")
        rows.append(" & ".join([name, units, str(draws), f"${sci(max(d, 1e-16))}$",
                                "--" if msq is None else f"${sci(max(msq, 1e-16))}$",
                                f"{100 * infl['median']:.1f}", f"{100 * infl['max']:.0f}"]) + " \\\\")
    lines = [HEADER, "\\begin{tabular}{@{}lrrrrrr@{}}", "\\toprule",
             " & Units & Draws & \\multicolumn{2}{c}{Largest difference} & "
             "\\multicolumn{2}{c}{Averaged prediction} \\\\",
             "\\cmidrule(lr){4-5}\\cmidrule(l){6-7}",
             "Test & rerun & & curve & msq & median & max \\\\", "\\midrule"]
    lines += rows + ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(lines) + "\n"


def draw_macros(recs, m):
    diffs, infl = [], []
    for r in recs.values():
        for key in ("max_abs_difference_per_draw_vs_published", "max_abs_difference_per_draw_vs_stored_unit_terms"):
            if r.get(key) is not None:
                diffs.append(r[key])
        infl.append(r["averaged_prediction_minus_published"])
    m["RvDrawTests"] = str(len(recs))
    m["RvDrawMaxDiff"] = f"${sci(max(diffs))}$"
    m["RvDrawInflMedianMin"] = f"{100 * min(i['median'] for i in infl):.0f}"
    m["RvDrawInflMedianMax"] = f"{100 * max(i['median'] for i in infl):.0f}"
    m["RvDrawInflMax"] = f"{100 * max(i['max'] for i in infl):.0f}"
    dep = recs.get("deployment", {})
    m["RvDrawFileIdentical"] = "identical" if dep.get("regenerated_prediction_file_identical") else "not identical"


# ------------------------------------------------------------------ noise calibration after contrasts

ESTIMATES = [("helmert", "Helmert, draw order (implemented)"), ("helmert_shuffled", "Helmert, random order"),
             ("orthonormal", "Random orthonormal"), ("jackknife", "Jackknife over cells"),
             ("own_centring", "Own-mean centring")]
BLOCKS = [f"{r}/{c}" for r in ("1--5", "6--20", "21--60", "rest") for c in ("1--3", "rest")]


def noise_table(cal):
    """Supplementary Table: calibration ratios by study, budget and noise estimate (summed over blocks); for the
    implemented estimate, its 95% interval, its range over the eight blocks and its variation over orderings."""
    budgets = list(cal["validation"]["budgets"])
    n = len(budgets)
    lines = [HEADER, "\\begin{tabular}{@{}l" + "r" * n + "@{}}", "\\toprule",
             f" & \\multicolumn{{{n}}}{{c}}{{Paired cells}} \\\\", f"\\cmidrule(l){{2-{n + 1}}}",
             "Noise estimate & " + " & ".join(budgets) + " \\\\", "\\midrule"]
    for study, label in (("validation", "Validation test"), ("bone_marrow", "Bone-marrow test")):
        if study not in cal:
            continue
        bud = cal[study]["budgets"]
        lines.append(f"\\multicolumn{{{n + 1}}}{{@{{}}l}}{{\\textit{{{label}}}}} \\\\")
        for e, name in ESTIMATES:
            lines.append(f"{name} & " + " & ".join(f"{d['ratio'][e]['global']:.3f}" for d in bud.values()) + " \\\\")
            if e == "helmert":
                lines.append("\\quad 95\\% interval & " + " & ".join(
                    f"{d['ratio'][e]['global_ci'][0]:.3f}--{d['ratio'][e]['global_ci'][1]:.3f}" for d in bud.values())
                             + " \\\\")
                lines.append("\\quad range over blocks & " + " & ".join(
                    f"{min(d['ratio'][e]['blocks']):.2f}--{max(d['ratio'][e]['blocks']):.2f}" for d in bud.values())
                             + " \\\\")
                lines.append("\\quad order, CV (largest) & " + " & ".join(
                    f"{100 * max(d['ordering']['median_cv']):.1f}\\%" for d in bud.values()) + " \\\\")
                lines.append("\\quad order, factor range & " + " & ".join(
                    f"{max(d['ordering']['median_factor_range']):.3f}" for d in bud.values()) + " \\\\")
        for e, name in (("helmert", "Recovered (\\%), implemented"), ("jackknife", "Recovered (\\%), jackknife")):
            lines.append(f"{name} & " + " & ".join(pct(d["recovered_fraction"][e]) for d in bud.values()) + " \\\\")
        if study != "bone_marrow":
            lines.append("\\addlinespace")
    lines += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(lines) + "\n"


def noise_block_table(cal):
    """Supplementary Table: the implemented estimate's calibration ratio block by block, with 95% intervals."""
    budgets = list(cal["validation"]["budgets"])
    n = len(budgets)
    lines = [HEADER, "\\begin{tabular}{@{}l" + "r" * n + "@{}}", "\\toprule",
             f" & \\multicolumn{{{n}}}{{c}}{{Paired cells}} \\\\", f"\\cmidrule(l){{2-{n + 1}}}",
             "Block (RNA/protein axes) & " + " & ".join(budgets) + " \\\\", "\\midrule"]
    for study, label in (("validation", "Validation test"), ("bone_marrow", "Bone-marrow test")):
        if study not in cal:
            continue
        bud = cal[study]["budgets"]
        lines.append(f"\\multicolumn{{{n + 1}}}{{@{{}}l}}{{\\textit{{{label}}}}} \\\\")
        for k, blk in enumerate(BLOCKS):
            lines.append(f"{blk} & " + " & ".join(
                f"{d['ratio']['helmert']['blocks'][k]:.3f}" for d in bud.values()) + " \\\\")
            lines.append(" & " + " & ".join(
                f"({d['ratio']['helmert']['blocks_ci'][k][0]:.3f}--{d['ratio']['helmert']['blocks_ci'][k][1]:.3f})"
                for d in bud.values()) + " \\\\")
        if study != "bone_marrow":
            lines.append("\\addlinespace")
    lines += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(lines) + "\n"


def noise_macros(cal, m):
    for study, key in (("validation", "Val"), ("bone_marrow", "Bm")):
        if study not in cal:
            continue
        bud = cal[study]["budgets"]
        g = [d["ratio"]["helmert"]["global"] for d in bud.values()]
        m[f"RvCal{key}Min"], m[f"RvCal{key}Max"] = f"{min(g):.3f}", f"{max(g):.3f}"
        bl = [x for d in bud.values() for x in d["ratio"]["helmert"]["blocks"]]
        m[f"RvCal{key}BlockMin"], m[f"RvCal{key}BlockMax"] = f"{min(bl):.2f}", f"{max(bl):.2f}"
        j = [d["ratio"]["jackknife"]["global"] for d in bud.values()]
        m[f"RvCal{key}JackMax"], m[f"RvCal{key}JackMin"] = f"{max(j):.2f}", f"{min(j):.2f}"
        o = [d["ratio"]["own_centring"]["global"] for d in bud.values()]
        m[f"RvCal{key}OwnMin"], m[f"RvCal{key}OwnMax"] = f"{min(o):.2f}", f"{max(o):.2f}"
        q = [d["ratio"]["orthonormal"]["global"] for d in bud.values()]
        m[f"RvCal{key}OrthoMin"], m[f"RvCal{key}OrthoMax"] = f"{min(q):.3f}", f"{max(q):.3f}"
        # ordering: per block, the median over resamples of the coefficient of variation of the estimate across 20
        # orders and of the range of the block's shrinkage factor; the largest block at each budget
        cv = {B: max(d["ordering"]["median_cv"]) for B, d in bud.items()}
        fr = {B: max(d["ordering"]["median_factor_range"]) for B, d in bud.items()}
        m[f"RvCal{key}OrderCvMax"] = f"{100 * max(cv.values()):.0f}"
        m[f"RvCal{key}OrderFactorMax"] = f"{max(fr.values()):.2f}"
        m[f"RvCal{key}OrderCvHundred"] = f"{100 * cv['100']:.1f}"
        m[f"RvCal{key}OrderFactorHundred"] = f"{fr['100']:.2f}"
        m[f"RvCal{key}OrderCvEight"] = f"{100 * cv['800']:.1f}"
        m[f"RvCal{key}OrderFactorEight"] = f"{fr['800']:.3f}"
        rh = [d["recovered_fraction"]["helmert"] for d in bud.values()]
        rj = [d["recovered_fraction"]["jackknife"] for d in bud.values()]
        dd = [100 * (b - a) for a, b in zip(rh, rj)]
        m[f"RvCal{key}JackGainMin"], m[f"RvCal{key}JackGainMax"] = f"{min(dd):.1f}", f"{max(dd):.1f}"


def noise_panel(cal, at, name, title, axis_start, common, log_x):
    """Calibration ratio (mean noise estimate over the variance across independent resamples) against paired cells."""
    styles = {"helmert": "color=propcol,line width=1.1pt,mark=*,mark size=1.4pt",
              "jackknife": "color=semicol,line width=.8pt,mark=square*,mark size=1.2pt",
              "own_centring": "color=meancol,line width=.8pt,mark=x,mark size=1.8pt"}
    lines = [axis_start(at, name, ".3", "3.2cm", log_x),
             " xmin=20,xmax=1000,ymin=.6,ymax=1.7,xtick={25,50,100,200,400,800},xticklabels={25,50,100,200,400,800},",
             " ytick={.6,.8,1,1.2,1.4,1.6},xlabel={Paired cells},ylabel={Estimated / actual noise},",
             f" title={{{title}}},", common + "]",
             "\\draw[dashed,black!45] (axis cs:20,1) -- (axis cs:1000,1);"]
    for study, dash in (("validation", ""), ("bone_marrow", ",densely dashed")):
        if study not in cal:
            continue
        bud = cal[study]["budgets"]
        for e, style in styles.items():
            pts = " ".join(f"({B},{min(max(d['ratio'][e]['global'], .6), 1.7):.4f})" for B, d in bud.items())
            lines.append(f"\\addplot[{style}{dash}] coordinates {{ {pts} }};")
    lines.append("\\end{axis}")
    return lines


# ------------------------------------------------------------------ what the reference contributes (Fig. 3)

AXES_ARMS = [("atlas", "Axes and maps", "color=propcol,line width=1.2pt,mark=*,mark size=1.6pt"),
             ("atlas/map_only", "Maps only", "color=champcol,line width=.9pt,mark=triangle*,mark size=1.7pt"),
             ("atlas/axes", "Axes only", "color=propcol,line width=.9pt,dashed,mark=o,mark size=1.5pt,"
                                         "mark options={solid}"),
             ("js/pooled", "Neither", "color=pairedcol,line width=.8pt,mark=square*,mark size=1.3pt")]


def arm_key(ref, kind):
    if ref == "full":
        return {"mapped": "atlas", "axes": "atlas/axes", "reweighted": "full/reweighted"}[kind]
    return f"{ref}/{kind}"


def axes_panel(vr, at, name, title, axis_start, common, log_x, curve_lines):
    b = vr["budgets"]
    xt = ",".join(str(x) for x in b if x != 150)
    tgt = 100 * vr["target"]
    lines = [axis_start(at, name, ".3", "3.2cm", log_x),
             f" xmin=20,xmax=1000,ymin=-5,ymax=55,xtick={{{xt}}},xticklabels={{{xt}}},ytick={{0,10,20,30,40,50}},",
             " xlabel={Paired cells},ylabel={Dependence recovered (\\%)},",
             f" title={{{title}}},", common + "]",
             f"\\draw[dashed,black!45] (axis cs:20,{tgt:.2f}) -- (axis cs:1000,{tgt:.2f});"]
    for arm, _, style in AXES_ARMS:
        lines += curve_lines(b, vr["arms"][arm]["rf"], style, lo=-5)
    lines.append("\\end{axis}")
    return lines


BM_MAP_ARMS = [("other_mapped", "Whole-cell axes and maps", "color=propcol,line width=1.2pt,mark=*,mark size=1.6pt"),
               ("assay_bases_other_map", "Nuclear axes, whole-cell maps",
                "color=semicol,line width=.9pt,dashed,mark=triangle*,mark size=1.6pt,mark options={solid}"),
               ("assay_mapped", "Nuclear axes and maps",
                "color=semicol,line width=.9pt,mark=triangle*,mark size=1.6pt"),
               ("other_unmapped", "Whole-cell axes only",
                "color=propcol,line width=.9pt,dashed,mark=o,mark size=1.5pt,mark options={solid}"),
               ("assay_unmapped", "Nuclear axes only",
                "color=semicol,line width=.9pt,densely dotted,mark=triangle,mark size=1.6pt,mark options={solid}")]


def bm_map_panel(mp, at, name, title, axis_start, common, log_x, curve_lines):
    b = mp["budgets"]
    xt = ",".join(str(x) for x in b)
    lines = [axis_start(at, name, ".3", "3.2cm", log_x),
             f" xmin=20,xmax=1000,ymin=-5,ymax=40,xtick={{{xt}}},xticklabels={{{xt}}},ytick={{0,10,20,30,40}},",
             " xlabel={Paired cells},ylabel={Dependence recovered (\\%)},",
             f" title={{{title}}},", common + "]"]
    for arm, _, style in BM_MAP_ARMS:
        lines += curve_lines(b, mp["rf"][arm], style, lo=-5)
    lines.append("\\end{axis}")
    return lines


def legend_rows(anchor, entries, columns, shift="-2pt", side="north"):
    """A legend without an axis below the point anchor; side north centres it there, north west and north east
    align its left or right edge with the point."""
    x = {"north": "0.5", "north west": "0", "north east": "1"}[side]
    out = ["\\begin{axis}[hide axis,scale only axis,width=1pt,height=1pt,xmin=0,xmax=1,ymin=0,ymax=1,"
           f"at={{({anchor})}},anchor={side},yshift={shift},legend style={{draw=none,font=\\sffamily\\scriptsize,"
           f"at={{({x},0.5)}},anchor={side},legend columns={columns},column sep=5pt,cells={{anchor=west}}}}]"]
    for style, label in entries:
        out += [f"\\addlegendimage{{{style}}}", f"\\addlegendentry{{{label}}}"]
    out.append("\\end{axis}")
    return out


# ------------------------------------------------------------------ the law (Fig. 6)

LAW_MAX = 48      # both axes of Fig. 6a,b, from .5 to beyond the largest saving (34 predicted at 30%)


def law_scatter(name, at, title, ylabel, common):
    ticks = "{0.5,1,2,4,8,16,32}"
    return [f"\\begin{{axis}}[name={name},{at}scale only axis,width=.2\\textwidth,height=.2\\textwidth,"
            f"xmode=log,ymode=log,log basis x=2,log basis y=2,xmin=.5,xmax={LAW_MAX},ymin=.5,ymax={LAW_MAX},"
            f"xtick={ticks},ytick={ticks},xticklabels={{.5,1,2,4,8,16,32}},yticklabels={{.5,1,2,4,8,16,32}},"
            f"xlabel={{Predicted saving}},{'ylabel={Observed saving},' if ylabel else ''}"
            f"title={{{title}}},{common}]",
            f"\\addplot[black!45,domain=.5:{LAW_MAX},samples=2] {{x}};",
            f"\\addplot[black!25,dashed,domain=.5:{LAW_MAX / 1.25},samples=2] {{1.25*x}};",
            f"\\addplot[black!25,dashed,domain=.625:{LAW_MAX},samples=2] {{x/1.25}};"]


STATUS = [("estimable", "Measured"), ("below", "Above target\\\\at 25 cells"),
          ("above", "Not reached\\\\within budgets")]


def status_of(r):
    if r["estimable"]:
        return "estimable"
    if r["rel_js"] == "<=" or r["rel_blocks"] == "<=":
        return "below"
    return "above"


def law_figure(rows, dev, lr, pa):
    """Fig. 6: the law against observation at half the dependence recovered (prospective and development) and at
    30% and 70%; every prospective problem by status; and budgets chosen from a pilot, pilot included."""
    L = ["% Generated by extension/synthesis/make_assets.py. Do not edit.",
         "\\definecolor{protcol}{HTML}{217D91}", "\\definecolor{chromcol}{HTML}{8C5BA8}",
         "\\definecolor{wirecol}{HTML}{C9803A}", "\\definecolor{ephyscol}{HTML}{6BAF5A}",
         "\\definecolor{meancol}{HTML}{A64442}", "\\definecolor{pairedcol}{HTML}{5D6670}",
         f"\\begin{{tikzpicture}}[{pa.SANS}]"]
    est = [r for r in rows if r["target"] == 0.5 and r["estimable"]]
    n_all = len({(r["dataset"], r["problem"]) for r in rows if r["target"] == 0.5})
    L += law_scatter("a", "", f"\\textbf{{a}}\\enspace 50\\%, {len(est)} of {n_all} measurable", True, pa.COMMON)
    L.append("\\addplot[only marks,mark=o,mark size=1.5pt,color=black!35] coordinates {"
             + " ".join(f"({l:.3f},{s:.3f})" for _, s, l in dev) + "};")
    for n in [n for n in pa.NEW if any(r["dataset"] == n for r in est)]:
        pts = [(r["law"], r["observed"]) for r in est if r["dataset"] == n]
        L.append(f"\\addplot[only marks,mark={pa.MARK.get(n, '*')},mark size=1.8pt,color={pa.COL[pa.SYSTEM[n]]}] "
                 "coordinates {" + " ".join(f"({x:.3f},{y:.3f})" for x, y in pts) + "};")
    L.append("\\end{axis}")
    L += law_scatter("b", "at={(a.outer north east)},anchor=outer north west,xshift=.2cm,",
                     "\\textbf{b}\\enspace 30\\% and 70\\%", False, pa.COMMON)
    for tg, fill in ((0.3, False), (0.7, True)):
        es = [r for r in rows if r["target"] == tg and r["estimable"] and r["law"]]
        for n in [n for n in pa.NEW if any(r["dataset"] == n for r in es)]:
            mk = pa.MARK.get(n, "*")
            mk = mk if fill else {"*": "o"}.get(mk, mk.rstrip("*"))     # open markers at 30%
            pts = [(r["law"], r["observed"]) for r in es if r["dataset"] == n]
            L.append(f"\\addplot[only marks,mark={mk},mark size=1.8pt,color={pa.COL[pa.SYSTEM[n]]}] coordinates {{"
                     + " ".join(f"({x:.3f},{y:.3f})" for x, y in pts) + "};")
    L.append(f"\\node[font=\\sffamily\\scriptsize,anchor=north west,align=left] at (axis cs:.55,{LAW_MAX * .92:g}) "
             "{open, 30\\%\\\\ filled, 70\\%};")
    L.append("\\end{axis}")
    # c: every prospective problem at half the dependence, by status, against the law's prediction
    half = [r for r in rows if r["target"] == 0.5 and r["law"]]
    L += ["\\begin{axis}[name=c,at={(b.outer north east)},anchor=outer north west,xshift=.2cm,scale only axis,"
          "width=.2\\textwidth,height=.2\\textwidth,xmode=log,log basis x=2,xmin=1,xmax=64,ymin=.4,ymax=3.6,"
          "xtick={1,2,4,8,16,32,64},xticklabels={1,2,4,8,16,32,64},ytick={1,2,3},"
          "yticklabels={" + ",".join("{" + lab + "}" for _, lab in reversed(STATUS)) + "},"
          "yticklabel style={align=right},xlabel={Predicted saving},"
          f"title={{\\textbf{{c}}\\enspace All {len({(r['dataset'], r['problem']) for r in half})} problems}},"
          + pa.COMMON + "]"]
    for y, (st, _) in enumerate(reversed(STATUS), start=1):
        grp = [r for r in half if status_of(r) == st]
        for n in pa.NEW:
            g = sorted(r["law"] for r in grp if r["dataset"] == n)
            if not g:
                continue
            jit = np.linspace(-.18, .18, len(g)) if len(g) > 1 else [0]
            L.append(f"\\addplot[only marks,mark=*,mark size=1.4pt,color={pa.COL[pa.SYSTEM[n]]}] coordinates {{"
                     + " ".join(f"({x:.3f},{y + j:.3f})" for x, j in zip(g, jit)) + "};")
    L.append("\\end{axis}")
    L += ["\\begin{axis}[hide axis,scale only axis,width=1pt,height=1pt,xmin=0,xmax=1,ymin=0,ymax=1,"
          "at={(c.outer south east)},anchor=north east,yshift=-2pt,legend style={draw=none,"
          "font=\\sffamily\\scriptsize,at={(1,0.5)},anchor=north east,legend columns=2,column sep=5pt,"
          "cells={anchor=west}}]"]
    for sy, lab in (("prot", "RNA--protein"), ("chrom", "RNA--chromatin"), ("wire", "Fly wiring"),
                    ("ephys", "Patch-seq")):
        L += [f"\\addlegendimage{{only marks,mark=*,mark size=1.4pt,color={pa.COL[sy]}}}", f"\\addlegendentry{{{lab}}}"]
    L.append("\\end{axis}")
    if lr is not None:
        L += pilot_panel(lr, "at={(b.outer south west)},anchor=outer north west,yshift=-1cm,",
                         "d", "\\textbf{d}\\enspace Budgets set from a pilot", pa.COMMON)
        L += ["\\begin{axis}[hide axis,scale only axis,width=1pt,height=1pt,xmin=0,xmax=1,ymin=0,ymax=1,"
              "at={(d.outer east)},anchor=west,xshift=.3cm,legend style={draw=none,font=\\sffamily\\scriptsize,"
              "at={(0,0.5)},anchor=west,legend columns=1,cells={anchor=west}}]"]
        for m_, lab in (("50", "Pilot of 50 cells"), ("100", "Pilot of 100 cells"), ("200", "Pilot of 200 cells"),
                        ("reservoir", "Law with every reservoir cell")):
            L += [f"\\addlegendimage{{only marks,{PILOT_STYLE[m_][0]}}}", f"\\addlegendentry{{{lab}}}"]
        L += ["\\addlegendimage{dashed,black!45}", "\\addlegendentry{Target}", "\\end{axis}"]
    L += ["\\begin{axis}[hide axis,scale only axis,width=1pt,height=1pt,xmin=0,xmax=1,ymin=0,ymax=1,"
          "at={(a.outer south west)},anchor=north west,yshift=-2pt,legend style={draw=none,"
          "font=\\sffamily\\scriptsize,at={(0,0.5)},anchor=north west,legend columns=1,"
          "cells={anchor=west}}]",
          "\\addlegendimage{only marks,mark=o,mark size=1.5pt,color=black!35}\\addlegendentry{Benchmark (development)}"]
    for n in [n for n in pa.NEW if any(r["dataset"] == n for r in est)]:
        L.append(f"\\addlegendimage{{only marks,mark={pa.MARK.get(n, '*')},mark size=1.8pt,"
                 f"color={pa.COL[pa.SYSTEM[n]]}}}\\addlegendentry{{{pa.SHORT[n]}}}")
    L += ["\\end{axis}", "\\end{tikzpicture}"]
    return "\n".join(L) + "\n"


# ------------------------------------------------------------------ per-donor readout (Fig. 2)

def review_folds(path=REV / "validation"):
    return [dict(np.load(p)) for p in sorted(Path(path).glob("fold*.npz"))]


def donor_readout(R, arms_all, po_arms, reg_arms, budget, e, truth_index=0):
    """Per donor: E1 (e=1) or E2 (e=2) at one budget for the atlas, the best paired-only arm and the best form of
    reference regression, the best chosen on the pooled endpoint (as for the published envelopes)."""
    b = [int(x) for x in R[0]["budgets"]].index(budget)
    donors = sorted({str(r["donor"]) for r in R})
    num = {d: np.zeros(len(arms_all)) for d in donors}
    den = {d: 0.0 for d in donors}
    for r in R:
        d = str(r["donor"])
        sc = r["scored/primary"].astype(bool) if truth_index == 0 else r["scored/primary"].astype(bool)
        v = np.nanmean(r["score"][b, :, :, :, truth_index, e], 0)[:, sc]      # arms x scored types
        num[d] += v.sum(-1)
        den[d] += float(r["reps/primary"][sc].sum()) if e == 1 else 100.0 * int(sc.sum())
    pooled = sum(num.values()) / sum(den.values())
    best_po = max(po_arms, key=lambda a: pooled[arms_all.index(a)])
    best_reg = max(reg_arms, key=lambda a: pooled[arms_all.index(a)])
    out = {}
    for d in donors:
        if den[d] == 0:
            continue
        v = num[d] / den[d]
        out[d] = {"atlas": float(v[arms_all.index("atlas")]), "paired_only": float(v[arms_all.index(best_po)]),
                  "regression": float(v[arms_all.index(best_reg)])}
    return out, best_po, best_reg


def donor_macros(dr, m):
    """Per donor, with 100 paired cells: in how many donors the atlas estimate predicted more directions correctly
    than the best paired-only method and than the best form of reference regression, and the range of the
    differences (percentage points)."""
    po = [100 * (v["atlas"] - v["paired_only"]) for v in dr.values()]
    rg = [100 * (v["atlas"] - v["regression"]) for v in dr.values()]
    m["RvDonorN"] = str(len(dr))
    m["RvDonorBetterPo"] = str(sum(x > 0 for x in po))
    m["RvDonorBetterReg"] = str(sum(x > 0 for x in rg))
    m["RvDonorMinusPoMin"], m["RvDonorMinusPoMax"] = pct(min(po) / 100), pct(max(po) / 100)
    m["RvDonorMinusRegMin"], m["RvDonorMinusRegMax"] = pct(min(rg) / 100), pct(max(rg) / 100)


def donor_panel(dr, at, name, title, axis_start, common_x):
    """Per donor: E1 of the atlas estimate minus that of the best paired-only method and of reference regression."""
    diffs = {"paired_only": [100 * (v["atlas"] - v["paired_only"]) for v in dr.values()],
             "regression": [100 * (v["atlas"] - v["regression"]) for v in dr.values()]}
    rows = [("paired_only", "Paired only"), ("regression", "Regression, atlas")]
    lo = min(-10, 5 * np.floor(min(min(v) for v in diffs.values()) / 5))
    hi = max(10, 5 * np.ceil(max(max(v) for v in diffs.values()) / 5))
    lines = [axis_start(at, name, ".16", "3.2cm"),
             f" xmin={lo:.0f},xmax={hi:.0f},ymin=.4,ymax=2.6,ytick={{1,2}},",
             " yticklabels={" + ",".join("{" + lab + "}" for _, lab in reversed(rows)) + "},",
             " xlabel={Difference (points)},",
             f" title={{{title}}},", common_x + "]",
             "\\draw[dashed,black!45] (axis cs:0,.4) -- (axis cs:0,2.6);"]
    for y, (k, _) in enumerate(reversed(rows), start=1):
        v = np.array(diffs[k])
        jit = np.linspace(-.2, .2, len(v))
        order = np.argsort(v)
        lines.append("\\addplot[only marks,mark=*,mark size=1.1pt,color=propcol!60] coordinates { "
                     + " ".join(f"({v[i]:.2f},{y + jit[j]:.3f})" for j, i in enumerate(order)) + " };")
        m = float(np.mean(v))
        lines.append(f"\\draw[color=black,line width=1.2pt] (axis cs:{m:.2f},{y - .3}) -- (axis cs:{m:.2f},{y + .3});")
    lines.append("\\end{axis}")
    return lines


# ------------------------------------------------------------------ validation review macros

BUDGET_WORD = {25: "TwentyFive", 50: "Fifty", 100: "Hundred", 150: "OneFifty", 200: "TwoHundred",
               400: "FourHundred", 800: "Eight"}


def cells_text(a):
    return f"more than {a['cells']:.0f}" if a["relation"] == ">" else f"{a['cells']:.0f}"


def validation_macros(vr, m):
    b = vr["budgets"]
    arms = vr["arms"]
    names = {"atlas": "Both", "atlas/axes": "Axes", "atlas/map_only": "MapOnly", "js/pooled": "Neither",
             "other/axes": "OtherAxes", "own/axes": "OwnAxes", "paired_only": "Po", "regression": "Reg",
             "few_B_mono/mapped": "FewBMonoMapped", "few_B_mono/axes": "FewBMonoAxes",
             "few_B_mono/reweighted": "FewBMonoRw", "few_T/mapped": "FewTMapped", "few_T/axes": "FewTAxes",
             "few_T/reweighted": "FewTRw", "full/reweighted": "FullRw"}
    for arm, w in names.items():
        a = arms[arm]
        for i, B in enumerate(b):
            m[f"Rv{w}{BUDGET_WORD[B]}"] = pct(a["rf"][i])
            m[f"Rv{w}{BUDGET_WORD[B]}Lo"] = pct(a["rf_ci"][i][0])
            m[f"Rv{w}{BUDGET_WORD[B]}Hi"] = pct(a["rf_ci"][i][1])
        m[f"Rv{w}Cells"] = cells_text(a)
        m[f"Rv{w}CellsLo"], m[f"Rv{w}CellsHi"] = (f"{x:.0f}" for x in a["cells_ci"])
    for arm, w in names.items():
        if arm in vr["savings_over_paired_only"]:
            sv = vr["savings_over_paired_only"][arm]
            at_least = "at least " if sv["numerator_relation"] == ">" else ""
            m[f"Rv{w}Save"] = f"{at_least}{sv['ratio']:.1f}"
            m[f"Rv{w}SaveLo"], m[f"Rv{w}SaveHi"] = (f"{x:.1f}" for x in sv["ci"])
    m["RvValMeanDiff"] = f"${sci(vr['integrity']['max_abs_mean'])}$"
    m["RvValMsqDiff"] = f"${sci(max(vr['integrity']['max_rel_msq'], 1e-16))}$" if vr["integrity"]["max_rel_msq"] > 0 \
        else "machine precision"
    tv = vr["truth_variants"]
    i100 = b.index(100)
    for v, w in (("primary", "Primary"), ("fine", "Fine"), ("technical", "Tech"), ("both", "TechFine")):
        for e, we in (("E1", "One"), ("E2", "Two"), ("recovered_fraction", "Rf")):
            for comp, wc in (("paired_only", "Po"), ("regression", "Reg")):
                dd = tv[v][e]["atlas_minus"][comp]
                m[f"Rv{w}{we}Minus{wc}"] = pct(dd["difference"][i100])
                m[f"Rv{w}{we}Minus{wc}Lo"], m[f"Rv{w}{we}Minus{wc}Hi"] = (pct(x) for x in dd["ci"][i100])
            m[f"Rv{w}{we}Atlas"] = pct(tv[v][e]["values"]["atlas"][i100])
            m[f"Rv{w}{we}Po"] = pct(tv[v][e]["values"]["paired_only"][i100])
            m[f"Rv{w}{we}Reg"] = pct(tv[v][e]["values"]["regression"][i100])
        m[f"Rv{w}Reps"] = f"{tv[v]['reproducible']:,}"
        m[f"Rv{w}Units"] = str(tv[v]["units_scored"])


# ------------------------------------------------------------------ named relationships (Fig. 2f, Supplementary Table)

WORDS = ("One", "Two", "Three", "Four", "Five", "Six", "Seven", "Eight")
REL_WORD = {f"R{i}": f"Rel{w}" for i, w in enumerate(WORDS, start=1)}
REL_LABEL = {"R1": "CD14 Mono: interferon, CD169", "R2": "CD14 Mono: MHC II, HLA-DR", "R3": "B: MHC II, HLA-DR",
             "R4": "CD8 T: cytotoxic, CD57", "R5": "CD8 T: cytotoxic, CD27", "R6": "NK: cytotoxic, CD16",
             "R7": "NK: cytotoxic, CD56", "R8": "CD4 T: LEF1, CD45RA"}
REL_ARMS = [("atlas", "Estimator, atlas", "mark=*,mark size=1.8pt,color=propcol"),
            ("regression", "Reference regression, atlas", "mark=pentagon*,mark size=1.8pt,color=ridgecol!70!black"),
            ("paired_only", "Paired cells only", "mark=square*,mark size=1.5pt,color=pairedcol")]


def scored_relationships(vr):
    return [k for k in REL_LABEL if vr["relationships"].get(k, {}).get("units", 0)]


def relationship_values(R, vr, budget):
    """Per relationship: the held-out values (mean over genes of the within-type correlation with the protein) of
    every scored unit, and the mean prediction of the estimator and of the comparators' chosen members over units and
    draws with one budget of paired cells."""
    arms_all = [a for a in vr["arms"] if a not in ("paired_only", "regression")]
    bi = [int(x) for x in R[0]["budgets"]].index(budget)
    out = {}
    for ri, k in enumerate(REL_LABEL):
        rel = vr["relationships"].get(k, {})
        if not rel.get("units", 0):
            continue
        rows = [r for r in R if np.isfinite(r["rel_truth"][ri, 0])]
        truth = np.array([r["rel_truth"][ri, 0] for r in rows])
        pred = {}
        for fam in ("atlas", "regression", "paired_only"):
            arm = fam if fam == "atlas" else rel["arms"][fam]["members"][vr["budgets"].index(budget)]
            ai = arms_all.index(arm)
            pred[fam] = float(np.mean([np.nanmean(r["prog"][bi, :, ai, ri]) for r in rows]))
        out[k] = {"truth": truth, "pred": pred}
    return out


def relationship_panel(vals, at, name, title, axis_start, common_x):
    """Held-out value of each named relationship (diamond: mean over held-out samples; bar: their range) and the
    mean prediction of each method."""
    names = [k for k in REL_LABEL if k in vals]
    n = len(names)
    lines = [axis_start(at, name, ".2", "3.5cm"),
             f" xmin=-.8,xmax=.8,ymin=.4,ymax={n + .6},xtick={{-.8,-.4,0,.4,.8}},"
             "xticklabels={$-$0.8,$-$0.4,0,0.4,0.8},",
             f" ytick={{{','.join(str(k) for k in range(1, n + 1))}}},",
             " yticklabels={" + ",".join("{" + REL_LABEL[k] + "}" for k in reversed(names)) + "},",
             " xlabel={Within-type correlation},",
             f" title={{{title}}},", common_x + "]",
             f"\\draw[dashed,black!45] (axis cs:0,.4) -- (axis cs:0,{n + .6});"]
    for y, k in enumerate(reversed(names), start=1):
        t = vals[k]["truth"]
        yt = y + .24
        lines.append(f"\\draw[black!55,line width=.7pt] (axis cs:{t.min():.3f},{yt:.2f}) -- "
                     f"(axis cs:{t.max():.3f},{yt:.2f});")
        lines.append("\\addplot[only marks,mark=diamond*,mark size=2.2pt,color=black] "
                     f"coordinates {{ ({t.mean():.3f},{yt:.2f}) }};")
        for (arm, _, style), dy in zip(REL_ARMS, (.08, -.08, -.24)):
            lines.append(f"\\addplot[only marks,{style}] coordinates {{ ({vals[k]['pred'][arm]:.3f},{y + dy:.2f}) }};")
    lines.append("\\end{axis}")
    return lines


def relationship_table(vr, budget=100):
    i = vr["budgets"].index(budget)
    lines = [HEADER, "\\begin{tabular}{@{}lrrrrrrrrrr@{}}", "\\toprule",
             " & & Held-out & \\multicolumn{3}{c}{Recovered (\\%)} & \\multicolumn{3}{c}{Correct sign (\\%)}"
             " & \\multicolumn{2}{c}{Donors, estimator better} \\\\",
             "\\cmidrule(lr){4-6}\\cmidrule(lr){7-9}\\cmidrule(l){10-11}",
             "Relationship & Units & $r$ & Est. & Regr. & Paired & Est. & Regr. & Paired & than regr. & "
             "than paired \\\\",
             "\\midrule"]
    for k in REL_LABEL:
        r = vr["relationships"].get(k, {})
        if not r.get("units", 0):
            lines.append(f"{k}\\enspace {REL_LABEL[k]} & 0 & \\multicolumn{{9}}{{l}}{{no held-out unit with 20 cells "
                         f"in each half}} \\\\")
            continue
        a = r["arms"]
        dl = {fam: [x for x in r["donor_level"][fam] if x["budget"] == budget][0]
              for fam in ("regression", "paired_only")}
        lines.append(" & ".join(
            [f"{k}\\enspace {REL_LABEL[k]}", str(r["units"]), signed(f"{r['truth_mean']:.2f}")]
            + [pct(a[x]["rf"][i]) for x in ("atlas", "regression", "paired_only")]
            + [f"{100 * a[x]['sign'][i]:.0f}" for x in ("atlas", "regression", "paired_only")]
            + [f"{dl[f]['donors_atlas_better']}/{dl[f]['donors']}" for f in ("regression", "paired_only")]) + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(lines) + "\n"


def relationship_macros(vr, m, budget=100, vals=None):
    """Macros of the named relationships; with `vals` (relationship_values at the same budget) also each method's mean
    prediction and each relationship's share of units with the expected sign."""
    i = vr["budgets"].index(budget)
    names = scored_relationships(vr)
    m["RvRelN"] = str(len(names))
    m["RvRelUnits"] = f"{sum(vr['relationships'][k]['units'] for k in names):,}"
    better = {"paired_only": 0, "regression": 0}
    for k in names:
        r = vr["relationships"][k]
        w = REL_WORD[k]
        for arm, aw in (("atlas", "Atlas"), ("regression", "Reg"), ("paired_only", "Po")):
            m[f"Rv{w}{aw}Rf"] = pct(r["arms"][arm]["rf"][i])
            m[f"Rv{w}{aw}Sign"] = f"{100 * r['arms'][arm]['sign'][i]:.0f}"
        m[f"Rv{w}Units"] = str(r["units"])
        m[f"Rv{w}Truth"] = signed(f"{r['truth_mean']:.2f}")
        m[f"Rv{w}TruthShare"] = f"{100 * r['truth_share_expected_sign']:.0f}"
        if vals is not None and k in vals:
            for arm, aw in (("atlas", "Atlas"), ("regression", "Reg"), ("paired_only", "Po")):
                m[f"Rv{w}{aw}Pred"] = signed(f"{vals[k]['pred'][arm]:.2f}")
        for fam, fw in (("paired_only", "Po"), ("regression", "Reg")):
            dl = [x for x in r["donor_level"][fam] if x["budget"] == budget][0]
            m[f"Rv{w}Donors{fw}"] = f"{dl['donors_atlas_better']} of {dl['donors']}"
            better[fam] += r["arms"]["atlas"]["rf"][i] > r["arms"][fam]["rf"][i]
    m["RvRelBetterPo"], m["RvRelBetterReg"] = str(better["paired_only"]), str(better["regression"])
    # donors: over relationships, the share of donor comparisons in which the estimator's error was lower
    for fam, fw in (("paired_only", "Po"), ("regression", "Reg")):
        tot = sum([x for x in vr["relationships"][k]["donor_level"][fam] if x["budget"] == budget][0]["donors"]
                  for k in names)
        win = sum([x for x in vr["relationships"][k]["donor_level"][fam] if x["budget"] == budget][0]
                  ["donors_atlas_better"] for k in names)
        m[f"RvRelDonorWin{fw}"] = f"{100 * win / tot:.0f}" if tot else "--"


# ------------------------------------------------------------------ reference reweighting (Fig. 4b)

COMP_KINDS = [("mapped", "Unweighted maps", "mark=*,mark size=1.8pt,color=propcol", "propcol"),
              ("reweighted", "Reweighted maps", "mark=triangle*,mark size=2pt,color=meancol", "meancol"),
              ("axes", "No maps", "mark=o,mark size=1.8pt,color=propcol", "propcol")]
COMP_LABEL = {"full": "All 118 patients", "few_B_mono": "B, CD14 Mono from 15", "few_T": "CD4, CD8 T from 15"}


def composition_cells_panel(vr, at, name, title, axis_start, common_x, log_x):
    """Paired cells to the primary target for each atlas composition, with the published maps, reweighted maps and
    no maps; bars, 95% intervals from resampling donors; arrows, not reached within 800."""
    refs = list(COMP_LABEL)
    lines = [axis_start(at, name, ".2", "3.2cm", log_x),
             f" xmin=20,xmax=1600,ymin=.4,ymax={len(refs) + .6},xtick={{25,100,400,1600}},"
             "xticklabels={25,100,400,$>$800},",
             f" ytick={{{','.join(str(k) for k in range(1, len(refs) + 1))}}},",
             " yticklabels={" + ",".join("{" + COMP_LABEL[r] + "}" for r in reversed(refs)) + "},",
             " xlabel={Paired cells to the target},",
             f" title={{{title}}},", common_x + "]",
             f"\\draw[black!25] (axis cs:800,.4) -- (axis cs:800,{len(refs) + .6});"]
    for y, ref in enumerate(reversed(refs), start=1):
        for (kind, _, style, color), dy in zip(COMP_KINDS, (.22, 0, -.22)):
            a = vr["arms"][arm_key(ref, kind)]
            yy = y + dy
            if a["relation"] == ">":
                lines.append(f"\\draw[->,color={color},line width=.7pt] (axis cs:800,{yy:.2f}) -- "
                             f"(axis cs:1400,{yy:.2f});")
                lines.append(f"\\addplot[only marks,{style.replace('mark=*', 'mark=o')}] coordinates "
                             f"{{ (800,{yy:.2f}) }};")
                continue
            lo, hi = a["cells_ci"]
            lines.append(f"\\draw[color={color},line width=.7pt] (axis cs:{max(lo, 20):.1f},{yy:.2f}) -- "
                         f"(axis cs:{min(hi, 1400):.1f},{yy:.2f});")
            lines.append(f"\\addplot[only marks,{style}] coordinates {{ ({a['cells']:.1f},{yy:.2f}) }};")
    lines.append("\\end{axis}")
    return lines


def axes_table(vr):
    """Supplementary Table: axes and condition maps, and reweighting, in the validation test."""
    b = vr["budgets"]
    rows = [("Atlas", [("atlas", "Axes and maps"), ("atlas/axes", "Axes only"),
                       ("atlas/map_only", "Maps only"), ("js/pooled", "Neither")]),
            ("Other pools and donors", [("other", "Axes and maps"), ("other/axes", "Axes only")]),
            ("Own samples", [("own", "Axes and maps"), ("own/axes", "Axes only")]),
            ("Paired cells only", [("paired_only", "Best of eight methods")]),
            ("All 118 atlas patients", [("atlas", "Unweighted maps"), ("full/reweighted", "Reweighted maps"),
                                        ("atlas/axes", "No maps")]),
            ("B cells and CD14 monocytes from 15", [("few_B_mono/mapped", "Unweighted maps"),
                                                    ("few_B_mono/reweighted", "Reweighted maps"),
                                                    ("few_B_mono/axes", "No maps")]),
            ("CD4 and CD8 T cells from 15", [("few_T/mapped", "Unweighted maps"),
                                             ("few_T/reweighted", "Reweighted maps"),
                                             ("few_T/axes", "No maps")])]
    lines = [HEADER, "\\begin{tabular}{@{}l" + "r" * len(b) + "r@{}}", "\\toprule",
             " & \\multicolumn{%d}{c}{Recovered (\\%%) with paired cells} & Paired cells \\\\" % len(b),
             "\\cmidrule(lr){2-%d}" % (len(b) + 1),
             "Reference and version & " + " & ".join(str(x) for x in b) + " & to the target (95\\% CI) \\\\"]
    for k, (group, arms) in enumerate(rows):
        lines.append("\\midrule" if k in (0, 4) else "\\addlinespace")
        if k == 4:
            lines.append(f"\\multicolumn{{{len(b) + 2}}}{{@{{}}l}}{{\\textit{{Reweighting the atlas}}}} \\\\")
        lines.append(f"\\multicolumn{{{len(b) + 2}}}{{@{{}}l}}{{{group}}} \\\\")
        for arm, label in arms:
            a = vr["arms"][arm]
            c = ("$>$800" if a["relation"] == ">" else
                 f"{a['cells']:.0f} ({a['cells_ci'][0]:.0f}--{a['cells_ci'][1]:.0f})")
            lines.append(f"\\quad {label} & " + " & ".join(pct(v) for v in a["rf"]) + f" & {c} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(lines) + "\n"


# ------------------------------------------------------------------ readout: truths and the association test

TRUTH_ROWS = [("primary", "Broad types (published)"), ("fine", "Finer states"),
              ("technical", "Technical covariates"), ("both", "Both")]


def truths_table(vr, budget=100):
    """Supplementary Table: the atlas estimate minus each comparator with 100 paired cells, under each held-out
    truth, with 95% intervals from resampling donors."""
    i = vr["budgets"].index(budget)
    tv = vr["truth_variants"]
    lines = [HEADER, "\\begin{tabular}{@{}lrrlrrr@{}}", "\\toprule",
             " & & & & \\multicolumn{3}{c}{Estimator minus comparator (points)} \\\\", "\\cmidrule(l){5-7}",
             "Held-out truth & Units & Associations & Comparator & Direction (E1) & Top 100 (E2) & Recovered \\\\",
             "\\midrule"]
    for k, (v, label) in enumerate(TRUTH_ROWS):
        t = tv[v]
        for j, (comp, clab) in enumerate((("paired_only", "Paired only"), ("regression", "Regression"))):
            cells_ = [label if j == 0 else "", str(t["units_scored"]) if j == 0 else "",
                      f"{t['reproducible']:,}" if j == 0 else "", clab]
            for e in ("E1", "E2", "recovered_fraction"):
                d = t[e]["atlas_minus"][comp]
                lo, hi = d["ci"][i]
                cells_.append(f"{pct(d['difference'][i])} ({pct(lo)} to {pct(hi)})")
            lines.append(" & ".join(cells_) + " \\\\")
        if k < len(TRUTH_ROWS) - 1:
            lines.append("\\addlinespace")
    lines += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(lines) + "\n"


def fisher_table(rc):
    lv = ("P<=0.05", "P<=0.01", "P<=0.001")
    lines = [HEADER, "\\begin{tabular}{@{}lrrrr@{}}", "\\toprule",
             " & & \\multicolumn{3}{c}{Share of null tests at or below (\\%)} \\\\", "\\cmidrule(l){3-5}",
             "Cells per half & Tests & 5\\% & 1\\% & 0.1\\% \\\\", "\\midrule"]
    for k, v in rc["by_cells_per_sub_half"].items():
        if not v["pairs"]:
            continue
        lab = k.replace("-more", " or more").replace("-", "--").replace(" cells", "")
        lines.append(f"{lab} & {v['pairs']:,} & " + " & ".join(f"{100 * v[x]:.2f}" for x in lv) + " \\\\")
    o = rc["overall"]
    tot = sum(v["pairs"] for v in rc["by_cells_per_sub_half"].values())
    lines.append(f"All & {tot:,} & " + " & ".join(f"{100 * o[x]:.2f}" for x in lv) + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(lines) + "\n"


def readout_check_macros(rc, vr, m):
    o, rep = rc["overall"], rc["replicability"]
    m["RvFisherUnits"] = str(rc["units"])
    m["RvFisherPerm"] = str(rc["permutations"])
    m["RvFisherFive"] = f"{100 * o['P<=0.05']:.2f}"
    m["RvFisherOne"] = f"{100 * o['P<=0.01']:.2f}"
    m["RvFisherTenth"] = f"{100 * o['P<=0.001']:.3f}"
    bins = [(k, v) for k, v in rc["by_cells_per_sub_half"].items() if v["pairs"]]
    k0, small = bins[0]                                            # the smallest halves that occur
    lo, hi = k0.replace(" cells", "").split("-")
    m["RvFisherSmallRange"] = f"{lo} to {hi}" if hi != "more" else f"{lo} or more"
    m["RvFisherSmallLo"] = lo
    m["RvFisherSmallOne"] = f"{100 * small['P<=0.01']:.2f}"
    m["RvFisherSmallFive"] = f"{100 * small['P<=0.05']:.2f}"
    m["RvFisherSmallTenth"] = f"{100 * small['P<=0.001']:.2f}"
    rates = [v["P<=0.01"] for _, v in bins]
    m["RvFisherOneMin"], m["RvFisherOneMax"] = f"{100 * min(rates):.2f}", f"{100 * max(rates):.2f}"
    m["RvReplNull"] = f"{1e5 * rep['null_rate']:.1f}"          # per 100,000 pairs
    m["RvReplNominal"] = f"{1e5 * rep['nominal_rate']:.1f}"
    m["RvReplObserved"] = f"{100 * rep['observed_rate']:.1f}"
    m["RvReplFalseShare"] = f"{100 * rep['implied_false_share']:.2f}"
    if vr is not None:
        tv = vr["truth_variants"]
        i = vr["budgets"].index(100)
        diffs = [tv[v][e]["atlas_minus"][c]["difference"][i] for v in ("fine", "technical", "both")
                 for e in ("E1", "E2") for c in ("paired_only",)]
        m["RvTruthMinusPoMin"], m["RvTruthMinusPoMax"] = pct(min(diffs)), pct(max(diffs))


# ------------------------------------------------------------------ one draw, one atlas

def onedraw_table(vr, ab):
    d = vr["single_draw"]
    lines = [HEADER, "\\begin{tabular}{@{}lrrr@{}}", "\\toprule",
             " & Paired cells, estimator & Saving over paired-only (V1) & Regression over estimator (K2) \\\\",
             "\\midrule", "\\multicolumn{4}{@{}l}{\\textit{Each draw of paired cells on its own (atlas fixed)}} \\\\"]
    for k, v in sorted(d["per_draw"].items(), key=lambda kv: int(kv[0])):
        lines.append(f"\\quad Draw {int(k) + 1} & {v['atlas_cells']:.0f} & {v['V1']:.2f} & {v['K2']:.2f} \\\\")
    lines.append(f"\\quad One draw per fold, donors resampled & & {d['V1']['median']:.2f} "
                 f"({d['V1']['ci'][0]:.2f}--{d['V1']['ci'][1]:.2f}) & {d['K2']['median']:.2f} "
                 f"({d['K2']['ci'][0]:.2f}--{d['K2']['ci'][1]:.2f}) \\\\")
    if ab is not None:
        lines += ["\\addlinespace", "\\multicolumn{4}{@{}l}{\\textit{Atlas patients resampled (first draw)}} \\\\"]
        for k, v in sorted(ab["replicates"].items(), key=lambda kv: int(kv[0])):
            lab = "Every patient once" if int(k) < 0 else f"Replicate {int(k) + 1}"
            lines.append(f"\\quad {lab} & {v['atlas_cells']:.0f} & {v['V1']:.2f} & {v['K2']:.2f} \\\\")
        if "with_donor_resampling" in ab:
            w = ab["with_donor_resampling"]
            o = ab["over_replicates"]
            lines.append(f"\\quad Replicates and donors resampled & & {o['V1']['median']:.2f} "
                         f"({w['V1_ci'][0]:.2f}--{w['V1_ci'][1]:.2f}) & {o['K2']['median']:.2f} "
                         f"({w['K2_ci'][0]:.2f}--{w['K2_ci'][1]:.2f}) \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(lines) + "\n"


def onedraw_macros(vr, ab, m):
    d = vr["single_draw"]
    for k, w, nd in (("V1", "VOne", 1), ("K2", "KTwo", 2)):          # savings to one decimal, K2 to two
        vals = [v[k] for v in d["per_draw"].values()]
        m[f"RvDraw{w}Min"], m[f"RvDraw{w}Max"] = f"{min(vals):.{nd}f}", f"{max(vals):.{nd}f}"
        m[f"RvDraw{w}Med"] = f"{d[k]['median']:.{nd}f}"
        m[f"RvDraw{w}Lo"], m[f"RvDraw{w}Hi"] = (f"{x:.{nd}f}" for x in d[k]["ci"])
        m[f"RvDraw{w}Share"] = f"{100 * d[k]['share_above_one']:.0f}"
    cells_ = [v["atlas_cells"] for v in d["per_draw"].values()]
    m["RvDrawCellsMin"], m["RvDrawCellsMax"] = f"{min(cells_):.0f}", f"{max(cells_):.0f}"
    if ab is not None and "over_replicates" in ab:
        o, w = ab["over_replicates"], ab["with_donor_resampling"]
        reps = [v for k, v in ab["replicates"].items() if int(k) >= 0]
        m["RvAtlasReps"] = str(len(reps))
        m["RvAtlasKTwoMin"], m["RvAtlasKTwoMax"] = (f"{x:.2f}" for x in o["K2"]["range"])
        m["RvAtlasKTwoMed"] = f"{o['K2']['median']:.2f}"
        m["RvAtlasKTwoLo"], m["RvAtlasKTwoHi"] = (f"{x:.2f}" for x in w["K2_ci"])
        m["RvAtlasKTwoAbove"] = f"{sum(v['K2'] > 1 for v in reps)}"
        m["RvAtlasKTwoShare"] = f"{100 * w['K2_share_above_one']:.0f}"
        m["RvAtlasVOneMin"], m["RvAtlasVOneMax"] = (f"{x:.1f}" for x in o["V1"]["range"])
        m["RvAtlasVOneLo"], m["RvAtlasVOneHi"] = (f"{x:.1f}" for x in w["V1_ci"])
        cells_ = [v["atlas_cells"] for v in reps]
        m["RvAtlasCellsMin"], m["RvAtlasCellsMax"] = f"{min(cells_):.0f}", f"{max(cells_):.0f}"
        base = ab["replicates"].get("-1")
        if base is not None:
            m["RvAtlasBaseCells"], m["RvAtlasBaseKTwo"] = f"{base['atlas_cells']:.0f}", f"{base['K2']:.2f}"


# ------------------------------------------------------------------ the law with data sets as units; the pilot design

DS_LABEL = {"sln111": "Mouse lymphoid organs, 111 proteins", "sln206": "Mouse lymphoid organs, 206 proteins",
            "fafb_vpn": "Fly visual neurons, FlyWire", "banc_vpn": "Fly visual neurons, BANC",
            "human_gaba": "Human cortex Patch-seq", "pbmc10k": "Human blood", "malt10k": "Human MALT lymphoma",
            "bmcite": "Human bone marrow", "fetal_cortex": "Human fetal cortex, RNA--chromatin",
            "snare_cortex": "Mouse cortex, RNA--chromatin"}


def err_pct(log2err):
    return f"{100 * (2 ** log2err - 1):.0f}"


def lawunits_table(inf):
    lines = [HEADER, "\\begin{tabular}{@{}lrrrr@{}}", "\\toprule",
             "Data set & Problems & Median error (\\%) & Observed / law & Without this data set (\\%) \\\\"]
    for tg, lab in (("0.5", "Half of the dependence recovered (primary)"), ("0.3", "30\\% recovered"),
                    ("0.7", "70\\% recovered")):
        r = inf[tg]
        lines += ["\\midrule", f"\\multicolumn{{5}}{{@{{}}l}}{{\\textit{{{lab}}}}} \\\\"]
        for n, v in r["per_dataset"].items():
            loo = r["leave_one_out"][n]
            lines.append(f"\\quad {DS_LABEL.get(n, n)} & {v['problems']} & {err_pct(v['median_abs_log2'])} & "
                         f"{2 ** v['median_log2']:.2f} & {'--' if loo is None else err_pct(loo)} \\\\")
        lo, hi = r["median_abs_log2_ci_datasets"]
        slo, shi = r["median_abs_log2_ci_studies"]
        lines.append(f"\\quad All & {r['estimable']} & {err_pct(r['median_abs_log2'])} "
                     f"({err_pct(lo)}--{err_pct(hi)}; studies {err_pct(slo)}--{err_pct(shi)}) & & \\\\")
        extra = []
        if "dataset_means" in r:
            dm = r["dataset_means"]
            extra.append(f"rank correlation of data-set means {dm['rho']:.2f} "
                         f"(exact $P={dm['p_one_sided_exact']:.3f}$, "
                         f"{dm['datasets']} data sets)")
        if "within_dataset_permutation" in r:
            w = r["within_dataset_permutation"]
            extra.append(f"problem-level $\\rho={w['rho']:.2f}$, permutations within data sets "
                         f"$P={w['p_one_sided']:.3f}$ "
                         f"({w['permutations']:,})")
        sl = r["slope_fixed_effects"]
        if sl.get("ci"):
            extra.append(f"slope with data-set effects {sl['slope']:.2f} ({sl['ci'][0]:.2f}--{sl['ci'][1]:.2f})")
        if extra:
            lines.append(f"\\multicolumn{{5}}{{@{{}}p{{.95\\textwidth}}}}{{\\quad {'; '.join(extra)}.}} \\\\")
        reasons = {}
        for x in r["non_estimable"]:
            reasons[x["reason"]] = reasons.get(x["reason"], 0) + 1
        txt = "; ".join(f"{v} {k}" for k, v in sorted(reasons.items(), key=lambda kv: -kv[1]))
        lines.append(f"\\multicolumn{{5}}{{@{{}}p{{.95\\textwidth}}}}{{\\quad Not measurable: {txt}.}} \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(lines) + "\n"


def law_macros(inf, m):
    for tg, w in (("0.5", "Half"), ("0.3", "Three"), ("0.7", "Seven")):
        r = inf[tg]
        m[f"RvLaw{w}N"] = str(r["estimable"])
        m[f"RvLaw{w}Sets"] = str(len(r["datasets"]))
        m[f"RvLaw{w}Err"] = err_pct(r["median_abs_log2"])
        m[f"RvLaw{w}ErrLo"], m[f"RvLaw{w}ErrHi"] = (err_pct(x) for x in r["median_abs_log2_ci_datasets"])
        m[f"RvLaw{w}ErrStLo"], m[f"RvLaw{w}ErrStHi"] = (err_pct(x) for x in r["median_abs_log2_ci_studies"])
        loo = [v for v in r["leave_one_out"].values() if v is not None]
        if loo:
            m[f"RvLaw{w}LooMin"], m[f"RvLaw{w}LooMax"] = err_pct(min(loo)), err_pct(max(loo))
        signed_ = [v["median_log2"] for v in r["per_dataset"].values()]
        m[f"RvLaw{w}Over"] = str(sum(x < 0 for x in signed_))
        if "within_dataset_permutation" in r:
            wp = r["within_dataset_permutation"]
            m[f"RvLaw{w}WithinP"] = f"{wp['p_one_sided']:.3f}"
            m[f"RvLaw{w}WithinPerm"] = f"{wp['permutations']:,}"
            m[f"RvLaw{w}WithinPMin"] = f"{1 / wp['permutations']:.3f}"
        if "dataset_means" in r:
            dm = r["dataset_means"]
            m[f"RvLaw{w}MeansRho"] = f"{dm['rho']:.2f}"
            m[f"RvLaw{w}MeansP"] = f"{dm['p_one_sided_exact']:.3f}"
        sl = r["slope_fixed_effects"]
        m[f"RvLaw{w}Slope"] = f"{sl['slope']:.2f}"
        if sl.get("ci"):
            m[f"RvLaw{w}SlopeLo"], m[f"RvLaw{w}SlopeHi"] = (f"{x:.2f}" for x in sl["ci"])
        reasons = {}
        for x in r["non_estimable"]:
            reasons[x["reason"]] = reasons.get(x["reason"], 0) + 1
        m[f"RvLaw{w}NonN"] = str(len(r["non_estimable"]))
        m[f"RvLaw{w}NotReached"] = str(reasons.get("a curve does not reach the target within the budgets", 0))
        m[f"RvLaw{w}Below"] = str(reasons.get("target below both curves at the smallest budget", 0))
        m[f"RvLaw{w}OneAbove"] = str(reasons.get("one curve starts above the target", 0))


def pilot_records(path=REV / "law"):
    per = {}
    for p in sorted(Path(path).glob("pilot_*.json")):
        per[p.stem[len("pilot_"):]] = load(p)
    return per


def pilot_summary(per, targets=("0.3", "0.5", "0.7"), pilots=("50", "100", "200")):
    """Per target and pilot size, over problems (each weighted alike): the distribution of each problem's median
    achieved recovered fraction, the share of replicates reaching the target (and within 0.05), the flagged share,
    and the chosen total over the paired cells the observed curve needs."""
    out = {}
    for a in targets:
        rec = {}
        for m_ in pilots + ("reservoir",):
            med, reach, near, flag, tot, ratio, by_set = [], [], [], [], [], [], {}
            for name, probs in per.items():
                for tag, pr in probs.items():
                    ta = pr["targets"][a]
                    if m_ == "reservoir":
                        if "reservoir_law" not in ta:
                            continue
                        x = np.array(ta["reservoir_law"]["achieved"])
                        t = np.full(len(x), ta["reservoir_law"]["total"], float)
                        f = np.zeros(len(x), bool)
                    else:
                        v = ta["pilots"].get(m_) or next((w for w in ta["pilots"].values()
                                                          if int(m_) in w["labels"]), None)
                        if v is None:
                            continue
                        x, t, f = np.array(v["achieved"]), np.array(v["total"], float), np.array(v["flagged"])
                    med.append(float(np.median(x)))
                    reach.append(float(np.mean(x >= float(a))))
                    near.append(float(np.mean(x >= float(a) - 0.05)))
                    flag.append(float(np.mean(f)))
                    tot.append(float(np.median(t)))
                    if ta["observed_relation"] == "=":
                        ratio.append(float(np.median(t / ta["observed_cells"])))
                    by_set.setdefault(name, []).append(float(np.mean(x >= float(a) - 0.05)))
            if not med:
                continue
            rec[m_] = {"problems": len(med), "median_achieved": float(np.median(med)),
                       "iqr_achieved": np.percentile(med, [25, 75]).tolist(),
                       "share_reaching": float(np.mean(reach)), "share_within": float(np.mean(near)),
                       "share_flagged": float(np.mean(flag)), "median_total": float(np.median(tot)),
                       "median_total_over_needed": float(np.median(ratio)) if ratio else None,
                       "problems_with_needed": len(ratio),
                       "within_by_dataset": {k: float(np.mean(v)) for k, v in by_set.items()}}
        out[a] = rec
    return out


def pilot_table(ps):
    lines = [HEADER, "\\begin{tabular}{@{}llrrrrrrr@{}}", "\\toprule",
             " & & & Achieved & Reached & Reached target & & Budget / & Flagged \\\\",
             "Target & Pilot & Problems & (\\%; IQR) & (\\%) & $-$5 points (\\%) & Budget & needed & (\\%) \\\\",
             "\\midrule"]
    for a, rec in ps.items():
        for k, (m_, v) in enumerate(rec.items()):
            lab = "All reservoir cells" if m_ == "reservoir" else f"{m_} cells"
            q1, q3 = v["iqr_achieved"]
            ratio_ = "--" if v["median_total_over_needed"] is None else f"{v['median_total_over_needed']:.2f}"
            lines.append(" & ".join([f"{100 * float(a):.0f}\\%" if k == 0 else "", lab, str(v["problems"]),
                                     f"{100 * v['median_achieved']:.0f} ({100 * q1:.0f}--{100 * q3:.0f})",
                                     f"{100 * v['share_reaching']:.0f}", f"{100 * v['share_within']:.0f}",
                                     f"{v['median_total']:.0f}", ratio_, f"{100 * v['share_flagged']:.0f}"]) + " \\\\")
        lines.append("\\addlinespace")
    lines = lines[:-1] + ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(lines) + "\n"


def pilot_macros(ps, m):
    for a, w in (("0.3", "Three"), ("0.5", "Half"), ("0.7", "Seven")):
        if a not in ps:
            continue
        for m_, mw in (("50", "Fifty"), ("100", "Hundred"), ("200", "TwoHundred"), ("reservoir", "Res")):
            v = ps[a].get(m_)
            if v is None:
                continue
            key = f"RvPilot{w}{mw}"
            m[f"{key}Achieved"] = f"{100 * v['median_achieved']:.0f}"
            m[f"{key}Reached"] = f"{100 * v['share_reaching']:.0f}"
            m[f"{key}Within"] = f"{100 * v['share_within']:.0f}"
            m[f"{key}Flagged"] = f"{100 * v['share_flagged']:.0f}"
            m[f"{key}Budget"] = f"{v['median_total']:.0f}"
            if v["median_total_over_needed"] is not None:
                m[f"{key}Ratio"] = f"{v['median_total_over_needed']:.2f}"
            m[f"{key}Problems"] = str(v["problems"])


PILOT_STYLE = {"50": ("mark=triangle*,mark size=1.8pt,color=protcol!45", -.24),
               "100": ("mark=triangle*,mark size=1.8pt,color=protcol!75", -.08),
               "200": ("mark=triangle*,mark size=1.8pt,color=protcol", .08),
               "reservoir": ("mark=diamond,mark size=2.1pt,color=black", .24)}


def pilot_panel(ps, at, name, title, common):
    """Achieved recovered fraction when a pilot chooses the total budget (pilot included), per target: median over
    problems of each problem's median, with the interquartile range over problems; pilot sizes and the law with all
    reservoir cells."""
    styles = PILOT_STYLE
    targets = [a for a in ("0.3", "0.5", "0.7") if a in ps]
    lines = [f"\\begin{{axis}}[name={name},{at}scale only axis,width=.2\\textwidth,height=.2\\textwidth,"
             f"xmin=.5,xmax={len(targets) + .5},ymin=0,ymax=100,"
             f"xtick={{{','.join(str(k) for k in range(1, len(targets) + 1))}}},"
             "xticklabels={" + ",".join(f"{100 * float(a):.0f}\\%" for a in targets) + "},ytick={0,20,40,60,80,100},"
             f"xlabel={{Target}},ylabel={{Achieved (\\%)}},title={{{title}}},{common}]"]
    for k, a in enumerate(targets, start=1):
        t = 100 * float(a)
        lines.append(f"\\draw[dashed,black!45] (axis cs:{k - .4},{t:.0f}) -- (axis cs:{k + .4},{t:.0f});")
        for m_, (style, dx) in styles.items():
            v = ps[a].get(m_)
            if v is None:
                continue
            q1, q3 = (100 * x for x in v["iqr_achieved"])
            color = style.split("color=")[1]
            lines.append(f"\\draw[color={color},line width=.7pt] (axis cs:{k + dx:.2f},{q1:.1f}) -- "
                         f"(axis cs:{k + dx:.2f},{q3:.1f});")
            lines.append(f"\\addplot[only marks,{style}] "
                         f"coordinates {{ ({k + dx:.2f},{100 * v['median_achieved']:.1f}) }};")
    lines.append("\\end{axis}")
    return lines


# ------------------------------------------------------------------ fixed accuracy (benchmark and external test)

def fixed_table(br):
    lines = [HEADER, "\\begin{tabular}{@{}lrrrrrrrr@{}}", "\\toprule",
             " & \\multicolumn{4}{c}{Raw curves} & \\multicolumn{4}{c}{Running maximum} \\\\",
             "\\cmidrule(lr){2-5}\\cmidrule(l){6-9}",
             "Recovered & Estimable & Geometric mean & Above & Below & Estimable & Geometric mean & Above & Below \\\\",
             "\\midrule"]
    for L, v in br["levels"].items():
        cells_ = [f"{100 * float(L):.0f}\\%"]
        for mode in ("raw", "running_max"):
            w = v[mode]
            gm = "--" if w["geometric_mean"] is None else f"{w['geometric_mean']:.2f}"
            c = w["counts"]
            cells_ += [str(w["estimable"]), gm, str(c.get("unresolved above", 0)),
                       str(c.get("unresolved below", 0) + c.get("one curve below", 0))]
        lines.append(" & ".join(cells_) + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(lines) + "\n"


def fixed_detail_table(br, levels=("0.1", "0.2", "0.3")):
    names = [n for n in GEN_LABEL if n in br["datasets"]] + [n for n in br["datasets"] if n not in GEN_LABEL]
    lines = [HEADER, "\\begin{tabular}{@{}l" + "r" * len(levels) + "@{}}", "\\toprule",
             "Data set & " + " & ".join(f"{100 * float(L):.0f}\\% recovered" for L in levels) + " \\\\", "\\midrule"]
    for n in names:
        cells_ = []
        for L in levels:
            v = br["datasets"][n]["levels"][L]["raw"]
            if v["kind"] == "estimable":
                ci = v.get("ci")
                cells_.append(f"{v['ratio']:.2f}" + (f" ({ci[0]:.2f}--{ci[1]:.2f})" if ci else ""))
            elif v["kind"] == "unresolved above":
                both = v["estimator_relation"] == "above" and v["paired_only_relation"] == "above"
                cells_.append("not reached" if both else ("paired only not reached"
                                                          if v["paired_only_relation"] == "above"
                                                          else "estimator not reached"))
            elif v["kind"] == "one curve below":
                cells_.append("estimator above at 25" if v["estimator_relation"] == "below"
                              else "paired only above at 25")
            else:
                cells_.append("both above at 25")
        lines.append(f"{GEN_LABEL.get(n, n)} & " + " & ".join(cells_) + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}"]
    return "\n".join(lines) + "\n"


GEN_LABEL = {"external": "External test (OverCITE-seq)", "hao": "Blood (Hao)", "stephenson": "Blood (Stephenson)",
             "bmmc_cite": "Bone marrow CITE-seq", "colon": "Colon", "bmmc_multiome": "Bone marrow RNA--chromatin",
             "gouwens_visp": "Patch-seq, visual cortex", "scala_m1": "Patch-seq, motor cortex",
             "banc": "Fly, female", "malecns": "Fly, male"}


NUM_WORD = ["no", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten"]


def fixed_macros(br, m):
    for L, w in (("0.1", "Ten"), ("0.2", "Twenty"), ("0.3", "Thirty")):
        v = br["levels"][L]["raw"]
        m[f"RvFixed{w}N"] = str(v["estimable"])
        m[f"RvFixed{w}Gm"] = "--" if v["geometric_mean"] is None else f"{v['geometric_mean']:.1f}"
        m[f"RvFixed{w}Above"] = str(v["counts"].get("unresolved above", 0))
        m[f"RvFixed{w}Below"] = str(v["counts"].get("unresolved below", 0) + v["counts"].get("one curve below", 0))
        ests = [x[1] for x in v["per_dataset"].values() if x[0] == "estimable"]
        if ests:
            m[f"RvFixed{w}Min"], m[f"RvFixed{w}Max"] = f"{min(ests):.1f}", f"{max(ests):.1f}"
        # the reasons, from the per-data-set records: paired-only alone not reaching the level, neither reaching it,
        # and the estimator already above it with the smallest budget
        recs = [d["levels"][L]["raw"] for d in br["datasets"].values()]
        above = [r for r in recs if r["kind"] == "unresolved above"]
        m[f"RvFixed{w}PoAbove"] = NUM_WORD[sum(r["estimator_relation"] != "above" for r in above)]
        m[f"RvFixed{w}BothAbove"] = NUM_WORD[sum(r["estimator_relation"] == "above" for r in above)]
        m[f"RvFixed{w}EstBelow"] = NUM_WORD[sum(r["kind"] == "one curve below" and r["estimator_relation"] == "below"
                                                for r in recs)]
    m["RvFixedSameRunningMax"] = "none" if all(
        br["levels"][L]["raw"]["counts"] == br["levels"][L]["running_max"]["counts"] for L in br["levels"]) else "some"
    m["RvFixedSets"] = str(len(br["datasets"]))
