#!/usr/bin/env python3
"""Numbers of Supplementary Notes, Tables, Figures and Propositions for the main text.

The main text cites the Supplementary Information by label, \\Sref{tab:pred}, so that its numbers follow the
Supplementary Information. LaTeX numbers sections, captions and propositions in source order, so the numbers are
read from the source of the Supplementary Information (supplement.tex and the files it inputs) without compiling
it; with --aux, they are also checked against a compiled supplement.aux.

    python si_refs.py --out ../../revision/source                      # writes si_refs.tex
    python si_refs.py --out /tmp/x --aux path/to/supplement.aux        # and checks against a compiled build
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path

HERE = Path(__file__).resolve().parent
SOURCE = HERE.parent.parent / "revision" / "source"
KINDS = ("sec:", "tab:", "sfig:", "prop:")
TOKEN = re.compile(r"\\input\{([^}]+)\}|\\section(\*?)\{|\\begin\{(table|figure|proposition|longtable)\}|\\caption\b|"
                   r"\\begin\{(equation)\}|\\label\{([^}]+)\}|\\end\{(table|figure|longtable)\}")


def strip_comments(text):
    return "\n".join(re.sub(r"(?<!\\)%.*", "", line) for line in text.splitlines())


def static_labels(source):
    count = {"section": 0, "table": 0, "figure": 0, "proposition": 0, "equation": 0}
    state = {"current": None, "env": None}
    out = {}

    def walk(name):
        text = strip_comments((source / name).read_text())
        for m in TOKEN.finditer(text):
            inp, star, env, eq, label, end = m.groups()
            if inp:
                f = inp if inp.endswith(".tex") else inp + ".tex"
                if (source / f).exists():
                    walk(f)
            elif star is not None and m.group(0).startswith("\\section"):
                if star == "":
                    count["section"] += 1
                    state["current"] = str(count["section"])
            elif env in ("table", "figure", "longtable"):
                state["env"] = "table" if env == "longtable" else env
            elif env == "proposition":
                count["proposition"] += 1
                state["current"] = f"S{count['proposition']}"
            elif m.group(0) == "\\caption" and state["env"]:
                count[state["env"]] += 1
                state["current"] = str(count[state["env"]])
            elif eq:
                count["equation"] += 1
                state["current"] = str(count["equation"])
            elif label:
                if label.startswith(KINDS):
                    out[label] = state["current"]
            elif end:
                state["env"] = None

    walk("supplement.tex")
    return out


def aux_labels(aux_text):
    out = {}
    for m in re.finditer(r"\\newlabel\{([^}]*)\}\{\{([^}]*)\}", aux_text):
        if m.group(1).startswith(KINDS):
            out[m.group(1)] = m.group(2)
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=str(SOURCE))
    ap.add_argument("--source", default=str(SOURCE))
    ap.add_argument("--aux")
    a = ap.parse_args()
    lab = static_labels(Path(a.source))
    if a.aux:
        compiled = aux_labels(Path(a.aux).read_text(errors="replace"))
        diff = {k: (lab.get(k), compiled.get(k)) for k in set(lab) | set(compiled) if lab.get(k) != compiled.get(k)}
        assert not diff, f"source order and compiled numbers differ: {diff}"
    lines = ["% Generated by extension/synthesis/si_refs.py. Do not edit.", "\\makeatletter"]
    for k in sorted(lab):
        lines.append(f"\\expandafter\\def\\csname siref@{k}\\endcsname{{{lab[k]}}}")
    lines += ["\\makeatother",
              "\\newcommand{\\Sref}[1]{\\ifcsname siref@#1\\endcsname\\csname siref@#1\\endcsname"
              "\\else\\textbf{??}\\typeout{Undefined supplementary label #1}\\fi}"]
    Path(a.out, "si_refs.tex").write_text("\n".join(lines) + "\n")
    print(len(lab), "labels" + (", checked against the compiled build" if a.aux else ""))


if __name__ == "__main__":
    main()
